# Generated by Django 5.2.10 on 2026-01-24 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        ('telemetry', '0005_processingrule_telemetryformula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('code', models.SlugField(max_length=100, unique=True, verbose_name='Código Único')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('logic', models.JSONField(default=dict, help_text="Definición JSON de la condición (ej: {'field': 'flow', 'operator': '<', 'value': 0.5})", verbose_name='Lógica de Regla')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Regla de Cumplimiento',
                'verbose_name_plural': 'Reglas de Cumplimiento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompliancePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(help_text='Ej: Temporada de Riego 2024', max_length=200, verbose_name='Nombre del Periodo')),
                ('valid_from', models.DateTimeField(verbose_name='Válido Desde')),
                ('valid_to', models.DateTimeField(verbose_name='Válido Hasta')),
                ('is_active', models.BooleanField(default=True, help_text='Si este periodo está habilitado para validación', verbose_name='Activo')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_periods', to='telemetry.catchmentpoint', verbose_name='Punto de Captación')),
                ('rules', models.ManyToManyField(blank=True, related_name='periods', to='compliance.compliancerule', verbose_name='Reglas Aplicables')),
            ],
            options={
                'verbose_name': 'Periodo de Cumplimiento',
                'verbose_name_plural': 'Periodos de Cumplimiento',
                'ordering': ['-valid_from'],
                'indexes': [models.Index(fields=['point', 'valid_from', 'valid_to'], name='compliance__point_i_21aa2a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComplianceVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('data_timestamp', models.DateTimeField(help_text='Fecha y hora REAL que declara el dato (puede diferir de la creación)', verbose_name='Fecha del Dato')),
                ('data_snapshot', models.JSONField(default=dict, help_text='Copia inmutable de los datos enviados (JSON)', verbose_name='Snapshot de Datos')),
                ('voucher_status', models.CharField(choices=[('PENDING', 'Pendiente de Envío'), ('SENT', 'Enviado Exitosamente'), ('ERROR', 'Error en Envío'), ('IGNORED', 'Ignorado por Regla'), ('REJECTED', 'Rechazado por Autoridad')], default='PENDING', max_length=50, verbose_name='Estado del Voucher')),
                ('voucher_code', models.CharField(blank=True, help_text='ID retornado por la DGA/SMA', max_length=200, null=True, verbose_name='Código/Voucher Autoridad')),
                ('request_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload Enviado')),
                ('response_payload', models.JSONField(blank=True, default=dict, verbose_name='Respuesta Recibida')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generado El')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_vouchers', to='telemetry.catchmentpoint', verbose_name='Punto de Captación')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='compliance.complianceprovider', verbose_name='Proveedor')),
                ('telemetry_record', models.ForeignKey(blank=True, help_text='Referencia al registro crudo original si existe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_vouchers', to='telemetry.telemetryrecord', verbose_name='Registro Origen (Evidence)')),
                ('variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_vouchers', to='telemetry.corevariable', verbose_name='Variable (Opcional)')),
            ],
            options={
                'verbose_name': 'Comprobante de Cumplimiento (Voucher)',
                'verbose_name_plural': 'Comprobantes de Cumplimiento',
                'ordering': ['-data_timestamp'],
                'indexes': [models.Index(fields=['point', 'data_timestamp'], name='compliance__point_i_8238b2_idx'), models.Index(fields=['voucher_status'], name='compliance__voucher_8f9dc6_idx'), models.Index(fields=['voucher_code'], name='compliance__voucher_c3dbb2_idx')],
            },
        ),
    ]
