# Generated by Django 5.2.10 on 2026-01-22 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telemetry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IkoluModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('code', models.CharField(help_text="Identificador único (ej: 'mi_pozo', 'dga', 'reportes')", max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Módulo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('api_permission_codename', models.CharField(blank=True, help_text='Permiso Django requerido para acceder a este módulo', max_length=100, verbose_name='Codename de Permiso')),
                ('frontend_route', models.CharField(blank=True, help_text="Ruta en el frontend Ikolu (ej: '/dashboard/mi-pozo')", max_length=200, verbose_name='Ruta Frontend')),
                ('icon', models.CharField(blank=True, help_text='Nombre del icono FontAwesome o similar', max_length=50, verbose_name='Icono')),
                ('color_code', models.CharField(default='#007bff', max_length=20, verbose_name='Color Hex')),
                ('base_price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Mensual Base')),
                ('is_core', models.BooleanField(default=False, help_text='Los módulos core están siempre activos y no se pueden desactivar', verbose_name='Módulo Core')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de Visualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Módulo Ikolu',
                'verbose_name_plural': 'Módulos Ikolu',
                'db_table': 'subscriptions_module',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('code', models.CharField(help_text="Identificador único (ej: 'MENSUAL', 'ANUAL')", max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Plan')),
                ('duration_months', models.IntegerField(help_text='1=Mensual, 3=Trimestral, 6=Semestral, 12=Anual', verbose_name='Duración (meses)')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Descuento sobre el precio base mensual', max_digits=5, verbose_name='Descuento (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de Visualización')),
            ],
            options={
                'verbose_name': 'Plan de Suscripción',
                'verbose_name_plural': 'Planes de Suscripción',
                'db_table': 'subscriptions_plan',
                'ordering': ['order', 'duration_months'],
            },
        ),
        migrations.CreateModel(
            name='PointModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, help_text='Dejar vacío para acceso indefinido', null=True, verbose_name='Fecha de Término')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_module_access', to=settings.AUTH_USER_MODEL, verbose_name='Otorgado por')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_access', to='subscriptions.ikolumodule', verbose_name='Módulo')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_access', to='telemetry.catchmentpoint', verbose_name='Punto de Captación')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_access', to='subscriptions.subscriptionplan', verbose_name='Plan de Suscripción')),
            ],
            options={
                'verbose_name': 'Acceso a Módulo',
                'verbose_name_plural': 'Accesos a Módulos',
                'db_table': 'subscriptions_pointmoduleaccess',
                'ordering': ['point', 'module__order'],
                'unique_together': {('point', 'module')},
            },
        ),
    ]
