# Generated by Django 4.2.23 on 2026-07-05 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0072_alter_alertchannel_modified_alter_alertrule_modified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('external_id', models.CharField(blank=True, default='', help_text='ID del dispositivo en la plataforma del proveedor.', max_length=300, verbose_name='ID externo')),
                ('serial_number', models.CharField(blank=True, default='', max_length=300, verbose_name='Número de serie')),
                ('model', models.CharField(blank=True, default='', max_length=300, verbose_name='Modelo')),
                ('firmware_version', models.CharField(blank=True, default='', max_length=200, verbose_name='Firmware')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Variables, offsets y factores. Ej: {"pulses_factor": 1000, "variables": ["pulses", "nivel"]}', verbose_name='Configuración')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de activación')),
            ],
            options={
                'verbose_name': 'Dispositivo (void)',
                'verbose_name_plural': 'Dispositivos (void)',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre')),
                ('code_internal', models.CharField(blank=True, default='', max_length=300, verbose_name='Código interno')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('lat', models.CharField(blank=True, default='', max_length=120, verbose_name='Latitud')),
                ('lon', models.CharField(blank=True, default='', max_length=120, verbose_name='Longitud')),
                ('frequency_minutes', models.PositiveIntegerField(default=60, help_text='Frecuencia de telemetría: 1, 5, 10, 15, 30, 60, etc.', verbose_name='Frecuencia (minutos)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('installed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de instalación')),
                ('decommissioned_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('project', models.CharField(blank=True, default='', max_length=300, verbose_name='Proyecto')),
                ('client', models.CharField(blank=True, default='', max_length=300, verbose_name='Cliente')),
                ('migration_status', models.CharField(choices=[('not_started', 'No iniciado'), ('shadow', 'Shadow mode'), ('migrated', 'Migrado'), ('rolled_back', 'Rollback')], db_index=True, default='not_started', max_length=20, verbose_name='Estado de migración')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Metadatos extra')),
                ('legacy_point', models.ForeignKey(blank=True, help_text='Vínculo opcional con CatchmentPoint. Null = punto nativo void.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='void_points', to='core.catchmentpoint', verbose_name='Punto legacy')),
            ],
            options={
                'verbose_name': 'Punto de captación (void)',
                'verbose_name_plural': 'Puntos de captación (void)',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PointGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('points', models.ManyToManyField(blank=True, related_name='groups', to='void.point', verbose_name='Puntos')),
            ],
            options={
                'verbose_name': 'Grupo de puntos',
                'verbose_name_plural': 'Grupos de puntos',
            },
        ),
        migrations.CreateModel(
            name='ProcessingSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Versión')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('applies_to', models.JSONField(blank=True, default=dict, help_text='Ej: {"providers": ["tdata"], "point_groups": ["grupo_a"], "devices": ["uuid"]}', verbose_name='Aplica a')),
            ],
            options={
                'verbose_name': 'Esquema de procesamiento',
                'verbose_name_plural': 'Esquemas de procesamiento',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='VoidUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('operator', 'Operador'), ('client_admin', 'Administrador de Cliente'), ('viewer', 'Visualizador')], default='viewer', max_length=20, verbose_name='Rol')),
                ('phone', models.CharField(blank=True, default='', max_length=120, verbose_name='Teléfono')),
                ('timezone', models.CharField(blank=True, default='America/Santiago', max_length=80, verbose_name='Zona horaria')),
                ('notification_preferences', models.JSONField(blank=True, default=dict, help_text='Ej: {"email": true, "sms": false, "whatsapp": false}', verbose_name='Preferencias de notificación')),
                ('legacy_user_id', models.PositiveIntegerField(blank=True, help_text='ID del usuario en api.core.User para migración futura.', null=True, verbose_name='ID usuario legacy')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='void_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de usuario (void)',
                'verbose_name_plural': 'Perfiles de usuario (void)',
            },
        ),
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('metric', models.CharField(choices=[('uptime', 'Disponibilidad (%)'), ('data_latency_minutes', 'Latencia de datos (minutos)'), ('last_connection_hours', 'Horas desde última conexión'), ('battery_level', 'Nivel de batería'), ('signal_level', 'Nivel de señal'), ('missing_variables', 'Variables faltantes')], max_length=40, verbose_name='Métrica')),
                ('operator', models.CharField(choices=[('<', 'Menor que'), ('<=', 'Menor o igual que'), ('>', 'Mayor que'), ('>=', 'Mayor o igual que'), ('==', 'Igual a'), ('!=', 'Distinto de')], default='>', max_length=4, verbose_name='Operador')),
                ('threshold', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Umbral')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Advertencia'), ('critical', 'Crítico')], default='warning', max_length=20, verbose_name='Severidad')),
                ('escalation_minutes', models.PositiveIntegerField(default=0, help_text='0 = sin escalamiento automático.', verbose_name='Minutos para escalamiento')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('point_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_policies', to='void.pointgroup', verbose_name='Grupo de puntos')),
            ],
            options={
                'verbose_name': 'Política SLA',
                'verbose_name_plural': 'Políticas SLA',
            },
        ),
        migrations.CreateModel(
            name='SLAEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('started_at', models.DateTimeField(verbose_name='Iniciado el')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resuelto el')),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('acknowledged', 'Reconocido'), ('resolved', 'Resuelto')], db_index=True, default='open', max_length=20, verbose_name='Estado')),
                ('observed_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Valor observado')),
                ('message', models.CharField(blank=True, default='', max_length=500, verbose_name='Mensaje')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_events', to='void.device', verbose_name='Dispositivo')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='void.slapolicy', verbose_name='Política')),
            ],
            options={
                'verbose_name': 'Evento SLA',
                'verbose_name_plural': 'Eventos SLA',
            },
        ),
        migrations.CreateModel(
            name='RawReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('variable', models.CharField(choices=[('pulses', 'Pulsos'), ('total', 'Total acumulado'), ('flow', 'Caudal'), ('nivel', 'Nivel'), ('water_table', 'Nivel freático'), ('battery', 'Batería'), ('signal', 'Señal'), ('temperature', 'Temperatura'), ('other', 'Otro')], db_index=True, max_length=40, verbose_name='Variable')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Timestamp del logger')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Recibido en')),
                ('raw_value', models.CharField(help_text='Valor original como string para preservar precisión del proveedor.', max_length=400, verbose_name='Valor crudo')),
                ('unit', models.CharField(blank=True, default='', max_length=50, verbose_name='Unidad')),
                ('provider_payload', models.JSONField(blank=True, default=dict, help_text='Fragmento reducido del payload original para trazabilidad.', verbose_name='Payload del proveedor')),
                ('ingest_task_id', models.CharField(blank=True, default='', max_length=200, verbose_name='Task ID de ingesta')),
                ('is_valid', models.BooleanField(default=True, help_text='False si falló validación básica de formato.', verbose_name='Válido')),
                ('validation_error', models.CharField(blank=True, default='', max_length=500, verbose_name='Error de validación')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_readings', to='void.device', verbose_name='Dispositivo')),
            ],
            options={
                'verbose_name': 'Lectura cruda (void)',
                'verbose_name_plural': 'Lecturas crudas (void)',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('step_type', models.CharField(choices=[('filter', 'Filtrar'), ('transform', 'Transformar'), ('validate', 'Validar'), ('calculate', 'Calcular'), ('aggregate', 'Agregar')], max_length=20, verbose_name='Tipo de paso')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre')),
                ('input_variables', models.JSONField(blank=True, default=list, help_text='Ej: ["pulses", "total"]', verbose_name='Variables de entrada')),
                ('output_variable', models.CharField(blank=True, default='', max_length=80, verbose_name='Variable de salida')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Parámetros específicos del tipo de paso.', verbose_name='Configuración')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='void.processingschema', verbose_name='Esquema')),
            ],
            options={
                'verbose_name': 'Paso de procesamiento',
                'verbose_name_plural': 'Pasos de procesamiento',
                'ordering': ['schema', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('condition', models.JSONField(default=dict, help_text='Ej: {"operator": "<", "variable": "pulses", "value": 0}', verbose_name='Condición')),
                ('action', models.CharField(choices=[('keep', 'Mantener valor'), ('drop', 'Descartar lectura'), ('flag_error', 'Marcar error'), ('keep_last_valid', 'Usar último válido'), ('interpolate', 'Interpolar'), ('set_value', 'Fijar valor')], max_length=20, verbose_name='Acción')),
                ('action_params', models.JSONField(blank=True, default=dict, help_text='Ej: {"value": 0} para set_value.', verbose_name='Parámetros de acción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='void.processingstep', verbose_name='Paso')),
            ],
            options={
                'verbose_name': 'Regla de procesamiento',
                'verbose_name_plural': 'Reglas de procesamiento',
                'ordering': ['step', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('variable', models.CharField(db_index=True, max_length=40, verbose_name='Variable')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Timestamp')),
                ('pulses', models.IntegerField(blank=True, null=True, verbose_name='Pulsos')),
                ('total', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Total (m³)')),
                ('flow', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Caudal (l/s o m³/s según config)')),
                ('nivel', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Nivel (m)')),
                ('water_table', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Nivel freático (m)')),
                ('total_diff', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Consumo en período (m³)')),
                ('total_today_diff', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Consumo hoy (m³)')),
                ('is_reset', models.BooleanField(default=False, verbose_name='Reset detectado')),
                ('is_reconnection', models.BooleanField(default=False, verbose_name='Reconexión')),
                ('is_interpolated', models.BooleanField(default=False, verbose_name='Interpolado')),
                ('is_error', models.BooleanField(default=False, verbose_name='Error')),
                ('error_message', models.CharField(blank=True, default='', max_length=500, verbose_name='Mensaje de error')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='Procesado el')),
                ('processor_version', models.CharField(blank=True, default='', max_length=50, verbose_name='Versión del procesador')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_readings', to='void.device', verbose_name='Dispositivo')),
                ('processing_schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_readings', to='void.processingschema', verbose_name='Esquema de procesamiento')),
                ('raw_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed', to='void.rawreading', verbose_name='Lectura cruda origen')),
            ],
            options={
                'verbose_name': 'Lectura procesada (void)',
                'verbose_name_plural': 'Lecturas procesadas (void)',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PointPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('permission', models.CharField(choices=[('view', 'Ver'), ('change', 'Editar'), ('admin', 'Administrar')], default='view', max_length=20, verbose_name='Permiso')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='void.pointgroup', verbose_name='Grupo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_permissions', to='void.voiduserprofile', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Permiso sobre grupo',
                'verbose_name_plural': 'Permisos sobre grupos',
            },
        ),
        migrations.CreateModel(
            name='DeviceHardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('component_type', models.CharField(choices=[('logger', 'Logger / Datalogger'), ('sensor_flow', 'Sensor de caudal'), ('sensor_level', 'Sensor de nivel'), ('antenna', 'Antena'), ('battery', 'Batería'), ('solar_panel', 'Panel solar'), ('modem', 'Módem'), ('other', 'Otro')], db_index=True, max_length=30, verbose_name='Tipo de componente')),
                ('serial', models.CharField(blank=True, default='', max_length=300, verbose_name='Número de serie')),
                ('model', models.CharField(blank=True, default='', max_length=300, verbose_name='Modelo')),
                ('manufacturer', models.CharField(blank=True, default='', max_length=300, verbose_name='Fabricante')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='Fecha de instalación')),
                ('warranty_until', models.DateField(blank=True, null=True, verbose_name='Garantía hasta')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('replaced', 'Reemplazado'), ('decommissioned', 'Dado de baja'), ('spare', 'Repuesto')], db_index=True, default='active', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware', to='void.device', verbose_name='Dispositivo')),
            ],
            options={
                'verbose_name': 'Componente de hardware',
                'verbose_name_plural': 'Componentes de hardware',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='point',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='void.point', verbose_name='Punto'),
        ),
        migrations.AddField(
            model_name='device',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='void_devices', to='core.telemetryprovider', verbose_name='Proveedor de telemetría'),
        ),
        migrations.AddIndex(
            model_name='voiduserprofile',
            index=models.Index(fields=['role', 'is_active'], name='void_voidus_role_acefb0_idx'),
        ),
        migrations.AddIndex(
            model_name='voiduserprofile',
            index=models.Index(fields=['legacy_user_id'], name='void_voidus_legacy__0ea085_idx'),
        ),
        migrations.AddIndex(
            model_name='slaevent',
            index=models.Index(fields=['device', 'status', 'started_at'], name='void_slaeve_device__228c45_idx'),
        ),
        migrations.AddIndex(
            model_name='slaevent',
            index=models.Index(fields=['policy', 'status'], name='void_slaeve_policy__19cf6f_idx'),
        ),
        migrations.AddIndex(
            model_name='rawreading',
            index=models.Index(fields=['device', 'variable', 'timestamp'], name='void_rawrea_device__2b183b_idx'),
        ),
        migrations.AddIndex(
            model_name='rawreading',
            index=models.Index(fields=['device', 'timestamp'], name='void_rawrea_device__2d4981_idx'),
        ),
        migrations.AddIndex(
            model_name='rawreading',
            index=models.Index(fields=['timestamp', 'is_valid'], name='void_rawrea_timesta_0c1944_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='processingstep',
            unique_together={('schema', 'order')},
        ),
        migrations.AddIndex(
            model_name='processedreading',
            index=models.Index(fields=['device', 'variable', 'timestamp'], name='void_proces_device__86fbb7_idx'),
        ),
        migrations.AddIndex(
            model_name='processedreading',
            index=models.Index(fields=['device', 'timestamp'], name='void_proces_device__742271_idx'),
        ),
        migrations.AddIndex(
            model_name='processedreading',
            index=models.Index(fields=['is_error', 'timestamp'], name='void_proces_is_erro_af527e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='processedreading',
            unique_together={('device', 'variable', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='pointpermission',
            unique_together={('user', 'group', 'permission')},
        ),
        migrations.AddIndex(
            model_name='point',
            index=models.Index(fields=['client', 'project'], name='void_point_client_506053_idx'),
        ),
        migrations.AddIndex(
            model_name='point',
            index=models.Index(fields=['is_active', 'frequency_minutes'], name='void_point_is_acti_898482_idx'),
        ),
        migrations.AddIndex(
            model_name='point',
            index=models.Index(fields=['legacy_point', 'migration_status'], name='void_point_legacy__1dc075_idx'),
        ),
        migrations.AddIndex(
            model_name='devicehardware',
            index=models.Index(fields=['device', 'component_type', 'status'], name='void_device_device__1f8897_idx'),
        ),
        migrations.AddIndex(
            model_name='devicehardware',
            index=models.Index(fields=['warranty_until', 'status'], name='void_device_warrant_68709c_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['provider', 'is_active'], name='void_device_provide_8a4072_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['external_id'], name='void_device_externa_e71b64_idx'),
        ),
    ]
