# Generated by Django 4.2.23 on 2026-07-05 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('void', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('protocol', models.CharField(choices=[('HTTP_REST', 'HTTP REST (JSON)'), ('HTTP_GET', 'HTTP GET simple'), ('MQTT', 'MQTT Broker'), ('WEBSOCKET', 'WebSocket'), ('CUSTOM', 'Custom / Script')], default='HTTP_REST', max_length=20, verbose_name='Protocolo')),
                ('base_url', models.URLField(blank=True, help_text='Ej: https://api.twindimension.com/tdata/v1 o mqtt://broker.smarthydro.cl:1883', max_length=500, verbose_name='URL base')),
                ('auth_type', models.CharField(choices=[('NONE', 'Sin autenticación'), ('BASIC', 'Basic Auth'), ('BEARER', 'Bearer Token'), ('API_KEY_HEADER', 'API Key en Header'), ('API_KEY_QUERY', 'API Key en Query Param'), ('OAUTH2_PASSWORD', 'OAuth2 Password'), ('OAUTH2_CLIENT', 'OAuth2 Client Credentials'), ('CUSTOM', 'Custom')], default='NONE', max_length=20, verbose_name='Tipo de autenticación')),
                ('auth_config', models.JSONField(blank=True, default=dict, help_text='Ej: {"username": "x", "password": "y"}, {"token": "abc"}, {"api_key": "k", "header_name": "X-API-Key"}', verbose_name='Configuración de autenticación')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Config extra del proveedor. Ej: timeout, retry, parser default.', verbose_name='Metadatos')),
            ],
            options={
                'verbose_name': 'Proveedor (void)',
                'verbose_name_plural': 'Proveedores (void)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MqttTopicConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('topic_template', models.CharField(help_text='Variables: {external_id}, {variable}, {point_code}. Ej: devices/{external_id}/{variable}', max_length=500, verbose_name='Template de topic')),
                ('qos', models.IntegerField(choices=[(0, 'At most once (0)'), (1, 'At least once (1)'), (2, 'Exactly once (2)')], default=1, verbose_name='QoS')),
                ('payload_parser', models.JSONField(blank=True, default=dict, help_text='Ej: {"value_field": "v", "timestamp_field": "ts", "unit_field": "u"}', verbose_name='Parser de payload')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mqtt_topics', to='void.provider', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Topic MQTT',
                'verbose_name_plural': 'Topics MQTT',
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='device',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='void.provider', verbose_name='Proveedor de telemetría'),
        ),
        migrations.CreateModel(
            name='ProviderEndpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('endpoint_type', models.CharField(choices=[('AUTH', 'Autenticación / Login'), ('TOKEN_REFRESH', 'Refrescar token'), ('INGEST', 'Ingesta de lecturas'), ('HEALTH', 'Health check'), ('DEVICE_INFO', 'Info de dispositivo'), ('WEBHOOK', 'Webhook receptor'), ('CUSTOM', 'Custom')], db_index=True, max_length=20, verbose_name='Tipo de endpoint')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre')),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=10, verbose_name='Método HTTP')),
                ('path_template', models.CharField(blank=True, default='', help_text='Variables: {base_url}, {external_id}, {variable}, {token}, etc.', max_length=500, verbose_name='Template de ruta')),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Ej: {"Content-Type": "application/json"}', verbose_name='Headers')),
                ('query_params', models.JSONField(blank=True, default=dict, help_text='Variables soportadas: {startTs}, {endTs}, {limit}, {variable}.', verbose_name='Query params')),
                ('body_template', models.JSONField(blank=True, default=dict, help_text='Solo para POST/PUT/PATCH. Variables: {username}, {password}, {token}.', verbose_name='Body template')),
                ('response_parser', models.JSONField(blank=True, default=dict, help_text='Ej: {"root": "data", "value_field": "value", "timestamp_field": "ts", "timestamp_format": "iso"}', verbose_name='Parser de respuesta')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='void.provider', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Endpoint de proveedor',
                'verbose_name_plural': 'Endpoints de proveedores',
                'ordering': ['provider', 'endpoint_type', 'order'],
                'unique_together': {('provider', 'endpoint_type', 'order')},
            },
        ),
    ]
