# Generated by Django 4.2.23 on 2026-07-05 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('void', '0002_provider_mqtttopicconfig_alter_device_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShadowRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('variable', models.CharField(max_length=80, verbose_name='Variable')),
                ('window_start', models.DateTimeField(verbose_name='Inicio ventana')),
                ('window_end', models.DateTimeField(verbose_name='Fin ventana')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Ejecutando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('skipped', 'Omitido')], db_index=True, default='pending', max_length=20, verbose_name='Estado')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Mensaje de error')),
                ('legacy_count', models.PositiveIntegerField(default=0, verbose_name='Registros legacy')),
                ('void_count', models.PositiveIntegerField(default=0, verbose_name='Registros void')),
                ('matched_count', models.PositiveIntegerField(default=0, verbose_name='Coincidencias')),
                ('mismatched_count', models.PositiveIntegerField(default=0, verbose_name='Diferencias')),
                ('legacy_only_count', models.PositiveIntegerField(default=0, verbose_name='Solo en legacy')),
                ('void_only_count', models.PositiveIntegerField(default=0, verbose_name='Solo en void')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shadow_runs', to='void.device', verbose_name='Dispositivo')),
            ],
            options={
                'verbose_name': 'Shadow run',
                'verbose_name_plural': 'Shadow runs',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ShadowComparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Timestamp')),
                ('result', models.CharField(choices=[('match', 'Coincide'), ('mismatch', 'Difiere'), ('legacy_only', 'Solo legacy'), ('void_only', 'Solo void')], db_index=True, max_length=20, verbose_name='Resultado')),
                ('legacy_value', models.CharField(blank=True, default='', max_length=400, verbose_name='Valor legacy')),
                ('void_value', models.CharField(blank=True, default='', max_length=400, verbose_name='Valor void')),
                ('legacy_record_id', models.CharField(blank=True, default='', max_length=80, verbose_name='ID registro legacy')),
                ('void_record_id', models.CharField(blank=True, default='', max_length=80, verbose_name='ID registro void')),
                ('diff', models.JSONField(blank=True, default=dict, verbose_name='Diferencias detalladas')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='void.shadowrun', verbose_name='Shadow run')),
            ],
            options={
                'verbose_name': 'Comparación shadow',
                'verbose_name_plural': 'Comparaciones shadow',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='shadowrun',
            index=models.Index(fields=['device', 'variable', '-created'], name='void_shadow_device__f28ce1_idx'),
        ),
        migrations.AddIndex(
            model_name='shadowrun',
            index=models.Index(fields=['status', '-created'], name='void_shadow_status_b199c5_idx'),
        ),
        migrations.AddIndex(
            model_name='shadowcomparison',
            index=models.Index(fields=['run', 'result'], name='void_shadow_run_id_0fa7cc_idx'),
        ),
        migrations.AddIndex(
            model_name='shadowcomparison',
            index=models.Index(fields=['run', 'timestamp'], name='void_shadow_run_id_885499_idx'),
        ),
    ]
