# Generated by Django 4.2.23 on 2026-07-05 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('void', '0003_shadowrun_shadowcomparison_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('name', models.CharField(max_length=300, verbose_name='Razón social / Nombre')),
                ('tax_id', models.CharField(blank=True, default='', max_length=100, verbose_name='RUT / Tax ID')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('prospect', 'Prospecto'), ('churned', 'De baja')], db_index=True, default='active', max_length=20, verbose_name='Estado')),
                ('contact_name', models.CharField(blank=True, default='', max_length=300, verbose_name='Nombre de contacto')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email de contacto')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=120, verbose_name='Teléfono de contacto')),
                ('billing_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email de facturación')),
                ('billing_phone', models.CharField(blank=True, default='', max_length=120, verbose_name='Teléfono de facturación')),
                ('billing_address', models.TextField(blank=True, default='', verbose_name='Dirección de facturación')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
                ('account_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clients', to='void.voiduserprofile', verbose_name='Ejecutivo a cargo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre del contrato')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('start_date', models.DateField(db_index=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(db_index=True, verbose_name='Fecha de término')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('yearly', 'Anual')], default='monthly', max_length=20, verbose_name='Ciclo de facturación')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto base')),
                ('currency', models.CharField(default='CLP', max_length=3, verbose_name='Moneda')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('pending', 'Pendiente'), ('suspended', 'Suspendido'), ('cancelled', 'Cancelado'), ('expired', 'Vencido')], db_index=True, default='pending', max_length=20, verbose_name='Estado')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='Renovación automática')),
                ('reminder_frequency', models.CharField(choices=[('once', 'Una vez'), ('daily', 'Diaria'), ('every_3_days', 'Cada 3 días'), ('weekly', 'Semanal')], default='once', help_text='Con qué frecuencia se repite el aviso de vencimiento antes de la fecha de término.', max_length=20, verbose_name='Frecuencia de recordatorio')),
                ('last_reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Último recordatorio enviado')),
                ('payment_method', models.CharField(blank=True, default='', max_length=100, verbose_name='Método de pago')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='void.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='point',
            name='client_fk',
            field=models.ForeignKey(blank=True, help_text="Entidad Cliente real. Reemplazará el campo 'client' texto en la migración.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='void.client', verbose_name='Cliente (FK)'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(db_index=True, verbose_name='Fecha de término')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('pending', 'Pendiente'), ('suspended', 'Suspendida'), ('cancelled', 'Cancelada')], db_index=True, default='active', max_length=20, verbose_name='Estado')),
                ('amount_override', models.DecimalField(blank=True, decimal_places=2, help_text='Si está vacío, usa el monto del contrato.', max_digits=15, null=True, verbose_name='Monto específico (opcional)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='void.contract', verbose_name='Contrato')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='void.point', verbose_name='Punto')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['contract', 'status', 'end_date'], name='void_subscr_contrac_6ffe2a_idx'), models.Index(fields=['point', 'status'], name='void_subscr_point_i_9ad132_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Email destinatario')),
                ('recipient_name', models.CharField(blank=True, default='', max_length=300, verbose_name='Nombre destinatario')),
                ('category', models.CharField(choices=[('subscription_reminder', 'Recordatorio de suscripción'), ('invoice_reminder', 'Recordatorio de factura'), ('invoice_overdue', 'Factura vencida'), ('sla_alert', 'Alerta SLA'), ('device_offline', 'Dispositivo offline'), ('system', 'Sistema')], db_index=True, max_length=40, verbose_name='Categoría')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push'), ('in_app', 'In-app')], default='email', max_length=20, verbose_name='Canal')),
                ('subject', models.CharField(max_length=500, verbose_name='Asunto')),
                ('body', models.TextField(verbose_name='Cuerpo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviada'), ('failed', 'Fallida'), ('read', 'Leída')], db_index=True, default='pending', max_length=20, verbose_name='Estado')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviada el')),
                ('error_message', models.CharField(blank=True, default='', max_length=500, verbose_name='Error de envío')),
                ('reference_id', models.CharField(blank=True, db_index=True, default='', help_text='Clave única para evitar duplicados de la misma notificación.', max_length=255, verbose_name='ID de referencia')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='void.client', verbose_name='Cliente')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='void.contract', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['status', 'category'], name='void_notifi_status_54753c_idx'), models.Index(fields=['recipient_email', 'status'], name='void_notifi_recipie_0c728f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('invoice_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Número de factura')),
                ('period_start', models.DateField(verbose_name='Inicio período')),
                ('period_end', models.DateField(verbose_name='Término período')),
                ('due_date', models.DateField(db_index=True, verbose_name='Fecha de vencimiento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto neto')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Impuestos')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviada'), ('paid', 'Pagada'), ('overdue', 'Vencida'), ('cancelled', 'Anulada')], db_index=True, default='draft', max_length=20, verbose_name='Estado')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviada el')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pagada el')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='void.contract', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-due_date'],
                'indexes': [models.Index(fields=['contract', 'status', 'due_date'], name='void_invoic_contrac_d1481f_idx'), models.Index(fields=['status', 'due_date'], name='void_invoic_status_136818_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['client', 'status', 'end_date'], name='void_contra_client__67d151_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status', 'end_date'], name='void_contra_status_c70bcc_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status', 'name'], name='void_client_status_0b54ca_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['tax_id'], name='void_client_tax_id_357da3_idx'),
        ),
    ]
