# Generated by Django 4.2.23 on 2026-07-05 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('void', '0004_client_contract_point_client_fk_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingstep',
            name='step_type',
            field=models.CharField(choices=[('filter', 'Filtrar'), ('transform', 'Transformar'), ('validate', 'Validar'), ('calculate', 'Calcular'), ('aggregate', 'Agregar'), ('totalizer', 'Totalizador')], max_length=20, verbose_name='Tipo de paso'),
        ),
        migrations.CreateModel(
            name='DeviceTotalizerState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('variable', models.CharField(help_text='Nombre de la variable totalizada (ej: pulses).', max_length=40, verbose_name='Variable')),
                ('pulses_factor', models.IntegerField(default=1000, help_text='(pulsos * factor) / 1000 = m³', verbose_name='Factor de pulsos')),
                ('offset', models.DecimalField(decimal_places=3, default=0, help_text='Suma de compensaciones por resets detectados (equivalente a addition).', max_digits=15, verbose_name='Offset acumulado (m³)')),
                ('max_diff_m3_per_hour', models.DecimalField(decimal_places=2, default=500, help_text='Umbral para detectar saltos masivos.', max_digits=10, verbose_name='Máx diff m³/hora')),
                ('reconnection_threshold_hours', models.DecimalField(decimal_places=2, default=2, help_text='Si el gap supera este valor se asume reconexión legítima.', max_digits=5, verbose_name='Umbral reconexión (horas)')),
                ('last_pulses', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Últimos pulsos')),
                ('last_total', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Último total (m³)')),
                ('last_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Último timestamp')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totalizer_states', to='void.device', verbose_name='Dispositivo')),
            ],
            options={
                'verbose_name': 'Estado de totalizador',
                'verbose_name_plural': 'Estados de totalizadores',
                'indexes': [models.Index(fields=['device', 'variable'], name='void_device_device__db1eba_idx')],
                'unique_together': {('device', 'variable')},
            },
        ),
        migrations.CreateModel(
            name='CounterResetLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('variable', models.CharField(max_length=40, verbose_name='Variable')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp de la medición')),
                ('reset_type', models.CharField(choices=[('ZERO_KEPT', 'Reset a 0 - total preservado'), ('PARTIAL', 'Reset parcial (0 < actual < anterior)'), ('PARTIAL_REJECTED', 'Reset parcial rechazado (sin evidencia de desconexión)'), ('NOISE_DROP', 'Caída de ruido (<1%)'), ('NEGATIVE_PULSES', 'Pulsos negativos'), ('MASSIVE_JUMP_OK', 'Salto masivo aceptado')], max_length=30, verbose_name='Tipo de reset')),
                ('last_pulses', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Pulsos anteriores')),
                ('current_pulses', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Pulsos actuales')),
                ('pulses_factor', models.IntegerField(verbose_name='Factor de pulsos')),
                ('addition_before', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Offset antes')),
                ('amount_to_add', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Volumen compensado (m³)')),
                ('addition_after', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Offset después')),
                ('total_before', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Total anterior (m³)')),
                ('total_after', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Total calculado (m³)')),
                ('is_reconnection', models.BooleanField(default=False, verbose_name='Detectado como reconexión')),
                ('time_diff_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Horas desde última medición')),
                ('days_not_connection', models.IntegerField(blank=True, null=True, verbose_name='Días sin conexión')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_reset_logs', to='void.device', verbose_name='Dispositivo')),
            ],
            options={
                'verbose_name': 'Log de reset de contador',
                'verbose_name_plural': 'Logs de resets de contadores',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', 'variable', 'timestamp'], name='void_counte_device__c314f0_idx'), models.Index(fields=['reset_type', 'timestamp'], name='void_counte_reset_t_27b421_idx')],
            },
        ),
    ]
