# Generated by Django 4.2.23 on 2026-07-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('void', '0005_totalizer_state_and_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetotalizerstate',
            name='first_total_today',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Total del primer registro válido del día actual; usado para calcular consumo diario.', max_digits=15, null=True, verbose_name='Primer total del día'),
        ),
        migrations.AddField(
            model_name='devicetotalizerstate',
            name='first_total_today_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del primer total del día'),
        ),
    ]
