# Generated by Django 4.2.23 on 2026-07-05 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('void', '0006_totalizer_daily_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('variable', models.CharField(max_length=40, verbose_name='Variable')),
                ('event_type', models.CharField(choices=[('counter_reset', 'Reset de contador'), ('massive_jump', 'Salto masivo de consumo'), ('negative_pulses', 'Pulsos negativos'), ('zero_kept', 'Pulsos cero con histórico'), ('partial_rejected', 'Caída parcial rechazada'), ('noise_drop', 'Caída de ruido'), ('device_offline', 'Dispositivo offline'), ('device_reconnected', 'Dispositivo reconectado')], db_index=True, max_length=30, verbose_name='Tipo de evento')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Advertencia'), ('critical', 'Crítico')], db_index=True, default='info', max_length=20, verbose_name='Severidad')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Timestamp de la medición')),
                ('message', models.TextField(blank=True, default='', verbose_name='Mensaje')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Datos técnicos del evento (pulsos, totales, offsets, etc.).', verbose_name='Contexto')),
                ('is_dispatched', models.BooleanField(default=False, help_text='True cuando ya se envió por los canales configurados.', verbose_name='Notificado')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True, verbose_name='Notificado el')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='void.device', verbose_name='Dispositivo')),
            ],
            options={
                'verbose_name': 'Evento de dispositivo',
                'verbose_name_plural': 'Eventos de dispositivos',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', 'event_type', 'timestamp'], name='void_device_device__177927_idx'), models.Index(fields=['severity', 'is_dispatched'], name='void_device_severit_af27e2_idx')],
            },
        ),
    ]
