# Generated by Django 4.2.23 on 2026-07-05 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('void', '0007_device_event_and_totalizer_fixes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceVariableConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('source_variable', models.CharField(db_index=True, help_text="Nombre original que envía el logger/proveedor (ej: '5000', 'flow', 'lvl').", max_length=80, verbose_name='Variable del logger')),
                ('internal_variable', models.CharField(help_text='Tipo genérico dentro del sistema.', max_length=40, verbose_name='Variable interna')),
                ('processing_type', models.CharField(choices=[('totalizer', 'Totalizador (pulsos)'), ('flow_instant', 'Caudal instantáneo'), ('flow_average', 'Caudal promedio'), ('nivel', 'Nivel'), ('battery', 'Batería'), ('signal', 'Señal'), ('temperature', 'Temperatura'), ('other', 'Otro'), ('none', 'Sin clasificar')], db_index=True, default='none', max_length=20, verbose_name='Tipo de procesamiento')),
                ('pulses_factor', models.IntegerField(default=1000, help_text='Solo aplica a totalizador: (pulsos * factor) / 1000 = m³.', verbose_name='Factor de pulsos')),
                ('offset', models.DecimalField(decimal_places=3, default=0, help_text='Suma fija al resultado (m³, metros, etc.).', max_digits=15, verbose_name='Offset')),
                ('scale', models.DecimalField(decimal_places=6, default=1, help_text='Factor multiplicador/divisor para convertir unidades del proveedor.', max_digits=15, verbose_name='Escala')),
                ('max_diff_m3_per_hour', models.DecimalField(decimal_places=2, default=500, help_text='Umbral anti-salto masivo (solo totalizador).', max_digits=10, verbose_name='Máx diff m³/hora')),
                ('reconnection_threshold_hours', models.DecimalField(decimal_places=2, default=2, help_text='Gap que se considera reconexión legítima (solo totalizador).', max_digits=5, verbose_name='Umbral reconexión (horas)')),
                ('unit', models.CharField(blank=True, default='', max_length=20, verbose_name='Unidad')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activa')),
                ('display_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Nombre visible')),
            ],
            options={
                'verbose_name': 'Configuración de variable',
                'verbose_name_plural': 'Configuraciones de variables',
            },
        ),
        migrations.AddField(
            model_name='rawreading',
            name='source_variable',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Nombre original enviado por el proveedor/logger.', max_length=80, verbose_name='Variable del logger'),
        ),
        migrations.AlterField(
            model_name='rawreading',
            name='variable',
            field=models.CharField(choices=[('pulses', 'Pulsos'), ('total', 'Total acumulado'), ('flow', 'Caudal'), ('nivel', 'Nivel'), ('water_table', 'Nivel freático'), ('battery', 'Batería'), ('signal', 'Señal'), ('temperature', 'Temperatura'), ('other', 'Otro')], db_index=True, help_text='Tipo genérico dentro del sistema.', max_length=40, verbose_name='Variable interna'),
        ),
        migrations.AddIndex(
            model_name='rawreading',
            index=models.Index(fields=['device', 'source_variable', 'timestamp'], name='void_rawrea_device__c42a69_idx'),
        ),
        migrations.AddField(
            model_name='devicevariableconfig',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_configs', to='void.device', verbose_name='Dispositivo'),
        ),
        migrations.AddIndex(
            model_name='devicevariableconfig',
            index=models.Index(fields=['device', 'processing_type', 'is_active'], name='void_device_device__960495_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='devicevariableconfig',
            unique_together={('device', 'source_variable')},
        ),
    ]
