# Generated by Django 4.2.23 on 2026-07-05 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('void', '0008_device_variable_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicevariableconfig',
            name='custom_schema',
            field=models.ForeignKey(blank=True, help_text="Schema declarativo propio de esta variable. Usado cuando processing_type='custom'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variable_configs', to='void.processingschema', verbose_name='Schema custom'),
        ),
        migrations.AlterField(
            model_name='devicevariableconfig',
            name='processing_type',
            field=models.CharField(choices=[('totalizer', 'Totalizador (pulsos)'), ('flow_instant', 'Caudal instantáneo'), ('flow_average', 'Caudal promedio'), ('nivel', 'Nivel'), ('battery', 'Batería'), ('signal', 'Señal'), ('temperature', 'Temperatura'), ('other', 'Otro'), ('custom', 'Custom (schema propio)'), ('none', 'Sin clasificar')], db_index=True, default='none', max_length=20, verbose_name='Tipo de procesamiento'),
        ),
    ]
