# Generated by Django 4.2.23 on 2026-07-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('void', '0009_device_variable_custom_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicevariableconfig',
            name='formula',
            field=models.CharField(blank=True, default='', help_text='Fórmula Python segura. Variables disponibles: value, scale, offset, y constantes del punto (d1, d2, d3, etc.).', max_length=500, verbose_name='Fórmula'),
        ),
        migrations.AddField(
            model_name='devicevariableconfig',
            name='output_field',
            field=models.CharField(blank=True, default='', help_text='Nombre del campo donde se guarda el resultado (ej: flow, nivel, ph). Si está vacío, usa internal_variable.', max_length=40, verbose_name='Campo de salida'),
        ),
        migrations.AddField(
            model_name='point',
            name='constants',
            field=models.JSONField(blank=True, default=dict, help_text='Constantes físicas del punto: d1, d2, d3, d4, d5, d6, etc.', verbose_name='Constantes del punto'),
        ),
        migrations.AddField(
            model_name='processedreading',
            name='extra_values',
            field=models.JSONField(blank=True, default=dict, help_text='Valores de variables dinámicas que no tienen campo propio.', verbose_name='Valores adicionales'),
        ),
        migrations.AlterField(
            model_name='devicevariableconfig',
            name='processing_type',
            field=models.CharField(choices=[('totalizer', 'Totalizador (pulsos)'), ('formula', 'Fórmula configurable'), ('custom', 'Custom (schema propio)'), ('none', 'Sin clasificar')], db_index=True, default='none', max_length=20, verbose_name='Tipo de procesamiento'),
        ),
    ]
