# Generated by Django 4.2.23 on 2026-07-05 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('void', '0010_devicevariableconfig_formula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingstep',
            name='step_type',
            field=models.CharField(choices=[('filter', 'Filtrar'), ('transform', 'Transformar'), ('validate', 'Validar'), ('calculate', 'Calcular'), ('aggregate', 'Agregar'), ('totalizer', 'Totalizador'), ('stateful', 'Con estado')], max_length=20, verbose_name='Tipo de paso'),
        ),
        migrations.CreateModel(
            name='DeviceVariableState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('variable', models.CharField(db_index=True, max_length=80, verbose_name='Variable')),
                ('state', models.JSONField(blank=True, default=dict, help_text='Diccionario libre mantenido por el handler stateful.', verbose_name='Estado')),
                ('last_processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Último procesamiento')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_states', to='void.device', verbose_name='Dispositivo')),
            ],
            options={
                'verbose_name': 'Estado de variable',
                'verbose_name_plural': 'Estados de variables',
                'indexes': [models.Index(fields=['device', 'variable'], name='void_device_device__5a9062_idx')],
                'unique_together': {('device', 'variable')},
            },
        ),
    ]
