# Generated by Django 4.2.23 on 2026-07-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('void', '0011_alter_processingstep_step_type_devicevariablestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingschema',
            name='is_template',
            field=models.BooleanField(db_index=True, default=False, help_text='Las plantillas se reutilizan entre múltiples variables/configuraciones.', verbose_name='Es plantilla'),
        ),
    ]
