# Generated by Django 4.2.23 on 2026-07-05 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('void', '0012_processingschema_is_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicevariableconfig',
            name='custom_schema',
            field=models.ForeignKey(blank=True, help_text="Schema declarativo propio de esta variable. Usado cuando processing_type='stateful'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variable_configs', to='void.processingschema', verbose_name='Schema stateful'),
        ),
        migrations.AlterField(
            model_name='devicevariableconfig',
            name='processing_type',
            field=models.CharField(choices=[('stateful', 'Stateful rules (motor de reglas con memoria)'), ('formula', 'Fórmula configurable'), ('none', 'Sin clasificar')], db_index=True, default='none', max_length=20, verbose_name='Tipo de procesamiento'),
        ),
    ]
