# Generated by Django 4.2.23 on 2026-07-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('void', '0013_simplify_processing_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingstep',
            name='step_type',
            field=models.CharField(choices=[('filter', 'Filtrar'), ('transform', 'Transformar'), ('validate', 'Validar'), ('calculate', 'Calcular'), ('aggregate', 'Agregar'), ('stateful', 'Con estado')], max_length=20, verbose_name='Tipo de paso'),
        ),
    ]
