# Generated by Django 4.2.23 on 2026-07-05 21:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('void', '0014_remove_totalizer_step_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('code', models.CharField(db_index=True, help_text='Identificador único. Ej: dga, sma, sea, siss.', max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('protocol', models.CharField(choices=[('HTTP_REST', 'HTTP REST (JSON)'), ('HTTP_SOAP', 'HTTP SOAP/XML'), ('WEBHOOK', 'Webhook'), ('CUSTOM', 'Custom / Script')], default='HTTP_REST', max_length=20, verbose_name='Protocolo')),
                ('auth_type', models.CharField(choices=[('NONE', 'Sin autenticación'), ('BASIC', 'Basic Auth'), ('BEARER', 'Bearer Token'), ('API_KEY_HEADER', 'API Key en Header'), ('JSON_BODY', 'Credenciales en JSON Body')], default='NONE', max_length=20, verbose_name='Autenticación')),
                ('base_url', models.URLField(blank=True, help_text='Ej: https://apimee.mop.gob.cl/api/v1', max_length=500, verbose_name='URL base')),
                ('auth_url', models.URLField(blank=True, help_text='Opcional. Solo si el login es en endpoint separado (ej: SMA /auth).', max_length=500, verbose_name='URL de autenticación')),
                ('auth_username', models.CharField(blank=True, max_length=200, verbose_name='Usuario / RUT')),
                ('auth_password', models.CharField(blank=True, max_length=200, verbose_name='Password / Clave')),
                ('auth_token', models.CharField(blank=True, max_length=500, verbose_name='Token / API Key')),
                ('auth_header_name', models.CharField(blank=True, default='Authorization', max_length=100, verbose_name='Nombre del header')),
                ('protocol_config', models.JSONField(blank=True, default=dict, help_text='\n        Config específica del protocolo en JSON.\n        DGA ejemplo:\n        {\n            "subterraneo_endpoint": "/mediciones/subterraneas",\n            "superficial_endpoint": "/mediciones/superficiales/flujometro",\n            "default_rut_empresa": "76944359-2"\n        }\n        SMA ejemplo:\n        {\n            "token_header": "Authorization",\n            "token_prefix": "Bearer"\n        }\n        ', verbose_name='Configuración del protocolo')),
                ('timeout_seconds', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Timeout (segundos)')),
                ('retry_attempts', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reintentos')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Entidad de cumplimiento',
                'verbose_name_plural': 'Entidades de cumplimiento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PointComplianceProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('external_code', models.CharField(blank=True, default='', help_text='Código de obra, device id, etc.', max_length=300, verbose_name='Código externo')),
                ('standard', models.CharField(blank=True, default='', help_text='Ej: MAYOR, MEDIO, MENOR, CMP, SIN_ESTANDAR.', max_length=100, verbose_name='Estándar')),
                ('type_key', models.CharField(blank=True, default='', help_text='Ej: SUBTERRANEO, SUPERFICIAL.', max_length=100, verbose_name='Tipo')),
                ('region', models.CharField(blank=True, default='', max_length=100, verbose_name='Región')),
                ('shac', models.CharField(blank=True, default='', max_length=300, verbose_name='Sector hidrológico (SHAC)')),
                ('flow_granted', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Caudal otorgado (l/s)')),
                ('total_granted', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Totalizado otorgado (m³)')),
                ('informant_name', models.CharField(blank=True, default='', max_length=300, verbose_name='Nombre informante')),
                ('informant_rut', models.CharField(blank=True, default='', max_length=100, verbose_name='RUT informante')),
                ('date_start_compliance', models.DateField(blank=True, null=True, verbose_name='Fecha inicio envío')),
                ('date_created_code', models.DateField(blank=True, null=True, verbose_name='Fecha creación código')),
                ('aggregate_points', models.JSONField(blank=True, default=list, help_text='Lista de IDs de puntos cuyo total se suma al enviar (ej: [84, 85]).', verbose_name='Puntos agregados')),
                ('variable_mapping', models.JSONField(blank=True, default=dict, help_text='\n        Mapea variables de ProcessedReading a campos del payload.\n        Ejemplo DGA:\n        {"total": "total", "flow": "flow", "water_table": "water_table"}\n        ', verbose_name='Mapeo de variables')),
                ('extra_config', models.JSONField(blank=True, default=dict, verbose_name='Config extra')),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_profiles', to='void.complianceauthority', verbose_name='Entidad')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_profiles', to='void.point', verbose_name='Punto')),
            ],
            options={
                'verbose_name': 'Perfil de cumplimiento',
                'verbose_name_plural': 'Perfiles de cumplimiento',
            },
        ),
        migrations.CreateModel(
            name='ComplianceSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('period_start', models.DateTimeField(blank=True, null=True, verbose_name='Inicio período')),
                ('period_end', models.DateTimeField(blank=True, null=True, verbose_name='Término período')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload enviado')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('confirmed', 'Confirmado'), ('failed', 'Fallido'), ('duplicate', 'Duplicado'), ('unrecoverable', 'Irrecuperable'), ('retrying', 'Reintentando')], db_index=True, default='pending', max_length=20, verbose_name='Estado')),
                ('attempt_number', models.PositiveIntegerField(default=0, verbose_name='Intento')),
                ('response_status', models.IntegerField(blank=True, null=True, verbose_name='HTTP status')),
                ('response_body', models.TextField(blank=True, default='', verbose_name='Respuesta cruda')),
                ('voucher', models.CharField(blank=True, default='', max_length=500, verbose_name='Comprobante / Voucher')),
                ('tracking_id', models.CharField(blank=True, default='', max_length=500, verbose_name='Tracking ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado el')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado el')),
                ('last_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='Último reintento')),
                ('error_message', models.CharField(blank=True, default='', max_length=1000, verbose_name='Mensaje de error')),
                ('processed_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_submissions', to='void.processedreading', verbose_name='Lectura procesada')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='void.pointcomplianceprofile', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Envío de cumplimiento',
                'verbose_name_plural': 'Envíos de cumplimiento',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='pointcomplianceprofile',
            index=models.Index(fields=['point', 'authority', 'is_active'], name='void_pointc_point_i_8f3dd9_idx'),
        ),
        migrations.AddIndex(
            model_name='pointcomplianceprofile',
            index=models.Index(fields=['authority', 'is_active'], name='void_pointc_authori_e9a812_idx'),
        ),
        migrations.AddIndex(
            model_name='pointcomplianceprofile',
            index=models.Index(fields=['external_code'], name='void_pointc_externa_f4cb5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pointcomplianceprofile',
            unique_together={('point', 'authority')},
        ),
        migrations.AddIndex(
            model_name='compliancesubmission',
            index=models.Index(fields=['profile', 'status', 'created'], name='void_compli_profile_7884b4_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancesubmission',
            index=models.Index(fields=['status', 'created'], name='void_compli_status_fd7896_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancesubmission',
            index=models.Index(fields=['processed_reading', 'status'], name='void_compli_process_a17484_idx'),
        ),
    ]
