# Generated by Django 4.2.23 on 2026-07-05 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('void', '0015_add_compliance_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetotalizerstate',
            options={'verbose_name': 'Estado de totalizador (deprecated)', 'verbose_name_plural': 'Estados de totalizadores (deprecated)'},
        ),
    ]
