# Generated by Django 4.2.23 on 2026-07-05 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('void', '0016_mark_totalizer_state_deprecated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceTotalizerState',
        ),
    ]
