# Generated by Django 4.2.30 on 2026-07-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('void', '0017_remove_totalizer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='shadowrun',
            name='output_field',
            field=models.CharField(blank=True, default='', help_text='Campo de ProcessedReading comparado (total, flow, nivel, water_table). Vacío = comparación cruda.', max_length=40, verbose_name='Campo procesado'),
        ),
    ]
