# Generated by Django 4.2.30 on 2026-07-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('void', '0022_add_compliance_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancestandard',
            name='minute_interval',
            field=models.PositiveIntegerField(blank=True, help_text='Ej: 5 para enviar cuando minuto % 5 == 0. Null = no usar intervalo.', null=True, verbose_name='Intervalo de minutos'),
        ),
    ]
