# Generated by Django 4.2.30 on 2026-07-06 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('void', '0023_add_compliance_standard_minute_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('code_internal', models.CharField(blank=True, default='', max_length=300, verbose_name='Código interno')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='point',
            name='void_point_client_506053_idx',
        ),
        migrations.AlterField(
            model_name='point',
            name='project',
            field=models.CharField(blank=True, default='', help_text='Campo texto legacy. Se migrará a project_fk.', max_length=300, verbose_name='Proyecto (legacy texto)'),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='void.client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='point',
            name='project_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='void.project', verbose_name='Proyecto'),
        ),
    ]
