# Generated by Django 4.2.30 on 2026-07-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('void', '0025_migrate_project_data'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='point',
            index=models.Index(fields=['client_fk', 'project_fk', 'is_active'], name='void_point_client__0a8bb2_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['client', 'is_active'], name='void_projec_client__6ad254_idx'),
        ),
    ]
