# Generated by Django 4.2.30 on 2026-07-06 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('void', '0026_add_project_point_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('event_types', models.JSONField(blank=True, default=list, help_text='Lista de códigos de DeviceEvent.event_type. Vacío = cualquiera.', verbose_name='Tipos de evento')),
                ('severities', models.JSONField(blank=True, default=list, help_text='Lista de severidades. Vacío = cualquiera.', verbose_name='Severidades')),
                ('device_ids', models.JSONField(blank=True, default=list, help_text='Lista de IDs de device. Vacío = cualquiera.', verbose_name='IDs de dispositivos')),
                ('point_ids', models.JSONField(blank=True, default=list, help_text='Lista de IDs de point. Vacío = cualquiera.', verbose_name='IDs de puntos')),
                ('variables', models.JSONField(blank=True, default=list, help_text='Lista de nombres de variable. Vacío = cualquiera.', verbose_name='Variables')),
                ('cooldown_minutes', models.PositiveIntegerField(default=60, help_text='No dispara si ya disparó para el mismo device/variable en este periodo.', verbose_name='Cooldown (minutos)')),
                ('channels', models.JSONField(default=list, help_text='Lista de canales a usar: email, sms, webhook, push, in_app.', verbose_name='Canales')),
                ('recipients', models.JSONField(blank=True, default=dict, help_text="{'emails': ['a@x.com'], 'phones': ['+569...'], 'webhook_url': 'https://...', 'user_ids': [1, 2]}", verbose_name='Destinatarios')),
                ('message_template', models.TextField(blank=True, default='', help_text='Soporta {event_type}, {device}, {variable}, {severity}, {message}, {timestamp}, {point}.', verbose_name='Plantilla de mensaje')),
            ],
            options={
                'verbose_name': 'Regla de alerta',
                'verbose_name_plural': 'Reglas de alerta',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AlertTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación.', verbose_name='modificado el')),
                ('channels', models.JSONField(default=list, verbose_name='Canales')),
                ('recipients', models.JSONField(blank=True, default=dict, verbose_name='Destinatarios')),
                ('message', models.TextField(blank=True, default='', verbose_name='Mensaje renderizado')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('dispatched', 'Enviada'), ('failed', 'Fallida')], db_index=True, default='pending', max_length=20, verbose_name='Estado')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviada el')),
                ('dispatch_result', models.JSONField(blank=True, default=dict, verbose_name='Resultado del envío')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_triggers', to='void.deviceevent', verbose_name='Evento')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='void.alertrule', verbose_name='Regla')),
            ],
            options={
                'verbose_name': 'Disparo de alerta',
                'verbose_name_plural': 'Disparos de alerta',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['rule', 'event', 'status'], name='void_alertt_rule_id_eb8d3a_idx'), models.Index(fields=['status', 'created'], name='void_alertt_status_b3db5d_idx')],
            },
        ),
    ]
