# Generated by Django 4.2.30 on 2026-07-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('void', '0028_alter_devicevariableconfig_processing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicevariableconfig',
            name='processing_type',
            field=models.CharField(choices=[('stateful', 'Stateful rules (motor de reglas con memoria)'), ('formula', 'Fórmula configurable'), ('totalizer', 'Totalizador robusto (paridad legacy)'), ('nivel', 'Nivel robusto (paridad legacy)'), ('none', 'Sin clasificar')], db_index=True, default='none', max_length=20, verbose_name='Tipo de procesamiento'),
        ),
    ]
