# Generated by Django 4.2.30 on 2026-07-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('void', '0029_alter_devicevariableconfig_processing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicevariableconfig',
            name='processing_type',
            field=models.CharField(choices=[('stateful', 'Stateful rules (motor de reglas con memoria)'), ('formula', 'Fórmula configurable'), ('passthrough', 'Paso directo (sin transformar)'), ('none', 'Sin clasificar')], db_index=True, default='none', max_length=20, verbose_name='Tipo de procesamiento'),
        ),
        migrations.AlterField(
            model_name='processingrule',
            name='action',
            field=models.CharField(help_text='Nombre de la acción registrada en el motor (stateful o pipeline).', max_length=40, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='processingrule',
            name='action_params',
            field=models.JSONField(blank=True, default=dict, help_text='Ej: {"output": "total", "formula": "value * scale"}.', verbose_name='Parámetros de acción'),
        ),
        migrations.AlterField(
            model_name='processingrule',
            name='condition',
            field=models.TextField(blank=True, default='', help_text='Expresión Python evaluable. Vacío = siempre ejecuta.', verbose_name='Condición'),
        ),
    ]
