from django.apps import AppConfig


class ProvidersConfig(AppConfig):
    """Configuración de la aplicación de proveedores dinámicos."""

    default_auto_field = 'django.db.models.BigAutoField'
    name = 'api.telemetry.providers'
    label = 'telemetry_providers'  # Evita conflicto con api.providers
    verbose_name = 'Proveedores Dinámicos (Legacy)'

    def ready(self):
        # Import metrics to register them with Prometheus on startup
        try:
            import api.telemetry.providers.metrics
            
            # Start Prometheus HTTP server only if running as Celery Worker
            # This allows scraping metrics generated by background tasks
            import sys
            import os
            from prometheus_client import start_http_server

            # Check if this process is a celery worker
            is_celery = 'celery' in sys.argv[0] or (len(sys.argv) > 1 and 'celery' in sys.argv[1])
            if is_celery and 'worker' in sys.argv:
                try:
                    # Port 9200 for Celery Worker Metrics
                    start_http_server(9200)
                    print("🚀 Metrics server started on port 9200 (Celery Worker)")
                except Exception as e:
                    print(f"⚠️ Could not start metrics server: {e}")
                    
        except ImportError:
            pass