# Generated by Django 5.2.10 on 2026-01-22 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_initial'),
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catchmentpoint',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Proyecto al que pertenece este punto de captación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='crm.project', verbose_name='Proyecto'),
        ),
    ]
