# Generated by Django 5.2.10 on 2026-01-18 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='catchmentpoint',
            table='core_catchmentpoint',
        ),
        migrations.AlterModelTable(
            name='client',
            table='core_client',
        ),
        migrations.AlterModelTable(
            name='dgadataconfigcatchment',
            table='core_dgadataconfigcatchment',
        ),
        migrations.AlterModelTable(
            name='filecatchment',
            table='core_filecatchment',
        ),
        migrations.AlterModelTable(
            name='notificationscatchment',
            table='core_notificationscatchment',
        ),
        migrations.AlterModelTable(
            name='profiledataconfigcatchment',
            table='core_profiledataconfigcatchment',
        ),
        migrations.AlterModelTable(
            name='profileikolucatchment',
            table='core_profileikolucatchment',
        ),
        migrations.AlterModelTable(
            name='projectcatchments',
            table='core_projectcatchments',
        ),
        migrations.AlterModelTable(
            name='registerpersons',
            table='core_registerpersons',
        ),
        migrations.AlterModelTable(
            name='responsenotificationscatchment',
            table='core_responsenotificationscatchment',
        ),
        migrations.AlterModelTable(
            name='typefilecatchment',
            table='core_typefilecatchment',
        ),
    ]
