# Generated by Django 5.2.10 on 2026-01-18 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_alter_catchmentpoint_table_alter_client_table_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='iotdevice',
            new_name='core_iotdev_device__122efe_idx',
            old_name='telemetry_i_device__554d85_idx',
        ),
        migrations.RenameIndex(
            model_name='iotdevice',
            new_name='core_iotdev_catchme_464ee7_idx',
            old_name='telemetry_i_catchme_c3e364_idx',
        ),
        migrations.RenameIndex(
            model_name='iotdevice',
            new_name='core_iotdev_equipme_5e1dc9_idx',
            old_name='telemetry_i_equipme_1486de_idx',
        ),
        migrations.RenameIndex(
            model_name='iotdevice',
            new_name='core_iotdev_last_se_8fbbab_idx',
            old_name='telemetry_i_last_se_172b88_idx',
        ),
        migrations.RenameIndex(
            model_name='iotdevice',
            new_name='core_iotdev_status_57116c_idx',
            old_name='telemetry_i_status_3f0680_idx',
        ),
        migrations.AlterModelTable(
            name='iotdevice',
            table='core_iotdevice',
        ),
    ]
