# Generated by Django 5.2.10 on 2026-01-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_rename_telemetry_i_device__554d85_idx_core_iotdev_device__122efe_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corevariable',
            name='type_variable',
            field=models.CharField(help_text="Identificador de la variable en el proveedor externo (ej: '5000', 'descarga', 'pc')", max_length=100, verbose_name='Clave/ID de Variable'),
        ),
    ]
