# Generated by Django 5.2.10 on 2026-01-23 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_catchmentpoint_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corevariable',
            name='provider_key',
        ),
        migrations.RemoveField(
            model_name='corevariable',
            name='type_variable',
        ),
    ]
