# Generated by Django 4.2.23 on 2026-01-20 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "telemetry",
            "0003_remove_constantapplication_telemetry_c_constan_aa37c9_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigurationScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha de creacion.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha de modificacion.",
                        verbose_name="modified at",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nombre del Esquema"),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Identificador único del esquema (ej: 'pozo_std')",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "category",
                    models.CharField(
                        default="general",
                        help_text="Ej: 'pozo', 'sensor', 'superficial'",
                        max_length=100,
                        verbose_name="Categoría",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Esquema de Configuración",
                "verbose_name_plural": "Esquemas de Configuración",
                "db_table": "telemetry_configurationscheme",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="ConfigurationSchemeField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha de creacion.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha de modificacion.",
                        verbose_name="modified at",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Identificador único dentro del esquema (ej: 'd3', 'pulses_factor')",
                        max_length=50,
                        verbose_name="Código del Campo",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre para Mostrar"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("decimal", "Decimal"),
                            ("integer", "Entero"),
                            ("text", "Texto"),
                            ("boolean", "Booleano"),
                        ],
                        default="decimal",
                        max_length=20,
                        verbose_name="Tipo de Dato",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Ej: 'mt', 'pulsos/m3', 'L/s'",
                        max_length=50,
                        verbose_name="Unidad",
                    ),
                ),
                (
                    "default_value",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Valor por Defecto"
                    ),
                ),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=15,
                        null=True,
                        verbose_name="Valor Mínimo",
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=15,
                        null=True,
                        verbose_name="Valor Máximo",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="Requerido"),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, verbose_name="Orden de Visualización"
                    ),
                ),
                (
                    "help_text",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Texto de Ayuda"
                    ),
                ),
                (
                    "is_formula_accessible",
                    models.BooleanField(
                        default=True,
                        help_text="Si está marcado, puede usarse en fórmulas como {config.code}",
                        verbose_name="Accesible en Fórmulas",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="telemetry.configurationscheme",
                        verbose_name="Esquema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campo de Esquema",
                "verbose_name_plural": "Campos de Esquema",
                "db_table": "telemetry_configurationschemefield",
                "ordering": ["display_order", "code"],
                "unique_together": {("scheme", "code")},
            },
        ),
        migrations.CreateModel(
            name="SamplingFrequency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha de creacion.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha de modificacion.",
                        verbose_name="modified at",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Identificador único (ej: '1', '5', '60')",
                        max_length=20,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ej: '1 minuto', '5 minutos', '1 hora'",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "minutes",
                    models.IntegerField(
                        help_text="Valor en minutos", verbose_name="Minutos"
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True,
                        help_text="Ej: '*/5 * * * *' para cada 5 minutos",
                        max_length=100,
                        verbose_name="Expresión Cron",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, verbose_name="Orden de Visualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Frecuencia de Muestreo",
                "verbose_name_plural": "Frecuencias de Muestreo",
                "db_table": "telemetry_samplingfrequency",
                "ordering": ["display_order", "minutes"],
            },
        ),
        migrations.CreateModel(
            name="VariableType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha de creacion.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha de modificacion.",
                        verbose_name="modified at",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Identificador único (ej: 'TOTALIZADO', 'NIVEL', 'CAUDAL')",
                        max_length=50,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "default_formula",
                    models.CharField(
                        blank=True,
                        help_text="Fórmula que se usa si CoreVariable no tiene una propia",
                        max_length=1000,
                        verbose_name="Fórmula por Defecto",
                    ),
                ),
                (
                    "required_inputs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de variables que deben existir (ej: ['pulses', 'factor'])",
                        verbose_name="Inputs Requeridos",
                    ),
                ),
                (
                    "default_unit",
                    models.CharField(
                        blank=True,
                        help_text="Ej: 'm3', 'L/s', 'mt'",
                        max_length=50,
                        verbose_name="Unidad por Defecto",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Tipo de Variable",
                "verbose_name_plural": "Tipos de Variable",
                "db_table": "telemetry_variabletype",
                "ordering": ["code"],
            },
        ),
        migrations.AlterField(
            model_name="corevariable",
            name="formula",
            field=models.CharField(
                blank=True,
                help_text="Sintaxis de fórmulas:\n- {var_code}: Valor de otra variable del punto\n- {config.codigo}: Valor de configuración del punto\n- {system.key}: Valor de SystemConfiguration\n- {prev.var_code}: Valor anterior de una variable\n- {time.diff_seconds}: Diferencia de tiempo en segundos\nEjemplo: ({pulses} * {config.pulses_factor}) / 1000 + {config.addition}",
                max_length=1000,
                null=True,
                verbose_name="Fórmula",
            ),
        ),
        migrations.AddField(
            model_name="catchmentpoint",
            name="configuration_scheme",
            field=models.ForeignKey(
                blank=True,
                help_text="Plantilla de configuración para este punto (pozo, sensor, etc.)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="points",
                to="telemetry.configurationscheme",
                verbose_name="Esquema de Configuración",
            ),
        ),
        migrations.AddField(
            model_name="catchmentpoint",
            name="frequency",
            field=models.ForeignKey(
                blank=True,
                help_text="Frecuencia dinámica de muestreo",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="points",
                to="telemetry.samplingfrequency",
                verbose_name="Frecuencia de Muestreo",
            ),
        ),
        migrations.AddField(
            model_name="corevariable",
            name="type_definition",
            field=models.ForeignKey(
                blank=True,
                help_text="Definición del tipo de variable (reemplaza type_variable hardcodeado)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variables",
                to="telemetry.variabletype",
                verbose_name="Tipo de Variable",
            ),
        ),
        migrations.CreateModel(
            name="PointConfigurationValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha de creacion.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha de modificacion.",
                        verbose_name="modified at",
                    ),
                ),
                (
                    "value",
                    models.JSONField(
                        help_text="Almacena el valor según el tipo de dato del campo",
                        verbose_name="Valor",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="telemetry.configurationschemefield",
                        verbose_name="Campo",
                    ),
                ),
                (
                    "point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuration_values",
                        to="telemetry.catchmentpoint",
                        verbose_name="Punto de Captación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor de Configuración",
                "verbose_name_plural": "Valores de Configuración",
                "db_table": "telemetry_pointconfigurationvalue",
                "indexes": [
                    models.Index(
                        fields=["point", "field"], name="telemetry_p_point_i_6f18de_idx"
                    )
                ],
                "unique_together": {("point", "field")},
            },
        ),
    ]
