# Generated by Django 5.2.10 on 2026-01-20 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "telemetry",
            "0003_remove_constantapplication_telemetry_c_constan_aa37c9_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TelemetryProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha de creacion.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha de modificacion.",
                        verbose_name="modified at",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("api", "REST API"),
                            ("mqtt", "MQTT"),
                            ("modbus", "ModBus TCP"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Proveedor",
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="URL Base"
                    ),
                ),
                (
                    "auth_method",
                    models.CharField(
                        choices=[
                            ("bearer", "Bearer Token"),
                            ("basic", "Basic Auth"),
                            ("api_key", "API Key"),
                            ("none", "Sin autenticación"),
                        ],
                        default="none",
                        max_length=50,
                        verbose_name="Método de Autenticación",
                    ),
                ),
                (
                    "auth_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Credenciales, como tokens, API keys, etc.",
                        verbose_name="Configuración de Autenticación",
                    ),
                ),
                (
                    "endpoint_template",
                    models.CharField(
                        blank=True,
                        help_text="Ej: /devices/{device_id}/data",
                        max_length=500,
                        null=True,
                        verbose_name="Plantilla de Endpoint",
                    ),
                ),
                (
                    "request_template",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Cuerpo del request para enviar datos.",
                        verbose_name="Plantilla de Request",
                    ),
                ),
                (
                    "response_mapping",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Define cómo interpretar la respuesta del proveedor.",
                        verbose_name="Mapeo de Respuesta",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Proveedor de Telemetría",
                "verbose_name_plural": "Proveedores de Telemetría",
                "db_table": "telemetry_provider",
            },
        ),
        migrations.CreateModel(
            name="CatchmentPointProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha de creacion.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha de modificacion.",
                        verbose_name="modified at",
                    ),
                ),
                (
                    "config_override",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Sobrescribe la configuración general del proveedor para este punto.",
                        verbose_name="Configuración Específica",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Prioridad de uso en caso de múltiples proveedores activos (0 es la más alta).",
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="providers",
                        to="telemetry.catchmentpoint",
                        verbose_name="Punto de Captación",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catchment_points",
                        to="telemetry.telemetryprovider",
                        verbose_name="Proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proveedor del Punto de Captación",
                "verbose_name_plural": "Proveedores del Punto de Captación",
                "db_table": "telemetry_catchmentpoint_provider",
                "ordering": ["priority"],
                "unique_together": {("point", "provider")},
            },
        ),
    ]
