# Generated by Django 4.2.23 on 2026-01-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0004_configurationscheme_configurationschemefield_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telemetryrecord",
            name="n_voucher",
        ),
        migrations.RemoveField(
            model_name="telemetryrecord",
            name="return_dga",
        ),
        migrations.RemoveField(
            model_name="telemetryrecord",
            name="send_dga",
        ),
        migrations.AddField(
            model_name="telemetryrecord",
            name="compliance_status",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Estado de envío a proveedores: {'dga': {'sent': True, 'voucher': '...'}}",
            ),
        ),
        migrations.DeleteModel(
            name="DgaDataConfigCatchment",
        ),
    ]
