# Generated by Django 5.2.10 on 2026-01-24 02:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0004_remove_corevariable_provider_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('code', models.SlugField(max_length=100, unique=True, verbose_name='Código Único')),
                ('rule_type', models.CharField(choices=[('PRE_CALC', 'Pre-Cálculo (Limpieza/Validación Raw)'), ('POST_CALC', 'Post-Cálculo (Validación Resultado/Eventos)'), ('RESET_DETECTOR', 'Detector de Reinicio (Lógica Especial)'), ('MAX_DIFF', 'Validación de Diferencia Máxima'), ('MIN_VALUE', 'Validación de Valor Mínimo'), ('MAX_VALUE', 'Validación de Valor Máximo')], max_length=50, verbose_name='Tipo de Regla')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('default_parameters', models.JSONField(blank=True, default=dict, help_text="Parámetros base para la regla (ej: {'threshold': 500})", verbose_name='Parámetros por Defecto')),
                ('is_system', models.BooleanField(default=False, verbose_name='Es de Sistema')),
            ],
            options={
                'verbose_name': 'Regla de Procesamiento',
                'verbose_name_plural': 'Reglas de Procesamiento',
                'ordering': ['rule_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('code', models.SlugField(max_length=100, unique=True, verbose_name='Código Único')),
                ('expression', models.TextField(help_text='\n        Sintaxis soportada:\n        - {value}: Valor crudo entrante\n        - {config.x}: Valor de configuración\n        - {prev.x}: Valor previo calculado\n        - Operadores: +, -, *, /, (, )\n        ', verbose_name='Expresión Matemática')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('output_unit', models.CharField(blank=True, help_text='Unidad resultante del cálculo (ej: m3, L/s)', max_length=50, verbose_name='Unidad de Salida')),
                ('is_system', models.BooleanField(default=False, help_text='Si es True, no se puede eliminar ni modificar su código.', verbose_name='Es de Sistema')),
                ('variables', models.JSONField(blank=True, default=list, help_text="Lista de tokens que esta fórmula espera (ej: ['value', 'factor'])", verbose_name='Variables Esperadas')),
            ],
            options={
                'verbose_name': 'Definición de Fórmula',
                'verbose_name_plural': 'Definiciones de Fórmulas',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='corevariable',
            name='formula',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use FormulaAssignment instead.', max_length=1000, null=True, verbose_name='Fórmula (Legacy)'),
        ),
        migrations.AlterField(
            model_name='corevariable',
            name='operation',
            field=models.CharField(choices=[('PHYSICAL', 'Dato Físico (Sensor)'), ('SUM', 'Suma'), ('DIFF', 'Resta (A - B)'), ('MUL', 'Multiplicación'), ('AVG', 'Promedio'), ('FORMULA', 'Fórmula Personalizada')], default='PHYSICAL', help_text='DEPRECATED: Use FormulaAssignment instead.', max_length=20, verbose_name='Tipo de Operación (Legacy)'),
        ),
        migrations.CreateModel(
            name='RuleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('parameters_override', models.JSONField(blank=True, default=dict, help_text='Sobreescribe los parámetros por defecto de la regla para este periodo', verbose_name='Override Parámetros')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Válido Desde')),
                ('valid_to', models.DateTimeField(blank=True, help_text='Dejar vacío para vigencia indefinida', null=True, verbose_name='Válido Hasta')),
                ('is_active', models.BooleanField(default=True, help_text='Desactivar para pausar la regla temporalmente', verbose_name='Activo')),
                ('priority', models.IntegerField(default=0, verbose_name='Prioridad')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telemetry.processingrule', verbose_name='Regla')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_assignments', to='telemetry.corevariable', verbose_name='Variable')),
            ],
            options={
                'verbose_name': 'Asignación de Regla',
                'verbose_name_plural': 'Asignaciones de Reglas',
                'ordering': ['-valid_from', '-priority'],
                'indexes': [models.Index(fields=['variable', 'valid_from', 'valid_to'], name='telemetry_r_variabl_d9f808_idx')],
            },
        ),
        migrations.CreateModel(
            name='FormulaAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Válido Desde')),
                ('valid_to', models.DateTimeField(blank=True, help_text='Dejar vacío para vigencia indefinida', null=True, verbose_name='Válido Hasta')),
                ('priority', models.IntegerField(default=0, help_text='Mayor prioridad gana en caso de solapamiento de fechas', verbose_name='Prioridad')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_assignments', to='telemetry.corevariable', verbose_name='Variable')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telemetry.telemetryformula', verbose_name='Fórmula')),
            ],
            options={
                'verbose_name': 'Asignación de Fórmula',
                'verbose_name_plural': 'Asignaciones de Fórmulas',
                'ordering': ['-valid_from', '-priority'],
                'indexes': [models.Index(fields=['variable', 'valid_from', 'valid_to'], name='telemetry_f_variabl_1d4265_idx')],
            },
        ),
    ]
