# Generated by Django 5.2.10 on 2026-01-21 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_technicalsurvey_name_alter_technicalsurvey_project'),
        ('telemetry', '0005_remove_telemetryrecord_n_voucher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catchmentpoint',
            name='technical_survey',
            field=models.OneToOneField(blank=True, help_text='El levantamiento técnico que originó este punto de captación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_point', to='crm.technicalsurvey', verbose_name='Levantamiento Técnico de Origen'),
        ),
        migrations.AlterField(
            model_name='catchmentpoint',
            name='frecuency',
            field=models.CharField(blank=True, choices=[('1', '1 minuto'), ('5', '5 minutos'), ('10', '10 minutos'), ('60', '60 minutos')], default='60', help_text="[DEP] Use el campo 'frequency' (FK) en su lugar.", max_length=300, null=True, verbose_name='Frecuencia (Legacy)'),
        ),
        migrations.AlterField(
            model_name='catchmentpoint',
            name='project',
            field=models.ForeignKey(help_text="[DEP] Use 'technical_survey.project' en su lugar.", on_delete=django.db.models.deletion.CASCADE, related_name='catchment_points', to='crm.project', verbose_name='Proyecto (Legacy)'),
        ),
    ]
