# Generated by Django 5.2.10 on 2026-01-24 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0005_processingrule_telemetryformula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Timestamp Medición')),
                ('raw_value', models.FloatField(blank=True, null=True, verbose_name='Valor Crudo')),
                ('processed_value', models.FloatField(blank=True, null=True, verbose_name='Valor Procesado (Fórmula)')),
                ('final_value', models.FloatField(verbose_name='Valor Final')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Validado')),
                ('quality_code', models.CharField(default='RAW', max_length=50, verbose_name='Código de Calidad')),
                ('tags', models.JSONField(blank=True, default=dict, help_text='Metadatos extra: trigger_rule, is_interpolated, etc.', verbose_name='Etiquetas / Metadata')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='telemetry.telemetryrecord', verbose_name='Registro Origen')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='telemetry.corevariable', verbose_name='Variable')),
            ],
            options={
                'verbose_name': 'Medición de Telemetría',
                'verbose_name_plural': 'Mediciones de Telemetría',
                'db_table': 'telemetry_measurement',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['variable', 'timestamp'], name='telemetry_m_variabl_330bb4_idx'), models.Index(fields=['record', 'variable'], name='telemetry_m_record__29f6a7_idx')],
            },
        ),
    ]
