# Generated by Django 5.2.10 on 2026-01-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_crm_task_and_more'),
        ('telemetry', '0006_catchmentpoint_technical_survey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catchmentpoint',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='bi_catchment_points', to='documents.document', verbose_name='Archivos Adjuntos'),
        ),
    ]
