# Generated by Django 5.2.10 on 2026-01-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0006_telemetrymeasurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corevariable',
            name='formula',
        ),
        migrations.RemoveField(
            model_name='corevariable',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='corevariable',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='corevariable',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='virtualvariable',
            name='formula',
        ),
        migrations.RemoveField(
            model_name='virtualvariable',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='virtualvariable',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='virtualvariable',
            name='sources',
        ),
    ]
