# Generated by Django 5.2.10 on 2026-01-21 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_data(apps, schema_editor):
    CatchmentPoint = apps.get_model('telemetry', 'CatchmentPoint')
    ProfileDataConfigCatchment = apps.get_model('telemetry', 'ProfileDataConfigCatchment')
    SamplingFrequency = apps.get_model('telemetry', 'SamplingFrequency')
    
    # 1. Migrate 'addition' from ProfileDataConfigCatchment to CatchmentPoint
    for profile in ProfileDataConfigCatchment.objects.select_related('point_catchment').all():
        if profile.point_catchment:
            point = profile.point_catchment
            point.addition = profile.addition
            point.save(update_fields=['addition'])

    # 2. Migrate 'frecuency' (string) to 'frequency' (FK)
    freq_map = {}
    for sf in SamplingFrequency.objects.all():
        freq_map[str(sf.minutes)] = sf
    
    for point in CatchmentPoint.objects.all():
        if point.frecuency and not point.frequency:
            sf = freq_map.get(str(point.frecuency))
            if sf:
                point.frequency = sf
                point.save(update_fields=['frequency'])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_costcategory_is_active_taskcategory_is_active_and_more'),
        ('documents', '0004_alter_document_crm_task_and_more'),
        ('telemetry', '0007_catchmentpoint_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catchmentpoint',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profiledataconfigcatchment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profileikolucatchment',
            options={},
        ),
        migrations.RemoveField(
            model_name='profileikolucatchment',
            name='m3_start_subscription',
        ),
        migrations.RemoveField(
            model_name='profileikolucatchment',
            name='m3_type_subscriptions',
        ),
        migrations.RemoveField(
            model_name='profileikolucatchment',
            name='m4_start_subscription',
        ),
        migrations.RemoveField(
            model_name='profileikolucatchment',
            name='m4_type_subscriptions',
        ),
        migrations.RemoveField(
            model_name='profileikolucatchment',
            name='m5_start_subscription',
        ),
        migrations.RemoveField(
            model_name='profileikolucatchment',
            name='m5_type_subscriptions',
        ),
        migrations.RemoveField(
            model_name='profileikolucatchment',
            name='m6_start_subscription',
        ),
        migrations.RemoveField(
            model_name='profileikolucatchment',
            name='m6_type_subscriptions',
        ),
        migrations.RemoveField(
            model_name='profileikolucatchment',
            name='m7_start_subscription',
        ),
        migrations.RemoveField(
            model_name='profileikolucatchment',
            name='m7_type_subscriptions',
        ),
        migrations.AddField(
            model_name='catchmentpoint',
            name='addition',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(migrate_legacy_data),
        migrations.AlterField(
            model_name='catchmentpoint',
            name='configuration_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='telemetry.configurationscheme'),
        ),
        migrations.AlterField(
            model_name='catchmentpoint',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='bi_catchment_points', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='catchmentpoint',
            name='frecuency',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='catchmentpoint',
            name='frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='telemetry.samplingfrequency'),
        ),
        migrations.AlterField(
            model_name='catchmentpoint',
            name='lat',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='catchmentpoint',
            name='lon',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='catchmentpoint',
            name='owner_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_catchment_points', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='catchmentpoint',
            name='processing_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catchment_points', to='telemetry.telemetryscheme'),
        ),
        migrations.AlterField(
            model_name='catchmentpoint',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catchment_points_legacy', to='crm.project'),
        ),
        migrations.AlterField(
            model_name='catchmentpoint',
            name='technical_survey',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_point', to='crm.technicalsurvey'),
        ),
        migrations.AlterField(
            model_name='catchmentpoint',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='catchmentpoint',
            name='users_viewers',
            field=models.ManyToManyField(blank=True, related_name='viewed_catchment_points', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='addition',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='d1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='d2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='d3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='d4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='d5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='d6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='date_delivery_act',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='date_start_telemetry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='extra_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='is_telemetry',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='point_catchment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_config_profiles', to='telemetry.catchmentpoint'),
        ),
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='token_service',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profileikolucatchment',
            name='entry_by_form',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profileikolucatchment',
            name='m1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profileikolucatchment',
            name='m2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profileikolucatchment',
            name='m3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profileikolucatchment',
            name='m4',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profileikolucatchment',
            name='m5',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profileikolucatchment',
            name='m6',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profileikolucatchment',
            name='m7',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profileikolucatchment',
            name='point_catchment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ikolu_profiles', to='telemetry.catchmentpoint'),
        ),
    ]
