# Generated by Django 5.2.10 on 2026-01-21 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_costcategory_is_active_taskcategory_is_active_and_more'),
        ('documents', '0004_alter_document_crm_task_and_more'),
        ('telemetry', '0008_alter_catchmentpoint_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileikolucatchment',
            name='point_catchment',
        ),
        migrations.AlterModelOptions(
            name='catchmentpoint',
            options={'verbose_name': 'Punto de captacion', 'verbose_name_plural': 'Puntos de captacion'},
        ),
        migrations.RemoveField(
            model_name='catchmentpoint',
            name='frecuency',
        ),
        migrations.RemoveField(
            model_name='catchmentpoint',
            name='project',
        ),
        migrations.AlterField(
            model_name='catchmentpoint',
            name='addition',
            field=models.IntegerField(default=0, help_text='Valor acumulado automáticamente cuando el sensor se reinicia.', verbose_name='Adición Acumulada (Reset)'),
        ),
        migrations.AlterField(
            model_name='catchmentpoint',
            name='configuration_scheme',
            field=models.ForeignKey(blank=True, help_text='Plantilla de configuración para este punto (pozo, sensor, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='telemetry.configurationscheme', verbose_name='Esquema de Configuración'),
        ),
        migrations.AlterField(
            model_name='catchmentpoint',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='bi_catchment_points', to='documents.document', verbose_name='Archivos Adjuntos'),
        ),
        migrations.AlterField(
            model_name='catchmentpoint',
            name='frequency',
            field=models.ForeignKey(blank=True, help_text='Frecuencia dinámica de muestreo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='telemetry.samplingfrequency', verbose_name='Frecuencia de Muestreo'),
        ),
        migrations.AlterField(
            model_name='catchmentpoint',
            name='lat',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='latitud'),
        ),
        migrations.AlterField(
            model_name='catchmentpoint',
            name='lon',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='longitud'),
        ),
        migrations.AlterField(
            model_name='catchmentpoint',
            name='owner_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_catchment_points', to=settings.AUTH_USER_MODEL, verbose_name='Propietario'),
        ),
        migrations.AlterField(
            model_name='catchmentpoint',
            name='processing_scheme',
            field=models.ForeignKey(blank=True, help_text='Esquema reutilizable de procesamiento para este punto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catchment_points', to='telemetry.telemetryscheme', verbose_name='Esquema de Telemetría'),
        ),
        migrations.AlterField(
            model_name='catchmentpoint',
            name='technical_survey',
            field=models.OneToOneField(blank=True, help_text='El levantamiento técnico que originó este punto de captación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_point', to='crm.technicalsurvey', verbose_name='Levantamiento Técnico de Origen'),
        ),
        migrations.AlterField(
            model_name='catchmentpoint',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='catchmentpoint',
            name='users_viewers',
            field=models.ManyToManyField(blank=True, related_name='viewed_catchment_points', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.DeleteModel(
            name='ProfileDataConfigCatchment',
        ),
        migrations.DeleteModel(
            name='ProfileIkoluCatchment',
        ),
    ]
