# Generated by Django 5.2.10 on 2026-01-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0009_remove_profileikolucatchment_point_catchment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catchmentpoint',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Si el punto está habilitado para telemetría.', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='catchmentpoint',
            name='point_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Punto'),
        ),
    ]
