# Generated by Django 5.2.10 on 2026-01-22 16:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0002_initial'),
        ('telemetry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('ticket_number', models.CharField(help_text='Número único del ticket (auto-generado)', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Título descriptivo del ticket', max_length=200)),
                ('description', models.TextField(help_text='Descripción detallada del problema')),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('IN_PROGRESS', 'En Progreso'), ('WAITING_CUSTOMER', 'Esperando Cliente'), ('WAITING_SUPPLIER', 'Esperando Proveedor'), ('RESOLVED', 'Resuelto'), ('CLOSED', 'Cerrado')], default='OPEN', help_text='Estado actual del ticket', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('NORMAL', 'Normal'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica'), ('EMERGENCY', 'Emergencia')], default='NORMAL', help_text='Prioridad del ticket', max_length=10)),
                ('category', models.CharField(choices=[('TECHNICAL', 'Técnico'), ('FUNCTIONAL', 'Funcional'), ('PERFORMANCE', 'Performance'), ('SECURITY', 'Seguridad'), ('DATA_QUALITY', 'Calidad de Datos'), ('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software'), ('NETWORK', 'Red'), ('MAINTENANCE', 'Mantenimiento'), ('OTHER', 'Otro')], default='TECHNICAL', help_text='Categoría del ticket', max_length=15)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_time_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('customer_satisfaction', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('tags', models.JSONField(blank=True, default=list)),
                ('attachments', models.JSONField(default=dict)),
                ('custom_fields', models.JSONField(default=dict)),
                ('affected_devices', models.ManyToManyField(blank=True, help_text='Dispositivos afectados', related_name='support_tickets', to='infrastructure.device')),
                ('affected_points', models.ManyToManyField(blank=True, help_text='Puntos de captación afectados', related_name='support_tickets', to='telemetry.catchmentpoint')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket de Soporte',
                'verbose_name_plural': 'Tickets de Soporte',
                'db_table': 'core_supportticket',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('attachments', models.JSONField(default=dict)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comments', to=settings.AUTH_USER_MODEL)),
                ('mentioned_users', models.ManyToManyField(blank=True, related_name='mentioned_in_comments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='support.supportticket')),
            ],
            options={
                'verbose_name': 'Comentario de Ticket',
                'verbose_name_plural': 'Comentarios de Tickets',
                'db_table': 'core_ticketcomment',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='TicketSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('TECHNICAL', 'Técnico'), ('FUNCTIONAL', 'Funcional'), ('PERFORMANCE', 'Performance'), ('SECURITY', 'Seguridad'), ('DATA_QUALITY', 'Calidad de Datos'), ('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software'), ('NETWORK', 'Red'), ('MAINTENANCE', 'Mantenimiento'), ('OTHER', 'Otro')], max_length=15)),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('NORMAL', 'Normal'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica'), ('EMERGENCY', 'Emergencia')], max_length=10)),
                ('response_time_hours', models.PositiveIntegerField()),
                ('resolution_time_hours', models.PositiveIntegerField()),
                ('penalty_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('business_hours_only', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SLA de Tickets',
                'verbose_name_plural': 'SLAs de Tickets',
                'db_table': 'core_ticketsla',
                'unique_together': {('category', 'priority')},
            },
        ),
    ]
