# Generated by Django 5.2.10 on 2026-01-18 23:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telemetry', '0002_alter_catchmentpoint_table_alter_client_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('ticket_number', models.CharField(help_text='Número único del ticket (auto-generado)', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Título descriptivo del ticket', max_length=200)),
                ('description', models.TextField(help_text='Descripción detallada del problema')),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('IN_PROGRESS', 'En Progreso'), ('WAITING_CUSTOMER', 'Esperando Cliente'), ('WAITING_SUPPLIER', 'Esperando Proveedor'), ('RESOLVED', 'Resuelto'), ('CLOSED', 'Cerrado')], default='OPEN', help_text='Estado actual del ticket', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('NORMAL', 'Normal'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica'), ('EMERGENCY', 'Emergencia')], default='NORMAL', help_text='Prioridad del ticket', max_length=10)),
                ('category', models.CharField(choices=[('TECHNICAL', 'Técnico'), ('FUNCTIONAL', 'Funcional'), ('PERFORMANCE', 'Performance'), ('SECURITY', 'Seguridad'), ('DATA_QUALITY', 'Calidad de Datos'), ('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software'), ('NETWORK', 'Red'), ('MAINTENANCE', 'Mantenimiento'), ('OTHER', 'Otro')], default='TECHNICAL', help_text='Categoría del ticket', max_length=15)),
                ('opened_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de apertura del ticket')),
                ('due_date', models.DateTimeField(blank=True, help_text='Fecha límite para resolución', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Fecha de resolución', null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='Fecha de cierre', null=True)),
                ('resolution_time_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Tiempo de resolución en horas', max_digits=8, null=True)),
                ('customer_satisfaction', models.PositiveIntegerField(blank=True, help_text='Satisfacción del cliente (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags para categorización adicional')),
                ('attachments', models.JSONField(default=dict, help_text='Archivos adjuntos (URLs, paths, etc.)')),
                ('custom_fields', models.JSONField(default=dict, help_text='Campos personalizados según categoría')),
                ('affected_devices', models.ManyToManyField(blank=True, help_text='Dispositivos afectados', related_name='support_tickets', to='telemetry.iotdevice')),
                ('affected_points', models.ManyToManyField(blank=True, help_text='Puntos de captación afectados', related_name='support_tickets', to='telemetry.catchmentpoint')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Usuario asignado al ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó el ticket', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket de Soporte',
                'verbose_name_plural': 'Tickets de Soporte',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('comment', models.TextField(help_text='Contenido del comentario')),
                ('is_internal', models.BooleanField(default=False, help_text='Comentario interno (solo visible para staff)')),
                ('attachments', models.JSONField(default=dict, help_text='Archivos adjuntos al comentario')),
                ('author', models.ForeignKey(help_text='Autor del comentario', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comments', to=settings.AUTH_USER_MODEL)),
                ('mentioned_users', models.ManyToManyField(blank=True, help_text='Usuarios mencionados en el comentario', related_name='mentioned_in_comments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(help_text='Ticket al que pertenece el comentario', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='support.supportticket')),
            ],
            options={
                'verbose_name': 'Comentario de Ticket',
                'verbose_name_plural': 'Comentarios de Tickets',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='TicketSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(help_text='Nombre del SLA', max_length=100)),
                ('category', models.CharField(choices=[('TECHNICAL', 'Técnico'), ('FUNCTIONAL', 'Funcional'), ('PERFORMANCE', 'Performance'), ('SECURITY', 'Seguridad'), ('DATA_QUALITY', 'Calidad de Datos'), ('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software'), ('NETWORK', 'Red'), ('MAINTENANCE', 'Mantenimiento'), ('OTHER', 'Otro')], help_text='Categoría de tickets a la que aplica', max_length=15)),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('NORMAL', 'Normal'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica'), ('EMERGENCY', 'Emergencia')], help_text='Prioridad de tickets a la que aplica', max_length=10)),
                ('response_time_hours', models.PositiveIntegerField(help_text='Tiempo máximo de respuesta inicial en horas')),
                ('resolution_time_hours', models.PositiveIntegerField(help_text='Tiempo máximo de resolución en horas')),
                ('penalty_per_hour', models.DecimalField(decimal_places=2, default=0, help_text='Penalización por hora de retraso', max_digits=8)),
                ('is_active', models.BooleanField(default=True, help_text='SLA activo')),
                ('business_hours_only', models.BooleanField(default=True, help_text='Solo contar horas hábiles')),
            ],
            options={
                'verbose_name': 'SLA de Tickets',
                'verbose_name_plural': 'SLAs de Tickets',
                'indexes': [models.Index(fields=['category', 'priority', 'is_active'], name='support_tic_categor_0e9d37_idx')],
                'unique_together': {('category', 'priority')},
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['ticket_number'], name='support_sup_ticket__4a7d4b_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'priority'], name='support_sup_status_c67c70_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['category', 'status'], name='support_sup_categor_65532e_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['created_by', 'status'], name='support_sup_created_b8c4b4_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['assigned_to', 'status'], name='support_sup_assigne_87974a_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['opened_at'], name='support_sup_opened__ea4e98_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['due_date'], name='support_sup_due_dat_42d883_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcomment',
            index=models.Index(fields=['ticket', 'created'], name='support_tic_ticket__5cafc4_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcomment',
            index=models.Index(fields=['author', 'created'], name='support_tic_author__02012d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcomment',
            index=models.Index(fields=['is_internal'], name='support_tic_is_inte_9de665_idx'),
        ),
    ]
