# Generated by Django 5.2.10 on 2026-01-19 17:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='supportticket',
            name='support_sup_ticket__4a7d4b_idx',
        ),
        migrations.RemoveIndex(
            model_name='supportticket',
            name='support_sup_status_c67c70_idx',
        ),
        migrations.RemoveIndex(
            model_name='supportticket',
            name='support_sup_categor_65532e_idx',
        ),
        migrations.RemoveIndex(
            model_name='supportticket',
            name='support_sup_created_b8c4b4_idx',
        ),
        migrations.RemoveIndex(
            model_name='supportticket',
            name='support_sup_assigne_87974a_idx',
        ),
        migrations.RemoveIndex(
            model_name='supportticket',
            name='support_sup_opened__ea4e98_idx',
        ),
        migrations.RemoveIndex(
            model_name='supportticket',
            name='support_sup_due_dat_42d883_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticketcomment',
            name='support_tic_ticket__5cafc4_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticketcomment',
            name='support_tic_author__02012d_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticketcomment',
            name='support_tic_is_inte_9de665_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticketsla',
            name='support_tic_categor_0e9d37_idx',
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='affected_devices',
            field=models.ManyToManyField(blank=True, help_text='Dispositivos afectados', related_name='support_tickets', to='infrastructure.device'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='attachments',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='custom_fields',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='customer_satisfaction',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='opened_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='resolution_time_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='attachments',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='support.supportticket'),
        ),
        migrations.AlterField(
            model_name='ticketsla',
            name='business_hours_only',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ticketsla',
            name='category',
            field=models.CharField(choices=[('TECHNICAL', 'Técnico'), ('FUNCTIONAL', 'Funcional'), ('PERFORMANCE', 'Performance'), ('SECURITY', 'Seguridad'), ('DATA_QUALITY', 'Calidad de Datos'), ('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software'), ('NETWORK', 'Red'), ('MAINTENANCE', 'Mantenimiento'), ('OTHER', 'Otro')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ticketsla',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ticketsla',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticketsla',
            name='penalty_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ticketsla',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Baja'), ('NORMAL', 'Normal'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica'), ('EMERGENCY', 'Emergencia')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ticketsla',
            name='resolution_time_hours',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ticketsla',
            name='response_time_hours',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterModelTable(
            name='supportticket',
            table='core_supportticket',
        ),
        migrations.AlterModelTable(
            name='ticketcomment',
            table='core_ticketcomment',
        ),
        migrations.AlterModelTable(
            name='ticketsla',
            table='core_ticketsla',
        ),
    ]
