# Generated by Django 5.2.10 on 2026-01-22 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre/Razón Social')),
                ('rut', models.CharField(max_length=300, verbose_name='RUT')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=300, verbose_name='Teléfono')),
                ('email', models.CharField(blank=True, max_length=300, verbose_name='Correo Electrónico')),
                ('business_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Giro/Rubro')),
                ('legal_representative', models.CharField(blank=True, max_length=300, null=True, verbose_name='Representante Legal')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('PROSPECT', 'Prospecto'), ('SUSPENDED', 'Suspendido')], default='PROSPECT', max_length=20, verbose_name='Estado')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='client_logos/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'core_client',
            },
        ),
        migrations.CreateModel(
            name='CostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Categoría')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría de Costo',
                'verbose_name_plural': 'Categorías de Costos',
            },
        ),
        migrations.CreateModel(
            name='CostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Tipo')),
                ('flow', models.CharField(choices=[('INCOME', 'Ingreso'), ('EXPENSE', 'Egreso')], default='EXPENSE', max_length=20, verbose_name='Flujo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('color_code', models.CharField(default='#333333', max_length=20, verbose_name='Color Hex')),
            ],
            options={
                'verbose_name': 'Tipo de Costo (Ingreso/Egreso)',
                'verbose_name_plural': 'Tipos de Costos',
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Cargo')),
                ('department', models.CharField(blank=True, help_text='Ej: Comercial, Técnico, Operaciones', max_length=200, null=True, verbose_name='Departamento/Área')),
            ],
            options={
                'verbose_name': 'Cargo / Puesto',
                'verbose_name_plural': 'Cargos / Puestos',
                'ordering': ['client', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombre Completo')),
                ('email', models.EmailField(blank=True, max_length=300, null=True, verbose_name='Correo')),
                ('phone', models.CharField(blank=True, max_length=300, null=True, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Contacto / Persona',
                'verbose_name_plural': 'Contactos / Personas',
                'db_table': 'core_registerpersons',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre del Proyecto')),
                ('code_internal', models.CharField(blank=True, max_length=300, null=True, verbose_name='Código Interno')),
                ('status', models.CharField(choices=[('PLANNING', 'Planificación'), ('PROPOSAL', 'Propuesta/Cotización'), ('APPROVED', 'Aprobado (Preparando Instalación)'), ('IN_PROGRESS', 'En Instalación'), ('ACTIVE', 'Activo/Operativo'), ('MAINTENANCE', 'En Mantenimiento'), ('CLOSED', 'Cerrado')], default='PLANNING', max_length=20, verbose_name='Estado')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción del Proyecto')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha Prevista Inicio')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Presupuesto Estimado')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'core_projectcatchments',
            },
        ),
        migrations.CreateModel(
            name='ProjectCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('description', models.CharField(max_length=300, verbose_name='Descripción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('is_estimated', models.BooleanField(default=True, verbose_name='Es Estimado')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha del Movimiento')),
            ],
            options={
                'verbose_name': 'Costo de Proyecto',
                'verbose_name_plural': 'Costos de Proyecto',
                'ordering': ['-date', '-created'],
            },
        ),
        migrations.CreateModel(
            name='SurveyFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Campo')),
                ('code', models.CharField(help_text='Identificador único (ej: pipe_diameter, signal_strength)', max_length=100, unique=True, verbose_name='Código')),
                ('group', models.CharField(blank=True, help_text='Agrupa campos relacionados (ej: Hidráulica, Eléctrica, Logística)', max_length=100, verbose_name='Grupo')),
                ('is_required', models.BooleanField(default=False, verbose_name='Es Obligatorio')),
                ('default_value', models.CharField(blank=True, max_length=500, verbose_name='Valor por Defecto')),
                ('help_text', models.TextField(blank=True, verbose_name='Texto de Ayuda')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de Presentación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Definición de Campo de Levantamiento',
                'verbose_name_plural': 'Definiciones de Campos de Levantamiento',
                'ordering': ['group', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SurveyFieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Tipo')),
                ('data_type', models.CharField(choices=[('TEXT', 'Texto'), ('INTEGER', 'Número Entero'), ('DECIMAL', 'Número Decimal'), ('BOOLEAN', 'Sí/No'), ('DATE', 'Fecha'), ('DATETIME', 'Fecha y Hora'), ('SELECT', 'Lista de Opciones'), ('FILE', 'Archivo')], default='TEXT', max_length=20, verbose_name='Tipo de Dato')),
                ('options', models.JSONField(blank=True, default=list, help_text="Para tipo SELECT: ['Opción 1', 'Opción 2', ...]", verbose_name='Opciones')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='Valor Mínimo')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='Valor Máximo')),
                ('regex_pattern', models.CharField(blank=True, help_text='Expresión regular para validar texto', max_length=500, verbose_name='Patrón Regex')),
            ],
            options={
                'verbose_name': 'Tipo de Campo de Levantamiento',
                'verbose_name_plural': 'Tipos de Campos de Levantamiento',
            },
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Categoría')),
                ('color_code', models.CharField(default='#333333', max_length=20, verbose_name='Color Hex')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría de Tarea',
                'verbose_name_plural': 'Categorías de Tareas',
            },
        ),
        migrations.CreateModel(
            name='TaskResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('content', models.TextField(verbose_name='Contenido de la Respuesta')),
                ('response_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Respuesta')),
            ],
            options={
                'verbose_name': 'Respuesta de Tarea',
                'verbose_name_plural': 'Respuestas de Tareas',
                'ordering': ['-response_date'],
            },
        ),
        migrations.CreateModel(
            name='TaskSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Subcategoría')),
            ],
            options={
                'verbose_name': 'Subcategoría de Tarea',
                'verbose_name_plural': 'Subcategorías de Tareas',
            },
        ),
        migrations.CreateModel(
            name='TaskSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Subtipo')),
            ],
            options={
                'verbose_name': 'Subtipo de Tarea',
                'verbose_name_plural': 'Subtipos de Tareas',
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Tipo')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icono (FontAwesome)')),
                ('color_code', models.CharField(default='#007bff', max_length=20, verbose_name='Color Hex')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('requires_response', models.BooleanField(default=False, help_text='Si está marcado, la tarea debe tener una respuesta para completarse.', verbose_name='Requiere Respuesta')),
            ],
            options={
                'verbose_name': 'Tipo de Tarea',
                'verbose_name_plural': 'Tipos de Tareas',
            },
        ),
        migrations.CreateModel(
            name='TechnicalSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(blank=True, help_text='Ej: Pozo Norte, Sector A, etc.', max_length=200, verbose_name='Nombre del Levantamiento')),
                ('gps_coordinates', models.CharField(blank=True, max_length=100, verbose_name='Coordenadas GPS')),
                ('survey_date', models.DateField(blank=True, null=True, verbose_name='Fecha del Levantamiento')),
                ('dynamic_data', models.JSONField(blank=True, default=dict, help_text="Formato: {'field_code': value, ...}", verbose_name='Datos del Levantamiento')),
                ('requires_dga', models.BooleanField(default=False, verbose_name='¿Requiere Reporte DGA?')),
                ('requires_telemetry', models.BooleanField(default=True, verbose_name='¿Requiere Telemetría?')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recomendaciones Técnicas')),
                ('notes', models.TextField(blank=True, verbose_name='Notas Adicionales')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completado'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcar para desactivar este levantamiento sin eliminarlo.', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Levantamiento Técnico',
                'verbose_name_plural': 'Levantamientos Técnicos',
                'ordering': ['-survey_date', '-created'],
            },
        ),
        migrations.CreateModel(
            name='CostSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Subcategoría')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='crm.costcategory', verbose_name='Categoría Principal')),
            ],
            options={
                'verbose_name': 'Subcategoría de Costo',
                'verbose_name_plural': 'Subcategorías de Costos',
            },
        ),
        migrations.CreateModel(
            name='CostSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Subtipo')),
                ('cost_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtypes', to='crm.costtype', verbose_name='Tipo Principal')),
            ],
            options={
                'verbose_name': 'Subtipo de Costo',
                'verbose_name_plural': 'Subtipos de Costos',
            },
        ),
        migrations.CreateModel(
            name='CrmTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('title', models.CharField(max_length=300, verbose_name='Título de la Tarea')),
                ('description', models.TextField(blank=True, verbose_name='Descripción Detallada')),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=10, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Proceso'), ('AWAITING_RESPONSE', 'Esperando Respuesta'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Límite')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completada en')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
            ],
            options={
                'verbose_name': 'Tarea CRM',
                'verbose_name_plural': 'Tareas CRM',
                'ordering': ['-priority', 'due_date'],
            },
        ),
    ]
