# Generated by Django 5.2.10 on 2026-01-22 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crmtask',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='crm_tasks', to='documents.document', verbose_name='Archivos Adjuntos'),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Cliente al que pertenece este cargo. Dejar vacío para cargos globales.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_positions', to='crm.client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='person',
            name='job_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='crm.jobposition', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='crmtask',
            name='contacts',
            field=models.ManyToManyField(blank=True, help_text='Personas del cliente involucradas en esta tarea.', related_name='tasks', to='crm.person', verbose_name='Contactos Asociados'),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='crm.client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='project',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='projects_attached', to='documents.document', verbose_name='Archivos Adjuntos'),
        ),
        migrations.AddField(
            model_name='person',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.project', verbose_name='Proyecto Asociado'),
        ),
        migrations.AddField(
            model_name='crmtask',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.project'),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='crm.costcategory', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='cost_subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='crm.costsubtype', verbose_name='Subtipo'),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='cost_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='crm.costtype', verbose_name='Tipo (Ingreso/Egreso)'),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='project_costs', to='documents.document', verbose_name='Documentos de Respaldo'),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='crm.project'),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='crm.costsubcategory', verbose_name='Subcategoría'),
        ),
        migrations.AddField(
            model_name='surveyfielddefinition',
            name='field_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_definitions', to='crm.surveyfieldtype', verbose_name='Tipo de Dato'),
        ),
        migrations.AddField(
            model_name='crmtask',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.taskcategory', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='taskresponse',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='task_responses', to='documents.document', verbose_name='Archivos Adjuntos'),
        ),
        migrations.AddField(
            model_name='taskresponse',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_responses', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por'),
        ),
        migrations.AddField(
            model_name='taskresponse',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='crm.crmtask', verbose_name='Tarea'),
        ),
        migrations.AddField(
            model_name='tasksubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='crm.taskcategory', verbose_name='Categoría Principal'),
        ),
        migrations.AddField(
            model_name='crmtask',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.tasksubcategory', verbose_name='Subcategoría'),
        ),
        migrations.AddField(
            model_name='crmtask',
            name='task_subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.tasksubtype', verbose_name='Subtipo'),
        ),
        migrations.AddField(
            model_name='tasksubtype',
            name='task_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtypes', to='crm.tasktype', verbose_name='Tipo Principal'),
        ),
        migrations.AddField(
            model_name='crmtask',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.tasktype', verbose_name='Tipo de Tarea'),
        ),
        migrations.AddField(
            model_name='technicalsurvey',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='technical_surveys', to='documents.document', verbose_name='Archivos Adjuntos'),
        ),
        migrations.AddField(
            model_name='technicalsurvey',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_surveys', to='crm.project', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='technicalsurvey',
            name='surveyed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys_conducted', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por'),
        ),
    ]
