# Generated by Django 5.2.10 on 2026-01-19 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('telemetry', '0003_remove_constantapplication_telemetry_c_constan_aa37c9_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Contacto / Persona', 'verbose_name_plural': 'Contactos / Personas'},
        ),
        migrations.AddField(
            model_name='client',
            name='business_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Giro/Rubro'),
        ),
        migrations.AddField(
            model_name='client',
            name='legal_representative',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Representante Legal'),
        ),
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='client_logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('PROSPECT', 'Prospecto'), ('SUSPENDED', 'Suspendido')], default='PROSPECT', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='client',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio Web'),
        ),
        migrations.AddField(
            model_name='person',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.client'),
        ),
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='person',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='telemetry.profiledataconfigcatchment'),
        ),
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Presupuesto Estimado'),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del Proyecto'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Prevista Inicio'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PLANNING', 'Planificación'), ('PROPOSAL', 'Propuesta/Cotización'), ('APPROVED', 'Aprobado (Preparando Instalación)'), ('IN_PROGRESS', 'En Instalación'), ('ACTIVE', 'Activo/Operativo'), ('MAINTENANCE', 'En Mantenimiento'), ('CLOSED', 'Cerrado')], default='PLANNING', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=300, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=300, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Nombre/Razón Social'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=300, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='client',
            name='rut',
            field=models.CharField(max_length=300, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=300, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='crm.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='project',
            name='code_internal',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Código Interno'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Nombre del Proyecto'),
        ),
        migrations.CreateModel(
            name='CrmTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('title', models.CharField(max_length=300, verbose_name='Título de la Tarea')),
                ('description', models.TextField(verbose_name='Descripción Detallada')),
                ('task_type', models.CharField(choices=[('COMMERCIAL', 'Gestión Comercial'), ('TECHNICAL_VISIT', 'Visita Técnica Terreno'), ('INSTALLATION', 'Instalación'), ('MAINTENANCE', 'Mantenimiento'), ('ADMINISTRATIVE', 'Administrativo')], default='COMMERCIAL', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Proceso'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=15)),
                ('due_date', models.DateTimeField(verbose_name='Fecha Límite')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.project')),
            ],
            options={
                'verbose_name': 'Tarea CRM',
                'verbose_name_plural': 'Tareas CRM',
                'ordering': ['-priority', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('category', models.CharField(choices=[('HARDWARE', 'Equipos/Hardware'), ('MATERIALS', 'Materiales Consumo'), ('LABOR', 'Mano de Obra'), ('TRAVEL', 'Viáticos y Traslado'), ('SOFTWARE', 'Licencias/Software'), ('OTHER', 'Otros')], max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_estimated', models.BooleanField(default=True, verbose_name='Es Estimado')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='crm.project')),
            ],
            options={
                'verbose_name': 'Costo de Proyecto',
                'verbose_name_plural': 'Costos de Proyecto',
            },
        ),
        migrations.CreateModel(
            name='TechnicalSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('pipe_diameter_inches', models.FloatField(default=0, verbose_name='Diámetro Tubería (Pulgadas)')),
                ('expected_max_flow', models.FloatField(default=0, verbose_name='Caudal Máximo Esperado (L/s)')),
                ('sensor_type_suggested', models.CharField(blank=True, max_length=200, verbose_name='Tipo Sensor Sugerido')),
                ('power_source', models.CharField(choices=[('SOLAR', 'Panel Solar'), ('GRID', 'Red Eléctrica 220V'), ('BATTERY', 'Solo Batería (Recargable)'), ('OTHER', 'Otro')], default='SOLAR', max_length=20)),
                ('electrical_distance_meters', models.FloatField(default=0, verbose_name='Distancia a Fuente Eléctrica (m)')),
                ('signal_strength_dbm', models.IntegerField(default=0, verbose_name='Fuerza de Señal en Terreno (dBm)')),
                ('access_complexity', models.TextField(blank=True, verbose_name='Complejidad de Acceso')),
                ('gps_coordinates', models.CharField(blank=True, max_length=100, verbose_name='Coordenadas GPS Sugeridas')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recomendaciones Técnicas')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_survey', to='crm.project')),
            ],
            options={
                'verbose_name': 'Levantamiento Técnico',
                'verbose_name_plural': 'Levantamientos Técnicos',
            },
        ),
    ]
