# Generated by Django 5.2.10 on 2026-01-19 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_person_options_client_business_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Cargo')),
                ('department', models.CharField(blank=True, help_text='Ej: Comercial, Técnico, Operaciones', max_length=200, null=True, verbose_name='Departamento/Área')),
            ],
            options={
                'verbose_name': 'Cargo / Puesto',
                'verbose_name_plural': 'Cargos / Puestos',
            },
        ),
        migrations.RemoveField(
            model_name='person',
            name='position',
        ),
        migrations.AddField(
            model_name='person',
            name='legacy_position',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cargo Anterior (Texto)'),
        ),
        migrations.AddField(
            model_name='project',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='projects', to='crm.person', verbose_name='Contactos Asociados'),
        ),
        migrations.AddField(
            model_name='person',
            name='job_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='crm.jobposition', verbose_name='Cargo'),
        ),
    ]
