# Generated by Django 5.2.10 on 2026-01-19 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_jobposition_remove_person_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='client',
        ),
        migrations.RemoveField(
            model_name='person',
            name='legacy_position',
        ),
        migrations.RemoveField(
            model_name='person',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contacts',
        ),
        migrations.AddField(
            model_name='person',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.project', verbose_name='Proyecto Asociado'),
        ),
    ]
