# Generated by Django 5.2.10 on 2026-01-19 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_remove_person_client_remove_person_legacy_position_and_more'),
        ('documents', '0002_alter_document_options_document_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Categoría')),
            ],
            options={
                'verbose_name': 'Categoría de Costo',
                'verbose_name_plural': 'Categorías de Costos',
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Tipo Tarea')),
                ('color_code', models.CharField(default='#FFFFFF', max_length=20, verbose_name='Color Hex')),
            ],
            options={
                'verbose_name': 'Tipo de Tarea',
                'verbose_name_plural': 'Tipos de Tareas',
            },
        ),
        migrations.RemoveField(
            model_name='crmtask',
            name='task_type',
        ),
        migrations.RemoveField(
            model_name='projectcost',
            name='category',
        ),
        migrations.AddField(
            model_name='crmtask',
            name='legacy_task_type',
            field=models.CharField(choices=[('COMMERCIAL', 'Gestión Comercial'), ('TECHNICAL_VISIT', 'Visita Técnica Terreno'), ('INSTALLATION', 'Instalación'), ('MAINTENANCE', 'Mantenimiento'), ('ADMINISTRATIVE', 'Administrativo')], default='COMMERCIAL', max_length=20, verbose_name='Tipo (Legacy)'),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='project_costs', to='documents.document', verbose_name='Documentos de Respaldo'),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='legacy_category',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Categoría (Legacy)'),
        ),
        migrations.AddField(
            model_name='technicalsurvey',
            name='dga_water_rights_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Código Expediente DGA'),
        ),
        migrations.AddField(
            model_name='technicalsurvey',
            name='proposed_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Propuesta Inicio'),
        ),
        migrations.AddField(
            model_name='technicalsurvey',
            name='requires_dga',
            field=models.BooleanField(default=False, verbose_name='¿Requiere Reporte DGA?'),
        ),
        migrations.AddField(
            model_name='technicalsurvey',
            name='requires_telemetry',
            field=models.BooleanField(default=True, verbose_name='¿Requiere Telemetría?'),
        ),
        migrations.CreateModel(
            name='CostSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Subcategoría')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='crm.costcategory', verbose_name='Categoría Principal')),
            ],
            options={
                'verbose_name': 'Subcategoría de Costo',
                'verbose_name_plural': 'Subcategorías de Costos',
            },
        ),
        migrations.AddField(
            model_name='projectcost',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='crm.costsubcategory', verbose_name='Subcategoría'),
        ),
        migrations.AddField(
            model_name='crmtask',
            name='task_type_dynamic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.tasktype', verbose_name='Tipo de Tarea'),
        ),
    ]
