# Generated by Django 5.2.10 on 2026-01-19 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_costcategory_tasktype_remove_crmtask_task_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmtask',
            name='legacy_task_type',
        ),
        migrations.RemoveField(
            model_name='projectcost',
            name='legacy_category',
        ),
        migrations.AddField(
            model_name='projectcost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='crm.costcategory', verbose_name='Categoría'),
        ),
    ]
