# Generated by Django 5.2.10 on 2026-01-19 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_remove_crmtask_legacy_task_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Categoría')),
                ('color_code', models.CharField(default='#333333', max_length=20, verbose_name='Color Hex')),
            ],
            options={
                'verbose_name': 'Categoría de Tarea',
                'verbose_name_plural': 'Categorías de Tareas',
            },
        ),
        migrations.RemoveField(
            model_name='crmtask',
            name='task_type_dynamic',
        ),
        migrations.AddField(
            model_name='crmtask',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.taskcategory', verbose_name='Categoría'),
        ),
        migrations.CreateModel(
            name='TaskSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Subcategoría')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='crm.taskcategory', verbose_name='Categoría Principal')),
            ],
            options={
                'verbose_name': 'Subcategoría de Tarea',
                'verbose_name_plural': 'Subcategorías de Tareas',
            },
        ),
        migrations.AddField(
            model_name='crmtask',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.tasksubcategory', verbose_name='Subcategoría'),
        ),
        migrations.DeleteModel(
            name='TaskType',
        ),
    ]
