# Generated by Django 5.2.10 on 2026-01-21 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_taskcategory_remove_crmtask_task_type_dynamic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalsurvey',
            name='name',
            field=models.CharField(blank=True, help_text='Ej: Pozo Norte, Sector A, etc.', max_length=200, verbose_name='Nombre del Levantamiento'),
        ),
        migrations.AlterField(
            model_name='technicalsurvey',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_surveys', to='crm.project', verbose_name='Proyecto'),
        ),
    ]
