# Generated by Django 5.2.10 on 2026-01-21 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_technicalsurvey_name_alter_technicalsurvey_project'),
        ('documents', '0003_document_created_by_document_crm_task_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Subtipo')),
            ],
            options={
                'verbose_name': 'Subtipo de Costo',
                'verbose_name_plural': 'Subtipos de Costos',
            },
        ),
        migrations.CreateModel(
            name='CostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Tipo')),
                ('flow', models.CharField(choices=[('INCOME', 'Ingreso'), ('EXPENSE', 'Egreso')], default='EXPENSE', max_length=20, verbose_name='Flujo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('color_code', models.CharField(default='#333333', max_length=20, verbose_name='Color Hex')),
            ],
            options={
                'verbose_name': 'Tipo de Costo (Ingreso/Egreso)',
                'verbose_name_plural': 'Tipos de Costos',
            },
        ),
        migrations.CreateModel(
            name='SurveyFieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Tipo')),
                ('data_type', models.CharField(choices=[('TEXT', 'Texto'), ('INTEGER', 'Número Entero'), ('DECIMAL', 'Número Decimal'), ('BOOLEAN', 'Sí/No'), ('DATE', 'Fecha'), ('DATETIME', 'Fecha y Hora'), ('SELECT', 'Lista de Opciones'), ('FILE', 'Archivo')], default='TEXT', max_length=20, verbose_name='Tipo de Dato')),
                ('options', models.JSONField(blank=True, default=list, help_text="Para tipo SELECT: ['Opción 1', 'Opción 2', ...]", verbose_name='Opciones')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='Valor Mínimo')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='Valor Máximo')),
                ('regex_pattern', models.CharField(blank=True, help_text='Expresión regular para validar texto', max_length=500, verbose_name='Patrón Regex')),
            ],
            options={
                'verbose_name': 'Tipo de Campo de Levantamiento',
                'verbose_name_plural': 'Tipos de Campos de Levantamiento',
            },
        ),
        migrations.CreateModel(
            name='TaskSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Subtipo')),
            ],
            options={
                'verbose_name': 'Subtipo de Tarea',
                'verbose_name_plural': 'Subtipos de Tareas',
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Tipo')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icono (FontAwesome)')),
                ('color_code', models.CharField(default='#007bff', max_length=20, verbose_name='Color Hex')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('requires_response', models.BooleanField(default=False, help_text='Si está marcado, la tarea debe tener una respuesta para completarse.', verbose_name='Requiere Respuesta')),
            ],
            options={
                'verbose_name': 'Tipo de Tarea',
                'verbose_name_plural': 'Tipos de Tareas',
            },
        ),
        migrations.AlterModelOptions(
            name='jobposition',
            options={'ordering': ['client', 'name'], 'verbose_name': 'Cargo / Puesto', 'verbose_name_plural': 'Cargos / Puestos'},
        ),
        migrations.AlterModelOptions(
            name='projectcost',
            options={'ordering': ['-date', '-created'], 'verbose_name': 'Costo de Proyecto', 'verbose_name_plural': 'Costos de Proyecto'},
        ),
        migrations.AlterModelOptions(
            name='technicalsurvey',
            options={'ordering': ['-survey_date', '-created'], 'verbose_name': 'Levantamiento Técnico', 'verbose_name_plural': 'Levantamientos Técnicos'},
        ),
        migrations.RemoveField(
            model_name='technicalsurvey',
            name='access_complexity',
        ),
        migrations.RemoveField(
            model_name='technicalsurvey',
            name='dga_water_rights_code',
        ),
        migrations.RemoveField(
            model_name='technicalsurvey',
            name='electrical_distance_meters',
        ),
        migrations.RemoveField(
            model_name='technicalsurvey',
            name='expected_max_flow',
        ),
        migrations.RemoveField(
            model_name='technicalsurvey',
            name='pipe_diameter_inches',
        ),
        migrations.RemoveField(
            model_name='technicalsurvey',
            name='power_source',
        ),
        migrations.RemoveField(
            model_name='technicalsurvey',
            name='proposed_start_date',
        ),
        migrations.RemoveField(
            model_name='technicalsurvey',
            name='sensor_type_suggested',
        ),
        migrations.RemoveField(
            model_name='technicalsurvey',
            name='signal_strength_dbm',
        ),
        migrations.AddField(
            model_name='costcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='crmtask',
            name='contacts',
            field=models.ManyToManyField(blank=True, help_text='Personas del cliente involucradas en esta tarea.', related_name='tasks', to='crm.person', verbose_name='Contactos Asociados'),
        ),
        migrations.AddField(
            model_name='crmtask',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='crm_tasks', to='documents.document', verbose_name='Archivos Adjuntos'),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Cliente al que pertenece este cargo. Dejar vacío para cargos globales.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_positions', to='crm.client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='project',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='projects_attached', to='documents.document', verbose_name='Archivos Adjuntos'),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Movimiento'),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='technicalsurvey',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='technical_surveys', to='documents.document', verbose_name='Archivos Adjuntos'),
        ),
        migrations.AddField(
            model_name='technicalsurvey',
            name='dynamic_data',
            field=models.JSONField(blank=True, default=dict, help_text="Formato: {'field_code': value, ...}", verbose_name='Datos del Levantamiento'),
        ),
        migrations.AddField(
            model_name='technicalsurvey',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas Adicionales'),
        ),
        migrations.AddField(
            model_name='technicalsurvey',
            name='survey_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Levantamiento'),
        ),
        migrations.AddField(
            model_name='technicalsurvey',
            name='surveyed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys_conducted', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=300, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=300, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='crmtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a'),
        ),
        migrations.AlterField(
            model_name='crmtask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completada en'),
        ),
        migrations.AlterField(
            model_name='crmtask',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción Detallada'),
        ),
        migrations.AlterField(
            model_name='crmtask',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Límite'),
        ),
        migrations.AlterField(
            model_name='crmtask',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=10, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='crmtask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Proceso'), ('AWAITING_RESPONSE', 'Esperando Respuesta'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='projectcost',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='projectcost',
            name='description',
            field=models.CharField(max_length=300, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='technicalsurvey',
            name='gps_coordinates',
            field=models.CharField(blank=True, max_length=100, verbose_name='Coordenadas GPS'),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='cost_subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='crm.costsubtype', verbose_name='Subtipo'),
        ),
        migrations.AddField(
            model_name='costsubtype',
            name='cost_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtypes', to='crm.costtype', verbose_name='Tipo Principal'),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='cost_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='crm.costtype', verbose_name='Tipo (Ingreso/Egreso)'),
        ),
        migrations.CreateModel(
            name='SurveyFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Campo')),
                ('code', models.CharField(help_text='Identificador único (ej: pipe_diameter, signal_strength)', max_length=100, unique=True, verbose_name='Código')),
                ('group', models.CharField(blank=True, help_text='Agrupa campos relacionados (ej: Hidráulica, Eléctrica, Logística)', max_length=100, verbose_name='Grupo')),
                ('is_required', models.BooleanField(default=False, verbose_name='Es Obligatorio')),
                ('default_value', models.CharField(blank=True, max_length=500, verbose_name='Valor por Defecto')),
                ('help_text', models.TextField(blank=True, verbose_name='Texto de Ayuda')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de Presentación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_definitions', to='crm.surveyfieldtype', verbose_name='Tipo de Dato')),
            ],
            options={
                'verbose_name': 'Definición de Campo de Levantamiento',
                'verbose_name_plural': 'Definiciones de Campos de Levantamiento',
                'ordering': ['group', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaskResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('content', models.TextField(verbose_name='Contenido de la Respuesta')),
                ('response_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Respuesta')),
                ('documents', models.ManyToManyField(blank=True, related_name='task_responses', to='documents.document', verbose_name='Archivos Adjuntos')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_responses', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='crm.crmtask', verbose_name='Tarea')),
            ],
            options={
                'verbose_name': 'Respuesta de Tarea',
                'verbose_name_plural': 'Respuestas de Tareas',
                'ordering': ['-response_date'],
            },
        ),
        migrations.AddField(
            model_name='crmtask',
            name='task_subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.tasksubtype', verbose_name='Subtipo'),
        ),
        migrations.AddField(
            model_name='tasksubtype',
            name='task_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtypes', to='crm.tasktype', verbose_name='Tipo Principal'),
        ),
        migrations.AddField(
            model_name='crmtask',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.tasktype', verbose_name='Tipo de Tarea'),
        ),
    ]
