# Generated by Django 5.2.10 on 2026-01-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_costsubtype_costtype_surveyfieldtype_tasksubtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='technicalsurvey',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desmarcar para desactivar este levantamiento sin eliminarlo.', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='technicalsurvey',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completado'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='DRAFT', max_length=20, verbose_name='Estado'),
        ),
    ]
