server {
    listen 80;
    #server_name servername;
    charset     utf-8;

    location /media  {
        alias /app/media;  # your Django project's media files - amend as required
    }

    location /static {
        alias /app/staticfiles/; # your Django project's static files - amend as required
    }

    location / {
    	include uwsgi_params;
        uwsgi_pass unix:/app/app.sock;
	uwsgi_read_timeout 120; 
    }
    http {
    	proxy_connect_timeout   10;
    	proxy_send_timeout      15;
    	proxy_read_timeout      20;
    }

}

http {
    ...
    proxy_connect_timeout   10;
    proxy_send_timeout      15;
    proxy_read_timeout      20;
}


