# Generated by Django 5.2.10 on 2026-01-24 15:46

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Vista')),
                ('key', models.SlugField(help_text='Identificador único dentro del módulo', max_length=100, verbose_name='Clave Única (en módulo)')),
                ('view_type', models.CharField(choices=[('TABLE', 'Tabla de Datos'), ('FORM', 'Formulario'), ('KANBAN', 'Tablero Kanban'), ('DASHBOARD', 'Dashboard / KPIs'), ('DETAIL', 'Detalle de Registro')], default='TABLE', max_length=20, verbose_name='Tipo de Vista')),
                ('data_source', models.CharField(blank=True, help_text='Endpoint API o QueryName para obtener datos', max_length=200, verbose_name='Fuente de Datos')),
                ('layout_config', models.JSONField(blank=True, default=dict, help_text='Definición de columnas, filtros, campos, etc.', verbose_name='Configuración Layout')),
                ('is_home', models.BooleanField(default=False, help_text='Si es la vista por defecto al entrar al módulo', verbose_name='Es Home')),
                ('order', models.IntegerField(default=0, verbose_name='Orden tab/menú')),
            ],
            options={
                'verbose_name': 'Vista de Módulo',
                'verbose_name_plural': 'Vistas de Módulo',
                'ordering': ['module', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug (URL)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(default='extension', help_text='Nombre del icono (Material Design / FontAwesome)', max_length=50, verbose_name='Icono')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de Menú')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('required_permissions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Lista de codenames de permisos requeridos (OR logic)', size=None, verbose_name='Permisos Requeridos')),
            ],
            options={
                'verbose_name': 'Módulo del Sistema',
                'verbose_name_plural': 'Módulos del Sistema',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DynamicAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre Acción')),
                ('key', models.SlugField(verbose_name='Clave Acción')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icono')),
                ('action_type', models.CharField(choices=[('API_CALL', 'Llamada API'), ('NAVIGATE', 'Navegar a URL'), ('OPEN_MODAL', 'Abrir Modal'), ('TRIGGER_JOB', 'Ejecutar Tarea Background')], default='API_CALL', max_length=20, verbose_name='Tipo de Acción')),
                ('target', models.CharField(blank=True, help_text='URL destino, Endpoint API o ID de Job', max_length=500, verbose_name='Objetivo')),
                ('payload_schema', models.JSONField(blank=True, default=dict, help_text='Schema de datos requeridos (ej: confirmation message)', verbose_name='Schema Payload')),
                ('requires_confirmation', models.BooleanField(default=False, verbose_name='Requiere Confirmación')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='dynamic_registry.moduleview', verbose_name='Vista Asociada')),
            ],
            options={
                'verbose_name': 'Acción Dinámica',
                'verbose_name_plural': 'Acciones Dinámicas',
                'ordering': ['view', 'name'],
            },
        ),
        migrations.AddField(
            model_name='moduleview',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='dynamic_registry.systemmodule', verbose_name='Módulo'),
        ),
        migrations.AlterUniqueTogether(
            name='moduleview',
            unique_together={('module', 'key')},
        ),
    ]
