# Generated by Django 5.2.10 on 2026-01-24 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_registry', '0002_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('widget_type', models.CharField(choices=[('KPI_CARD', 'Tarjeta KPI (Número Único)'), ('LINE_CHART', 'Gráfico de Línea'), ('BAR_CHART', 'Gráfico de Barras'), ('PIE_CHART', 'Gráfico de Torta'), ('GAUGE', 'Medidor / Gauge'), ('LIST_PREVIEW', 'Lista Resumida')], default='KPI_CARD', max_length=20)),
                ('title', models.CharField(max_length=100, verbose_name='Título Widget')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Subtítulo/Descripción')),
                ('data_source', models.CharField(max_length=500, verbose_name='Endpoint Fuente de Datos')),
                ('refresh_interval', models.IntegerField(default=60, help_text='Segundos para auto-refresco (0 = desactivado)', verbose_name='Intervalo Refresco (s)')),
                ('grid_config', models.JSONField(blank=True, default=dict, help_text='Posición en grilla: {x: 0, y: 0, w: 4, h: 2}', verbose_name='Configuración Grilla')),
                ('visual_config', models.JSONField(blank=True, default=dict, help_text='Colores, iconos, umbrales de alerta', verbose_name='Configuración Visual')),
                ('order', models.IntegerField(default=0, verbose_name='Orden Sequencial')),
                ('dashboard', models.ForeignKey(limit_choices_to={'view_type': 'DASHBOARD'}, on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='dynamic_registry.moduleview', verbose_name='Dashboard Padre')),
            ],
            options={
                'verbose_name': 'Widget de Dashboard',
                'verbose_name_plural': 'Widgets de Dashboard',
                'ordering': ['dashboard', 'order'],
            },
        ),
    ]
