# Generated by Django 5.2.10 on 2026-01-22 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0001_initial'),
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='catchment_point',
            field=models.ForeignKey(help_text='Punto de captación al que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='telemetry.catchmentpoint'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_model',
            field=models.ForeignKey(help_text='Modelo del equipo', on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='infrastructure.devicemodel'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='manufacturer',
            field=models.ForeignKey(help_text='Proveedor del equipo', on_delete=django.db.models.deletion.CASCADE, related_name='models', to='infrastructure.manufacturer'),
        ),
        migrations.AlterUniqueTogether(
            name='devicemodel',
            unique_together={('manufacturer', 'model_code')},
        ),
    ]
