# Generated by Django 5.2.10 on 2026-01-19 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='connection',
            table=None,
        ),
        migrations.AlterModelTable(
            name='devicemodel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='manufacturer',
            table=None,
        ),
    ]
