# Generated by Django 4.2.23 on 2026-01-22 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manufacturer",
            name="mqtt_broker_host",
        ),
        migrations.RemoveField(
            model_name="manufacturer",
            name="mqtt_broker_port",
        ),
        migrations.RemoveField(
            model_name="manufacturer",
            name="mqtt_password",
        ),
        migrations.RemoveField(
            model_name="manufacturer",
            name="mqtt_use_tls",
        ),
        migrations.RemoveField(
            model_name="manufacturer",
            name="mqtt_username",
        ),
    ]
