# Generated by Django 4.2.23 on 2026-01-22 17:29

import uuid
from django.db import migrations, models


def generate_unique_tokens(apps, schema_editor):
    """Genera tokens únicos para dispositivos existentes."""
    Device = apps.get_model('infrastructure', 'Device')
    for device in Device.objects.all():
        device.token = uuid.uuid4().hex
        device.save(update_fields=['token'])


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0003_remove_mqtt_fields_from_manufacturer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="battery_level",
        ),
        migrations.RemoveField(
            model_name="devicemodel",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="manufacturer",
            name="is_active",
        ),
        migrations.AddField(
            model_name="device",
            name="imei",
            field=models.CharField(
                blank=True, help_text="IMEI del dispositivo (opcional)", max_length=20
            ),
        ),
        # Paso 1: Agregar token SIN unique
        migrations.AddField(
            model_name="device",
            name="token",
            field=models.CharField(
                default='',
                help_text="Token único para autenticación con el proveedor",
                max_length=255,
            ),
        ),
        # Paso 2: Generar tokens únicos para existentes
        migrations.RunPython(generate_unique_tokens, migrations.RunPython.noop),
        # Paso 3: Hacer el campo unique
        migrations.AlterField(
            model_name="device",
            name="token",
            field=models.CharField(
                help_text="Token único para autenticación con el proveedor",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="status",
            field=models.CharField(
                choices=[
                    ("OFFLINE", "Offline"),
                    ("ONLINE", "Online"),
                    ("ERROR", "Error"),
                    ("MAINTENANCE", "Mantenimiento"),
                ],
                default="OFFLINE",
                help_text="Estado actual del dispositivo",
                max_length=20,
            ),
        ),
    ]
