# Generated by Django 4.2.23 on 2026-01-22 17:32

import api.infrastructure.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0004_simplify_models_add_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="device_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="ID único del dispositivo (generado automáticamente)",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="token",
            field=models.CharField(
                default=api.infrastructure.models.generate_device_token,
                help_text="Token único para autenticación con el proveedor",
                max_length=255,
                unique=True,
            ),
        ),
    ]
