# Generated by Django 4.2.23 on 2026-01-22 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0005_change_device_id_to_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="catchment_point",
        ),
    ]
