# Generated by Django 4.2.23 on 2026-01-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0006_remove_catchment_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="use_internal_mqtt",
            field=models.BooleanField(
                default=True,
                help_text="Si es True, usa MQTT interno y genera token automático. Si es False, usa proveedor externo.",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="token",
            field=models.CharField(
                blank=True,
                help_text="Token para autenticación. Auto-generado si usa MQTT interno, manual si es proveedor externo.",
                max_length=255,
                unique=True,
            ),
        ),
    ]
