# Generated by Django 5.2.10 on 2026-01-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0008_device_configuration_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceconfigurationvalue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
