# Generated by Django 5.2.10 on 2026-01-22 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre')),
                ('internal', models.BooleanField(default=False, verbose_name='Interno')),
            ],
            options={
                'verbose_name': 'Tipo de archivo',
                'verbose_name_plural': 'Tipos de archivos',
                'db_table': 'core_typefilecatchment',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre')),
                ('file', models.FileField(upload_to='system_documents/', verbose_name='Archivo')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('valid_until', models.DateField(blank=True, help_text='Opcional. Para documentos con vigencia limitada.', null=True, verbose_name='Fecha de Vencimiento')),
                ('internal_only', models.BooleanField(default=False, help_text='Si está marcado, solo será visible para personal administrativo.', verbose_name='Solo Interno')),
                ('tags', models.CharField(blank=True, help_text='Separadas por comas. Ejemplo: factura, certificado, dga', max_length=500, verbose_name='Etiquetas')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
                ('crm_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sourced_documents', to='crm.crmtask', verbose_name='Tarea CRM')),
            ],
            options={
                'verbose_name': 'Archivo/Documento',
                'verbose_name_plural': 'Archivos/Documentos',
                'db_table': 'core_filecatchment',
            },
        ),
    ]
