# Generated by Django 5.2.10 on 2026-01-19 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_person_options_client_business_type_and_more'),
        ('documents', '0001_initial'),
        ('telemetry', '0003_remove_constantapplication_telemetry_c_constan_aa37c9_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Archivo/Documento', 'verbose_name_plural': 'Archivos/Documentos'},
        ),
        migrations.AddField(
            model_name='document',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.project', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='system_documents/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='point_catchment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='telemetry.catchmentpoint', verbose_name='Punto de captacion'),
        ),
    ]
