# Generated by Django 5.2.10 on 2026-01-19 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_taskcategory_remove_crmtask_task_type_dynamic_and_more'),
        ('documents', '0002_alter_document_options_document_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Subido por'),
        ),
        migrations.AddField(
            model_name='document',
            name='crm_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.crmtask', verbose_name='Tarea CRM'),
        ),
        migrations.AddField(
            model_name='document',
            name='internal_only',
            field=models.BooleanField(default=False, help_text='Si está marcado, solo será visible para personal administrativo.', verbose_name='Solo Interno'),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.CharField(blank=True, help_text='Separadas por comas. Ejemplo: factura, certificado, dga', max_length=500, verbose_name='Etiquetas'),
        ),
        migrations.AddField(
            model_name='document',
            name='technical_survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.technicalsurvey', verbose_name='Levantamiento Técnico'),
        ),
        migrations.AddField(
            model_name='document',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Opcional. Para documentos con vigencia limitada.', null=True, verbose_name='Fecha de Vencimiento'),
        ),
    ]
