# Generated by Django 4.2.23 on 2026-01-22 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0006_remove_catchment_point"),
        ("documents", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="device",
            field=models.ForeignKey(
                blank=True,
                help_text="Documentos del dispositivo (calibraciones, informes)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="infrastructure.device",
                verbose_name="Dispositivo",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="device_model",
            field=models.ForeignKey(
                blank=True,
                help_text="Documentos del modelo (datasheets, manuales)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="infrastructure.devicemodel",
                verbose_name="Modelo de Equipo",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                help_text="Documentos del fabricante (catálogos, guías)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="infrastructure.manufacturer",
                verbose_name="Fabricante",
            ),
        ),
    ]
