# Generated by Django 5.2.10 on 2026-01-21 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_costsubtype_costtype_surveyfieldtype_tasksubtype_and_more'),
        ('documents', '0003_document_created_by_document_crm_task_and_more'),
        ('telemetry', '0006_catchmentpoint_technical_survey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='crm_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sourced_documents', to='crm.crmtask', verbose_name='Tarea CRM'),
        ),
        migrations.AlterField(
            model_name='document',
            name='point_catchment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sourced_documents', to='telemetry.catchmentpoint', verbose_name='Punto de captacion'),
        ),
        migrations.AlterField(
            model_name='document',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sourced_documents', to='crm.project', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='document',
            name='technical_survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sourced_documents', to='crm.technicalsurvey', verbose_name='Levantamiento Técnico'),
        ),
    ]
