# Generated by Django 4.2.23 on 2026-01-18 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Variable",
            new_name="CoreVariable",
        ),
        migrations.RenameIndex(
            model_name="telemetryrecord",
            new_name="core_teleme_point_i_1fa6ab_idx",
            old_name="core_teleme_point_i_2549bc_idx",
        ),
        migrations.AlterModelTable(
            name="corevariable",
            table="core_variable",
        ),
        migrations.AlterModelTable(
            name="telemetryrecord",
            table="core_telemetryrecord",
        ),
    ]
