# Generated by Django 4.2.23 on 2026-01-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_variable_corevariable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="corevariable",
            name="formula",
            field=models.CharField(
                blank=True,
                help_text="Ej: ({var1} + {var2}) * 0.5. Use los internal_codes entre llaves.",
                max_length=500,
                null=True,
                verbose_name="Fórmula",
            ),
        ),
        migrations.AddField(
            model_name="corevariable",
            name="is_virtual",
            field=models.BooleanField(
                default=False,
                help_text="Indica si la variable es calculada internamente.",
                verbose_name="Es Virtual",
            ),
        ),
        migrations.AddField(
            model_name="corevariable",
            name="operation",
            field=models.CharField(
                choices=[
                    ("PHYSICAL", "Dato Físico (Sensor)"),
                    ("SUM", "Suma"),
                    ("DIFF", "Resta (A - B)"),
                    ("MUL", "Multiplicación"),
                    ("AVG", "Promedio"),
                    ("FORMULA", "Fórmula Personalizada"),
                ],
                default="PHYSICAL",
                max_length=20,
                verbose_name="Tipo de Operación",
            ),
        ),
        migrations.AddField(
            model_name="corevariable",
            name="priority",
            field=models.IntegerField(
                default=0,
                help_text="Menor valor se calcula antes.",
                verbose_name="Prioridad de Cálculo",
            ),
        ),
        migrations.AddField(
            model_name="corevariable",
            name="sources",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de internal_codes de origen",
                verbose_name="Variables de Origen",
            ),
        ),
        migrations.AlterField(
            model_name="virtualvariable",
            name="formula",
            field=models.CharField(
                blank=True,
                help_text="Ej: ({var1} + {var2}) * 0.5. Use los códigos entre llaves.",
                max_length=500,
                null=True,
                verbose_name="Fórmula",
            ),
        ),
        migrations.AlterField(
            model_name="virtualvariable",
            name="priority",
            field=models.IntegerField(
                default=0,
                help_text="Menor valor se calcula antes.",
                verbose_name="Prioridad de Cálculo",
            ),
        ),
    ]
