# Generated by Django 4.2.23 on 2026-01-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_corevariable_formula_corevariable_is_virtual_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="corevariable",
            name="max_value",
            field=models.FloatField(
                blank=True,
                help_text="Si el dato es mayor a este valor, se ignorará.",
                null=True,
                verbose_name="Valor Máximo",
            ),
        ),
        migrations.AddField(
            model_name="corevariable",
            name="min_value",
            field=models.FloatField(
                blank=True,
                help_text="Si el dato es menor a este valor, se ignorará.",
                null=True,
                verbose_name="Valor Mínimo",
            ),
        ),
    ]
