# Generated by Django 4.2.23 on 2026-01-18 04:38

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_corevariable_max_value_corevariable_min_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="profiledataconfigcatchment",
            name="extra_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Variables dinámicas de perfil para usar en fórmulas (ej: {'altura_sensor': 50.5}).",
                verbose_name="Configuración Dinámica",
            ),
        ),
        migrations.AddIndex(
            model_name="telemetryrecord",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["data"], name="core_teleme_data_e45449_gin"
            ),
        ),
    ]
