# Generated by Django 4.2.23 on 2026-01-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_profiledataconfigcatchment_extra_config_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profiledataconfigcatchment",
            name="extra_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Variables dinámicas. Soporta formato simple {'k': 1.5} o extendido {'k': {'value': 1.5, 'unit': 'm', 'prefix': 'H='}}.",
                verbose_name="Configuración Dinámica",
            ),
        ),
    ]
