# Generated by Django 4.2.27 on 2025-12-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_interactiondetail_core_interactiondetail_send_dga_created_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catchmentpoint',
            name='frecuency',
            field=models.CharField(blank=True, choices=[('1', '1 minuto'), ('5', '5 minutos'), ('10', '10 minutos'), ('60', '60 minutos')], default='60', max_length=300, null=True, verbose_name='Frecuencia'),
        ),
    ]
