# Generated by Django 4.2.27 on 2026-01-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_catchmentpoint_frecuency'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledataconfigcatchment',
            name='addition',
            field=models.IntegerField(default=0, help_text='Valor acumulado automáticamente cuando el sensor se reinicia (glitch/reset).', verbose_name='Adicion (Reset)'),
        ),
    ]
