# Generated by Django 4.2.27 on 2026-01-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_profiledataconfigcatchment_addition'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interactiondetail',
            unique_together={('catchment_point', 'date_time_medition')},
        ),
    ]
