# Generated by Django 4.2.27 on 2026-01-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_interactiondetail_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='addition',
        ),
    ]
