# Generated by Django 4.2.27 on 2026-01-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_variable_addition'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactiondetail',
            name='is_partial',
            field=models.BooleanField(default=False, help_text='True si hay variables fallando pero otras funcionando', verbose_name='Desconexión parcial'),
        ),
    ]
