# Generated by Django 4.2.27 on 2026-01-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_is_partial_to_interactiondetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactiondetail',
            name='variable_details',
            field=models.JSONField(blank=True, help_text='JSON con el estado individual de cada variable', null=True, verbose_name='Detalle de variables'),
        ),
    ]
