# Generated by Django 4.2.27 on 2026-01-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_interactiondetail_variable_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgadataconfigcatchment',
            name='password_dga_software',
            field=models.CharField(blank=True, default='', help_text='Contraseña software DGA. Dejar vacío para usar default del sistema.', max_length=1400, verbose_name='clave DGA'),
        ),
        migrations.AlterField(
            model_name='user',
            name='txt_password',
            field=models.CharField(blank=True, default='', help_text='DEPRECATED: No usar. Mantener vacío. Las contraseñas se hashean automáticamente.', max_length=1200, null=True),
        ),
    ]
