# Generated by Django 4.2.28 on 2026-04-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_security_move_credentials_to_env'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationscatchment',
            name='status_dga',
            field=models.BooleanField(default=False, verbose_name='Estado DGA'),
        ),
        migrations.AddField(
            model_name='notificationscatchment',
            name='status_sma',
            field=models.BooleanField(default=False, verbose_name='Estado SMA'),
        ),
    ]
