# Generated by Django 4.2.23 on 2026-05-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_status_dga_status_sma_to_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationscatchment',
            name='emails',
            field=models.JSONField(blank=True, default=list, help_text='Lista de emails. Ej: ["correo1@x.com", "correo2@x.com"]', verbose_name='Emails destinatarios'),
        ),
    ]
