# Generated by Django 4.2.27 on 2026-04-30

import re
from django.db import migrations

EMAIL_REGEX = re.compile(r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$")


def migrate_emails_to_array(apps, schema_editor):
    """
    Migra emails del campo 'message' al campo 'emails' (array JSON).
    
    El campo 'message' fue usado históricamente para almacenar el email
    destinatario de alertas umbral. Esta migración copia esos emails al
    nuevo campo 'emails' como array, eliminando la dependencia del fallback.
    """
    NotificationsCatchment = apps.get_model('core', 'NotificationsCatchment')

    updated = 0
    skipped = 0

    for alerta in NotificationsCatchment.objects.all():
        # Si ya tiene emails en el array nuevo, saltar
        if alerta.emails and len(alerta.emails) > 0:
            skipped += 1
            continue

        emails_found = []

        # Extraer emails del campo message
        if alerta.message:
            # Probar split por coma (puede haber múltiples emails)
            parts = alerta.message.split(',')
            for part in parts:
                raw = part.strip()
                if raw and EMAIL_REGEX.match(raw):
                    emails_found.append(raw)

        if emails_found:
            alerta.emails = emails_found
            alerta.save(update_fields=['emails'])
            updated += 1
        else:
            skipped += 1

    print(f"\n[MIGRACION] Alertas umbral migradas: {updated} | Sin email en message: {skipped}")


def reverse_migrate_emails_to_array(apps, schema_editor):
    """
    Reversión: no hace nada destructivo.
    Los emails siguen estando en 'message' como fallback,
    así que no perdemos datos.
    """
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0027_add_emails_to_notifications'),
    ]

    operations = [
        migrations.RunPython(
            migrate_emails_to_array,
            reverse_code=reverse_migrate_emails_to_array,
        ),
    ]
