# Generated by Django 4.2.28 on 2026-05-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_migrate_alert_emails_to_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_client_admin',
            field=models.BooleanField(default=False, help_text='Administrador de clientes. Puede editar datos asociados a sus clientes asignados.'),
        ),
    ]
