# Generated by Django 4.2.23 on 2026-05-13 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_is_client_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationscatchment',
            name='point_catchment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.catchmentpoint', verbose_name='Punto de captacion'),
        ),
    ]
