# Generated by Django 4.2.28 on 2026-05-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_make_notification_point_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgadataconfigcatchment',
            name='flow_granted_dga',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Caudal otorgado(lt/s)'),
        ),
    ]
