# Generated by Django 4.2.28 on 2026-05-16 03:04
# Modified manually to use CREATE INDEX CONCURRENTLY on InteractionDetail
# because the table has ~2.5M rows / 2GB.

from django.db import migrations, models


def _create_index(apps, schema_editor, name, fields, concurrent=True):
    """Crea un índice de forma condicional según el backend."""
    vendor = schema_editor.connection.vendor
    concurrently = "CONCURRENTLY " if (concurrent and vendor == "postgresql") else ""
    sql = (
        f"CREATE INDEX {concurrently}IF NOT EXISTS {name} "
        f"ON core_interactiondetail ({fields});"
    )
    schema_editor.execute(sql)


def _drop_index(apps, schema_editor, name, concurrent=True):
    """Elimina un índice de forma condicional según el backend."""
    vendor = schema_editor.connection.vendor
    concurrently = "CONCURRENTLY " if (concurrent and vendor == "postgresql") else ""
    sql = f"DROP INDEX {concurrently}IF EXISTS {name};"
    schema_editor.execute(sql)


def create_idx1_fwd(apps, schema_editor):
    _create_index(apps, schema_editor, "core_intera_send_dg_aae41a_idx", "send_dga, catchment_point_id, date_time_medition")


def create_idx1_rev(apps, schema_editor):
    _drop_index(apps, schema_editor, "core_intera_send_dg_aae41a_idx")


def create_idx2_fwd(apps, schema_editor):
    _create_index(apps, schema_editor, "core_intera_is_erro_f956b9_idx", "is_error")


def create_idx2_rev(apps, schema_editor):
    _drop_index(apps, schema_editor, "core_intera_is_erro_f956b9_idx")


class Migration(migrations.Migration):

    atomic = False  # REQUIRED for CREATE INDEX CONCURRENTLY

    dependencies = [
        ("core", "0031_add_indexes_and_fix_fields"),
    ]

    operations = [
        # Small tables — safe to use normal AlterField
        migrations.AlterField(
            model_name="catchmentpoint",
            name="is_novus",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Novus"),
        ),
        migrations.AlterField(
            model_name="catchmentpoint",
            name="is_tdata",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Twin"),
        ),
        migrations.AlterField(
            model_name="catchmentpoint",
            name="is_thethings",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Nettra"),
        ),
        migrations.AlterField(
            model_name="interactiondetail",
            name="is_error",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Error"),
        ),
        migrations.AlterField(
            model_name="interactiondetail",
            name="send_dga",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Agregar a la cola DGA"
            ),
        ),
        migrations.AlterField(
            model_name="profiledataconfigcatchment",
            name="is_telemetry",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Activar telemetría"
            ),
        ),
        # Large table — use CONCURRENTLY to avoid write-locking (PostgreSQL only)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(create_idx1_fwd, create_idx1_rev),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name="interactiondetail",
                    index=models.Index(
                        fields=["send_dga", "catchment_point", "date_time_medition"],
                        name="core_intera_send_dg_aae41a_idx",
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(create_idx2_fwd, create_idx2_rev),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name="interactiondetail",
                    index=models.Index(
                        fields=["is_error"],
                        name="core_intera_is_erro_f956b9_idx",
                    ),
                ),
            ],
        ),
    ]
