# Generated by Django 4.2.28 on 2026-05-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_catchmentpoint_is_novus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='addition',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Valor acumulado automáticamente cuando el sensor se reinicia (glitch/reset).', max_digits=15, verbose_name='Adicion (Reset)'),
        ),
    ]
