# Generated by Django 4.2.23 on 2026-05-16 21:36

import api.core.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_profiledataconfigcatchment_addition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactiondetail',
            name='date_time_last_logger',
            field=api.core.models.fields.AwareDateTimeField(blank=True, max_length=800, null=True, verbose_name='Fecha/hora logger'),
        ),
        migrations.AlterField(
            model_name='interactiondetail',
            name='date_time_medition',
            field=api.core.models.fields.AwareDateTimeField(blank=True, max_length=800, null=True, verbose_name='Fecha/hora medición'),
        ),
    ]
