# Generated by Django 4.2.23 on 2026-05-16 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_interactiondetail_date_time_last_logger_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('provider_type', models.CharField(choices=[('TWIN', 'TWIN (TwinDimension / TDATA)'), ('NETTRA', 'NETTRA (TheThings.io)'), ('NOVUS', 'NOVUS (Tago.io)'), ('CUSTOM', 'Custom / Otro')], max_length=20, verbose_name='Tipo de proveedor')),
                ('base_url', models.URLField(blank=True, help_text='Ej: https://api.twindimension.com/tdata/v1', max_length=500, verbose_name='URL base')),
                ('auth_type', models.CharField(choices=[('NONE', 'Sin autenticación'), ('BASIC', 'Basic Auth (usuario + password)'), ('BEARER', 'Bearer Token'), ('API_KEY', 'API Key en Header'), ('HEADER', 'Header personalizado')], default='NONE', max_length=20, verbose_name='Tipo de autenticación')),
                ('auth_username', models.CharField(blank=True, help_text='Para Basic Auth', max_length=200, verbose_name='Usuario')),
                ('auth_password', models.CharField(blank=True, help_text='Para Basic Auth', max_length=200, verbose_name='Password')),
                ('auth_token', models.CharField(blank=True, help_text='Para Bearer, API Key o Header personalizado', max_length=500, verbose_name='Token / API Key')),
                ('auth_header_name', models.CharField(blank=True, help_text='Ej: Authorization, authorization, x-api-key', max_length=100, verbose_name='Nombre del Header')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Proveedor de Telemetría',
                'verbose_name_plural': 'Proveedores de Telemetría',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='variable',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Proveedor configurado desde el admin (reemplaza service/token hardcodeado)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variables', to='core.telemetryprovider', verbose_name='Proveedor CRUD'),
        ),
    ]
