# Generated by Django 4.2.23 on 2026-05-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_telemetryprovider_variable_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telemetryprovider',
            name='provider_type',
        ),
        migrations.AddField(
            model_name='telemetryprovider',
            name='endpoint_template',
            field=models.CharField(blank=True, help_text='Variables: {token}, {variable}. Ej: /things/{token}/resources/{variable}', max_length=500, verbose_name='Template de endpoint'),
        ),
        migrations.AddField(
            model_name='telemetryprovider',
            name='handler_name',
            field=models.CharField(choices=[('generic_json', 'JSON Genérico (parser_config)'), ('tdata', 'TDATA (TwinDimension - login + bearer)'), ('thethings', 'TheThings.io v2'), ('tago', 'Tago.io')], default='generic_json', help_text='tdata/thethings/tago = lógica específica hardcodeada. generic_json = configurable vía parser_config.', max_length=20, verbose_name='Handler de datos'),
        ),
        migrations.AddField(
            model_name='telemetryprovider',
            name='parser_config',
            field=models.JSONField(blank=True, default=dict, help_text='\n        Solo para handler "generic_json". Ej:\n        {\n            "value_field": "value",\n            "timestamp_field": "ts",\n            "timestamp_format": "epoch_ms",\n            "response_is_array": true,\n            "response_root_key": "result",\n            "response_array_index": 0\n        }\n        ', verbose_name='Configuración del parser'),
        ),
        migrations.AddField(
            model_name='telemetryprovider',
            name='protocol',
            field=models.CharField(choices=[('HTTP_REST', 'HTTP REST (GET/POST JSON)'), ('HTTP_GET', 'HTTP GET genérico'), ('MQTT', 'MQTT Broker'), ('WEBSOCKET', 'WebSocket'), ('CUSTOM', 'Custom / Script')], default='HTTP_REST', max_length=20, verbose_name='Protocolo'),
        ),
        migrations.AddField(
            model_name='telemetryprovider',
            name='retry_attempts',
            field=models.IntegerField(default=3, verbose_name='Reintentos'),
        ),
        migrations.AddField(
            model_name='telemetryprovider',
            name='timeout_seconds',
            field=models.IntegerField(default=5, verbose_name='Timeout (segundos)'),
        ),
        migrations.AlterField(
            model_name='telemetryprovider',
            name='auth_header_name',
            field=models.CharField(blank=True, default='Authorization', max_length=100, verbose_name='Nombre del Header'),
        ),
        migrations.AlterField(
            model_name='telemetryprovider',
            name='auth_password',
            field=models.CharField(blank=True, max_length=200, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='telemetryprovider',
            name='auth_type',
            field=models.CharField(choices=[('NONE', 'Sin autenticación'), ('BASIC', 'Basic Auth (usuario + password)'), ('BEARER', 'Bearer Token'), ('API_KEY_HEADER', 'API Key en Header'), ('QUERY_PARAM', 'API Key en Query Param')], default='NONE', max_length=20, verbose_name='Autenticación'),
        ),
        migrations.AlterField(
            model_name='telemetryprovider',
            name='auth_username',
            field=models.CharField(blank=True, max_length=200, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='telemetryprovider',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
    ]
