# Generated by Django 4.2.23 on 2026-05-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_telemetryprovider_provider_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledataconfigcatchment',
            name='nivel_offset',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Desfase a aplicar al nivel antes de calcular (ej: -17.0 para punto 149).', max_digits=10, verbose_name='Offset nivel (m)'),
        ),
        migrations.AddField(
            model_name='profiledataconfigcatchment',
            name='replicate_on_missing',
            field=models.BooleanField(default=False, help_text='Si no llegan datos del sensor, replica el último registro válido en vez de crear ceros.', verbose_name='Replicar último registro si no hay datos'),
        ),
        migrations.AddField(
            model_name='profiledataconfigcatchment',
            name='use_transaction_atomic',
            field=models.BooleanField(default=True, help_text='Envuelve el guardado en transaction.atomic() para prevenir duplicados.', verbose_name='Usar transacción atómica al guardar'),
        ),
        migrations.AddField(
            model_name='variable',
            name='store_average_flow',
            field=models.BooleanField(default=True, help_text='Si es True, CAUDAL_PROMEDIO guarda flow en InteractionDetail. Si es False, se calcula dinámicamente.', verbose_name='Guardar caudal promedio en BD'),
        ),
    ]
