# Generated by Django 4.2.23 on 2026-05-17 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_profiledataconfigcatchment_nivel_offset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre de la regla')),
                ('target_type', models.CharField(choices=[('THRESHOLD_MAX', 'Umbral máximo'), ('THRESHOLD_MIN', 'Umbral mínimo'), ('NO_DATA', 'Sin datos por X tiempo'), ('RATE_OF_CHANGE', 'Tasa de cambio'), ('DEVIATION', 'Desviación estadística'), ('SCHEDULED_REPORT', 'Reporte programado')], max_length=50, verbose_name='Tipo de alerta')),
                ('variable_type', models.CharField(blank=True, choices=[('NIVEL', 'nivel'), ('CAUDAL', 'caudal'), ('CAUDAL_PROMEDIO', 'caudal_promedio((diff/3600)*1000)'), ('TOTALIZADO', 'totalizado')], help_text='Requerido para THRESHOLD_MAX, THRESHOLD_MIN, RATE_OF_CHANGE, DEVIATION. Ignorado para NO_DATA y SCHEDULED_REPORT.', max_length=50, null=True, verbose_name='Variable a monitorear')),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Valor umbral')),
                ('no_data_minutes', models.IntegerField(blank=True, help_text='Para alertas de tipo NO_DATA: tiempo máximo sin recibir datos.', null=True, verbose_name='Minutos sin datos')),
                ('rate_change_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Valor de tasa de cambio')),
                ('rate_change_window', models.IntegerField(blank=True, help_text='Para RATE_OF_CHANGE: intervalo en minutos para comparar.', null=True, verbose_name='Ventana de tiempo (minutos)')),
                ('cooldown_minutes', models.IntegerField(default=60, help_text='Tiempo mínimo entre disparos consecutivos de la misma regla.', verbose_name='Cooldown (minutos)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activa')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha inicio vigencia')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha fin vigencia')),
                ('report_schedule', models.CharField(blank=True, choices=[('DAILY', 'Diario'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensual')], max_length=50, null=True, verbose_name='Periodicidad del reporte')),
                ('report_hour', models.IntegerField(blank=True, null=True, verbose_name='Hora de envío (0-23)')),
                ('point_catchment', models.ForeignKey(blank=True, help_text='Si se deja vacío, la regla aplica globalmente (ej. alerta de administrador).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='core.catchmentpoint', verbose_name='Punto de captación')),
            ],
            options={
                'verbose_name': 'Regla de alerta',
                'verbose_name_plural': 'Reglas de alerta',
            },
        ),
        migrations.CreateModel(
            name='AlertChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('channel_type', models.CharField(choices=[('EMAIL', 'Email'), ('GOOGLE_CHAT', 'Google Chat'), ('WEBHOOK', 'Webhook'), ('SMS', 'SMS')], max_length=50, verbose_name='Tipo de canal')),
                ('destination', models.CharField(help_text='Email, URL de webhook, o número de teléfono según el canal.', max_length=500, verbose_name='Destino')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('template_override', models.TextField(blank=True, help_text='Si se deja vacío, se usa la plantilla por defecto del canal.', null=True, verbose_name='Plantilla personalizada')),
                ('alert_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='core.alertrule', verbose_name='Regla de alerta')),
            ],
            options={
                'verbose_name': 'Canal de notificación',
                'verbose_name_plural': 'Canales de notificación',
            },
        ),
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('event_type', models.CharField(choices=[('COUNTER_RESET', 'Reinicio de contador'), ('DISCONNECTION', 'Desconexión'), ('RECONNECTION', 'Reconexión'), ('MEASUREMENT_ERROR', 'Error de medición'), ('MASSIVE_JUMP_BLOCKED', 'Salto masivo bloqueado'), ('TOKEN_REFRESH', 'Token refrescado'), ('API_ERROR', 'Error de API externa')], db_index=True, max_length=50, verbose_name='Tipo de evento')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('severity', models.CharField(choices=[('INFO', 'Informativo'), ('WARNING', 'Advertencia'), ('CRITICAL', 'Crítico')], db_index=True, default='INFO', max_length=20, verbose_name='Severidad')),
                ('extra_data', models.JSONField(blank=True, help_text='JSON con información adicional del evento.', null=True, verbose_name='Datos extra')),
                ('point_catchment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_events', to='core.catchmentpoint', verbose_name='Punto de captación')),
            ],
            options={
                'verbose_name': 'Evento del sistema',
                'verbose_name_plural': 'Eventos del sistema',
                'indexes': [models.Index(fields=['event_type', 'created'], name='core_system_event_t_cda29d_idx'), models.Index(fields=['point_catchment', 'created'], name='core_system_point_c_c599f5_idx'), models.Index(fields=['severity', 'created'], name='core_system_severit_5b4844_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('triggered_at', models.DateTimeField(verbose_name='Fecha/hora del disparo')),
                ('value_at_trigger', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Valor en el momento del disparo')),
                ('threshold_breached', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Umbral que se rompió')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='Notificación enviada')),
                ('notification_error', models.TextField(blank=True, null=True, verbose_name='Error de envío')),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha envío')),
                ('is_acknowledged', models.BooleanField(default=False, verbose_name='Reconocida (ack)')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha reconocimiento')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_triggers', to=settings.AUTH_USER_MODEL, verbose_name='Reconocida por')),
                ('alert_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='core.alertrule', verbose_name='Regla')),
                ('interaction_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.interactiondetail', verbose_name='Registro de telemetría relacionado')),
            ],
            options={
                'verbose_name': 'Disparo de alerta',
                'verbose_name_plural': 'Disparos de alerta',
                'indexes': [models.Index(fields=['alert_rule', 'triggered_at'], name='core_alertt_alert_r_2d04f2_idx'), models.Index(fields=['is_acknowledged', 'notification_sent'], name='core_alertt_is_ackn_3a039a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['point_catchment', 'is_active', 'target_type'], name='core_alertr_point_c_ef3d49_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['is_active', 'target_type'], name='core_alertr_is_acti_c5d146_idx'),
        ),
    ]
