# Generated by Django 4.2.23 on 2026-05-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_add_alert_subsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='check_frequency_minutes',
            field=models.IntegerField(default=10, help_text='Cada cuántos minutos se evalúa esta regla. Ej: 1 para críticas, 60 para reportes.', verbose_name='Revisar cada (minutos)'),
        ),
    ]
