# Generated by Django 4.2.23 on 2026-05-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_add_alert_check_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Informativo'), ('WARNING', 'Advertencia'), ('ALERT', 'Alerta'), ('CRITICAL', 'Crítico')], db_index=True, default='WARNING', help_text='Determina la prioridad visual y la frecuencia sugerida.', max_length=20, verbose_name='Severidad'),
        ),
    ]
