# Generated by Django 4.2.23 on 2026-05-17 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_add_alert_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='description',
            field=models.TextField(blank=True, help_text='Documenta el propósito de esta regla. Visible solo en admin.', null=True, verbose_name='Descripción / Notas'),
        ),
        migrations.AddField(
            model_name='alerttrigger',
            name='point_catchment',
            field=models.ForeignKey(blank=True, help_text='Para reglas globales, indica qué punto específico causó el trigger.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.catchmentpoint', verbose_name='Punto que disparó'),
        ),
    ]
