# Generated by Django 4.2.23 on 2026-05-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_add_trigger_point_and_rule_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='points',
            field=models.ManyToManyField(blank=True, help_text='Si se deja vacío, la regla evalúa TODOS los puntos.', related_name='alert_rules_m2m', to='core.catchmentpoint', verbose_name='Puntos aplicables'),
        ),
    ]
