# Generated by Django 4.2.27 on 2026-05-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_add_alert_rule_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='max_disconnection_days',
            field=models.IntegerField(blank=True, help_text='Para DISCONNECTION: ignorar puntos desconectados hace más de N días (evita spam). Por defecto 3.', null=True, verbose_name='Máximo días desconectado'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='target_type',
            field=models.CharField(choices=[('THRESHOLD_MAX', 'Umbral máximo'), ('THRESHOLD_MIN', 'Umbral mínimo'), ('NO_DATA', 'Sin datos por X tiempo'), ('DISCONNECTION', 'Punto desconectado'), ('RATE_OF_CHANGE', 'Tasa de cambio'), ('DEVIATION', 'Desviación estadística'), ('SCHEDULED_REPORT', 'Reporte programado')], max_length=50, verbose_name='Tipo de alerta'),
        ),
    ]
