# Generated by Django 4.2.27 on 2026-05-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_add_alertrule_max_disconnection_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='target_type',
            field=models.CharField(choices=[('THRESHOLD_MAX', 'Umbral máximo'), ('THRESHOLD_MIN', 'Umbral mínimo'), ('NO_DATA', 'Sin datos por X tiempo'), ('DISCONNECTION', 'Punto desconectado'), ('RECONNECTION', 'Punto reconectado'), ('RATE_OF_CHANGE', 'Tasa de cambio'), ('DEVIATION', 'Desviación estadística'), ('SCHEDULED_REPORT', 'Reporte programado')], max_length=50, verbose_name='Tipo de alerta'),
        ),
    ]
