# Generated by Django 4.2.27 on 2026-05-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_alertrule_target_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerttrigger',
            name='ai_diagnosis',
            field=models.TextField(blank=True, help_text='Informe generado automáticamente por el modelo de IA.', null=True, verbose_name='Diagnóstico IA'),
        ),
    ]
