# Generated by Django 4.2.27 on 2026-05-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_alertrule_target_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Si el valor ingresado es mayor, se marca como error. Dejar vacío para no validar.', max_digits=15, null=True, verbose_name='Valor máximo permitido'),
        ),
        migrations.AddField(
            model_name='variable',
            name='min_value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Si el valor ingresado es menor, se marca como error. Dejar vacío para no validar.', max_digits=15, null=True, verbose_name='Valor mínimo permitido'),
        ),
    ]
