# Generated by Django 4.2.27 on 2026-05-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_add_variable_min_max_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactiondetail',
            name='variable_values',
            field=models.JSONField(blank=True, default=dict, help_text='JSON con los valores crudos de cada variable: {variable_id: valor}. Permite esquemas dinámicos sin alterar la BD.', null=True, verbose_name='Valores por variable'),
        ),
        migrations.AddField(
            model_name='variable',
            name='display_key',
            field=models.CharField(blank=True, help_text='Cómo se muestra esta variable en la app (ej: caudal, nivel, total, custom_1). Si está vacío, usa type_variable.', max_length=100, null=True, verbose_name='Clave de visualización'),
        ),
    ]
