# Generated by Django 4.2.28 on 2026-05-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_add_variable_values_and_display_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('code', models.CharField(help_text='Identificador único del sistema. Ej: dga, sma, sea', max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('protocol', models.CharField(choices=[('HTTP_REST', 'HTTP REST (JSON)'), ('HTTP_SOAP', 'HTTP SOAP/XML'), ('WEBHOOK', 'Webhook (Google Chat, Slack, etc.)'), ('CUSTOM', 'Custom / Script')], default='HTTP_REST', max_length=20, verbose_name='Protocolo')),
                ('base_url', models.URLField(blank=True, help_text='Ej: https://apimee.mop.gob.cl/api/v1', max_length=500, verbose_name='URL base')),
                ('auth_url', models.URLField(blank=True, help_text='Opcional. Solo si el login es en endpoint separado (ej: SMA /auth)', max_length=500, verbose_name='URL de autenticación')),
                ('auth_type', models.CharField(choices=[('NONE', 'Sin autenticación'), ('BASIC', 'Basic Auth'), ('BEARER', 'Bearer Token'), ('API_KEY_HEADER', 'API Key en Header'), ('JSON_BODY', 'Credenciales en JSON Body')], default='NONE', max_length=20, verbose_name='Autenticación')),
                ('auth_username', models.CharField(blank=True, max_length=200, verbose_name='Usuario / RUT')),
                ('auth_password', models.CharField(blank=True, max_length=200, verbose_name='Password / Clave')),
                ('auth_token', models.CharField(blank=True, max_length=500, verbose_name='Token / API Key')),
                ('auth_header_name', models.CharField(blank=True, default='Authorization', max_length=100, verbose_name='Nombre del Header')),
                ('protocol_config', models.JSONField(blank=True, default=dict, help_text='\n        Config específica del protocolo en JSON.\n        DGA ejemplo:\n        {\n            "subterraneo_endpoint": "/mediciones/subterraneas",\n            "superficial_endpoint": "/mediciones/superficiales/flujometro",\n            "default_rut_empresa": "76944359-2"\n        }\n        SMA ejemplo:\n        {\n            "token_header": "Authorization",\n            "token_prefix": "Bearer"\n        }\n        ', verbose_name='Configuración del protocolo')),
                ('timeout_seconds', models.IntegerField(default=10, verbose_name='Timeout (segundos)')),
                ('retry_attempts', models.IntegerField(default=3, verbose_name='Reintentos')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Proveedor de Cumplimiento',
                'verbose_name_plural': 'Proveedores de Cumplimiento',
                'ordering': ['name'],
            },
        ),
    ]
