# Generated by Django 4.2.28 on 2026-05-17 21:20

from django.db import migrations, models
import django.db.models.deletion


def migrate_telemetry_providers(apps, schema_editor):
    """
    Asigna TelemetryProvider a cada CatchmentPoint según los booleanos legacy.
    Crea los providers por defecto si no existen.
    """
    CatchmentPoint = apps.get_model('core', 'CatchmentPoint')
    TelemetryProvider = apps.get_model('core', 'TelemetryProvider')

    # Crear/obtener providers por defecto si no existen
    defaults = {
        'tdata': {'name': 'TwinDimension (TDATA)', 'protocol': 'HTTP_REST', 'auth_type': 'JSON_BODY', 'handler_name': 'tdata'},
        'thethings': {'name': 'TheThings.io', 'protocol': 'HTTP_REST', 'auth_type': 'BEARER', 'handler_name': 'thethings'},
        'tago': {'name': 'Tago.io (Novus)', 'protocol': 'HTTP_REST', 'auth_type': 'API_KEY_HEADER', 'handler_name': 'tago'},
    }

    providers = {}
    for code, config in defaults.items():
        provider, created = TelemetryProvider.objects.get_or_create(
            handler_name=code,
            defaults=config,
        )
        providers[code] = provider
        if created:
            print(f"[MIGRACIÓN] Creado TelemetryProvider: {provider.name} (handler={code})")

    # Asignar provider a puntos según booleanos legacy
    mapping = {
        'is_tdata': providers['tdata'],
        'is_thethings': providers['thethings'],
        'is_novus': providers['tago'],
    }

    updated = 0
    for flag, provider in mapping.items():
        points = CatchmentPoint.objects.filter(**{flag: True, 'telemetry_provider__isnull': True})
        count = points.count()
        if count:
            points.update(telemetry_provider=provider)
            updated += count
            print(f"[MIGRACIÓN] {count} puntos con {flag}=True → {provider.name}")

    print(f"[MIGRACIÓN] Total puntos actualizados: {updated}")


def reverse_migrate_telemetry_providers(apps, schema_editor):
    """Reversible: solo limpia el campo (no toca booleanos)."""
    CatchmentPoint = apps.get_model('core', 'CatchmentPoint')
    CatchmentPoint.objects.all().update(telemetry_provider=None)
    print("[MIGRACIÓN REVERSA] telemetry_provider limpiado en todos los puntos")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_add_compliance_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='catchmentpoint',
            name='telemetry_provider',
            field=models.ForeignKey(blank=True, help_text='Proveedor configurable. Reemplaza los campos booleanos legacy (is_tdata, is_thethings, is_novus).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='core.telemetryprovider', verbose_name='Proveedor de telemetría'),
        ),
        migrations.RunPython(
            migrate_telemetry_providers,
            reverse_code=reverse_migrate_telemetry_providers,
        ),
    ]
