# Generated by Django 4.2.28 on 2026-05-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_add_telemetry_provider_to_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgadataconfigcatchment',
            name='send_sma',
            field=models.BooleanField(default=False, help_text='Si está activo, este punto enviará datos al sistema SMA.', verbose_name='Activar envío SMA'),
        ),
        migrations.AddField(
            model_name='dgadataconfigcatchment',
            name='sma_device_id',
            field=models.CharField(blank=True, help_text='Identificador del dispositivo en el sistema SMA (ej: 12180).', max_length=100, null=True, verbose_name='ID dispositivo SMA'),
        ),
    ]
