# Generated by Django 4.2.28 on 2026-05-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_add_sma_fields_dgaconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgadataconfigcatchment',
            name='dga_aggregate_points',
            field=models.JSONField(blank=True, default=list, help_text='Lista de IDs de puntos cuyo total se suma al enviar a DGA (ej: [84, 85]).', verbose_name='Puntos agregados DGA'),
        ),
        migrations.AddField(
            model_name='profiledataconfigcatchment',
            name='max_diff_m3_per_hour',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Consumo máximo razonable por hora. Si el salto es mayor, se ignora como error de sensor.', max_digits=10, verbose_name='Máx diff m³/hora'),
        ),
        migrations.AddField(
            model_name='profiledataconfigcatchment',
            name='max_flow_ls',
            field=models.DecimalField(decimal_places=2, default=150.0, help_text='Caudal máximo razonable. Si supera este valor, se pone en 0.', max_digits=10, verbose_name='Máx caudal L/s'),
        ),
    ]
