# Generated by Django 4.2.28 on 2026-05-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_add_processing_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledataconfigcatchment',
            name='max_time_gap_hours',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Si hay más horas sin datos que este valor, no se calcula caudal promedio (trata como reconexión).', max_digits=5, verbose_name='Máx gap horas'),
        ),
        migrations.AddField(
            model_name='profiledataconfigcatchment',
            name='reconnection_threshold_hours',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Si pasan más horas entre registros, se asume que el sensor se reconectó y el salto es legítimo.', max_digits=5, verbose_name='Umbral reconexión (horas)'),
        ),
    ]
