# Generated by Django 4.2.28 on 2026-05-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_add_time_thresholds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='variable_type',
            field=models.CharField(blank=True, help_text='Requerido para THRESHOLD_MAX, THRESHOLD_MIN, RATE_OF_CHANGE, DEVIATION. Valores conocidos: CAUDAL, NIVEL, TOTALIZADO, CAUDAL_PROMEDIO. Ignorado para NO_DATA y SCHEDULED_REPORT.', max_length=50, null=True, verbose_name='Variable a monitorear'),
        ),
        migrations.AlterField(
            model_name='catchmentpoint',
            name='frecuency',
            field=models.CharField(blank=True, default='60', help_text='Frecuencia de telemetría en minutos. Valores comunes: 1, 5, 10, 15, 30, 60.', max_length=300, null=True, verbose_name='Frecuencia'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='type_variable',
            field=models.CharField(help_text='Tipo semántico: CAUDAL, NIVEL, TOTALIZADO, CAUDAL_PROMEDIO, o cualquier nuevo tipo. El procesador unificado aplica lógica específica solo a los tipos conocidos.', max_length=1200, verbose_name='Tipo variable'),
        ),
    ]
