# Generated by Django 4.2.28 on 2026-05-18 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_remove_choices_frecuency_variable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterResetLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('date_time_medition', models.DateTimeField(help_text='Timestamp del registro InteractionDetail que disparó el reset', verbose_name='Fecha/hora de la medición')),
                ('time_diff_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Horas desde última medición')),
                ('reset_type', models.CharField(choices=[('ZERO', 'Reset a 0'), ('PARTIAL', 'Reset parcial (0 < actual < anterior)'), ('MASSIVE_JUMP', 'Salto masivo bloqueado'), ('NEGATIVE_PULSES', 'Pulsos negativos (error de ingesta)')], max_length=20, verbose_name='Tipo de reset')),
                ('last_pulses', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Pulsos anteriores')),
                ('current_pulses', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Pulsos actuales')),
                ('pulses_factor', models.IntegerField(verbose_name='Factor de pulsos')),
                ('addition_before', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Addition antes del reset')),
                ('amount_to_add', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Volumen compensado (m³)')),
                ('addition_after', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Addition después del reset')),
                ('total_before', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Total anterior (m³)')),
                ('total_after', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Total calculado post-reset (m³)')),
                ('passed_anti_jump', models.BooleanField(default=True, verbose_name='Pasó validación anti-salto')),
                ('reconnection_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Umbral de reconexión (horas)')),
                ('is_reconnection', models.BooleanField(default=False, verbose_name='Detectado como reconexión')),
                ('days_not_connection', models.IntegerField(blank=True, null=True, verbose_name='Días sin conexión (último registro)')),
                ('detected_by', models.CharField(default='cron_unified', max_length=100, verbose_name='Detectado por')),
                ('point_catchment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_reset_logs', to='core.catchmentpoint', verbose_name='Punto de captación')),
            ],
            options={
                'verbose_name': 'Log de Reset de Contador',
                'verbose_name_plural': 'Logs de Resets de Contadores',
                'ordering': ['-date_time_medition'],
                'indexes': [models.Index(fields=['point_catchment', 'date_time_medition'], name='core_counte_point_c_f20099_idx'), models.Index(fields=['reset_type', 'date_time_medition'], name='core_counte_reset_t_1422c4_idx')],
            },
        ),
    ]
