# Generated by Django 4.2.28 on 2026-05-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_counterresetlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterresetlog',
            name='reset_type',
            field=models.CharField(choices=[('ZERO', 'Reset a 0'), ('PARTIAL', 'Reset parcial (0 < actual < anterior)'), ('PARTIAL_REJECTED', 'Reset parcial rechazado (sin evidencia de desconexión)'), ('MASSIVE_JUMP', 'Salto masivo bloqueado'), ('NEGATIVE_PULSES', 'Pulsos negativos (error de ingesta)')], max_length=20, verbose_name='Tipo de reset'),
        ),
    ]
