# Generated by Django 4.2.23 on 2026-05-22 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alertrule_legacy_notification_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('category', models.CharField(blank=True, choices=[('SOFTWARE', 'Software'), ('HARDWARE', 'Hardware'), ('CONECTIVIDAD', 'Conectividad'), ('DGA', 'DGA'), ('TELEMETRIA', 'Telemetría'), ('OT', 'Orden de Trabajo')], help_text='Si se deja vacío, aplica a todas las categorías.', max_length=50, null=True, verbose_name='Categoría')),
                ('priority', models.CharField(blank=True, choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], help_text='Si se deja vacío, aplica a todas las prioridades.', max_length=20, null=True, verbose_name='Prioridad')),
                ('response_time_hours', models.IntegerField(default=4, help_text='Horas máximas para dar primera respuesta al ticket.', verbose_name='Tiempo de respuesta (horas)')),
                ('resolution_time_hours', models.IntegerField(default=24, help_text='Horas máximas para resolver el ticket.', verbose_name='Tiempo de resolución (horas)')),
                ('business_hours_only', models.BooleanField(default=False, help_text='Si es True, el SLA solo corre en días hábiles (L-V 9:00-18:00).', verbose_name='Solo horario hábil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('client', models.ForeignKey(blank=True, help_text='Si se deja vacío, aplica a todos los clientes.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='Cliente')),
                ('escalation_user', models.ForeignKey(blank=True, help_text='A quién notificar si se vence el SLA.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario de escalamiento')),
                ('project', models.ForeignKey(blank=True, help_text='Si se deja vacío, aplica a todos los proyectos del cliente.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.projectcatchments', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Configuración SLA',
                'verbose_name_plural': 'Configuraciones SLA',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('status', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_ANALISIS', 'En análisis'), ('ESPERA_CLIENTE', 'Espera cliente'), ('ESPERA_PROVEEDOR', 'Espera proveedor'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], db_index=True, default='ABIERTO', max_length=30, verbose_name='Estado')),
                ('priority', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], db_index=True, default='MEDIA', max_length=20, verbose_name='Prioridad')),
                ('category', models.CharField(choices=[('SOFTWARE', 'Software'), ('HARDWARE', 'Hardware'), ('CONECTIVIDAD', 'Conectividad'), ('DGA', 'DGA'), ('TELEMETRIA', 'Telemetría'), ('OT', 'Orden de Trabajo')], db_index=True, default='TELEMETRIA', max_length=30, verbose_name='Categoría')),
                ('source', models.CharField(choices=[('APP_CLIENTE', 'App Cliente'), ('APP_ADMIN', 'App Admin'), ('ALERTA_AUTO', 'Alerta automática'), ('SISTEMA', 'Sistema'), ('CORREO', 'Correo'), ('TELEFONO', 'Teléfono')], default='APP_CLIENTE', max_length=30, verbose_name='Origen/Canal')),
                ('origin', models.CharField(choices=[('CLIENTE', 'Cliente'), ('INTERNO', 'Interno')], db_index=True, default='CLIENTE', max_length=20, verbose_name='Origen (cliente/interno)')),
                ('sla_deadline_response', models.DateTimeField(blank=True, null=True, verbose_name='Límite primera respuesta')),
                ('sla_deadline_resolution', models.DateTimeField(blank=True, null=True, verbose_name='Límite resolución')),
                ('sla_responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Primera respuesta dada')),
                ('sla_resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resuelto según SLA')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('alert_trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='core.alerttrigger', verbose_name='Alerta relacionada')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('point_catchment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='core.catchmentpoint', verbose_name='Punto de captación')),
                ('sla_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.slaconfig', verbose_name='Configuración SLA aplicada')),
                ('system_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='core.systemevent', verbose_name='Evento de sistema relacionado')),
            ],
            options={
                'verbose_name': 'Ticket de soporte',
                'verbose_name_plural': 'Tickets de soporte',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('is_internal', models.BooleanField(default=False, help_text='Si es True, el cliente no ve este comentario.', verbose_name='Nota interna')),
                ('status_change', models.CharField(blank=True, help_text='Si este comentario cambió el estado del ticket, registra el nuevo estado.', max_length=30, null=True, verbose_name='Cambio de estado')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_comments', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.supportticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Comentario de ticket',
                'verbose_name_plural': 'Comentarios de tickets',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('file', models.FileField(upload_to='tickets/%Y/%m/', verbose_name='Archivo')),
                ('original_name', models.CharField(blank=True, max_length=300, verbose_name='Nombre original')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.ticketcomment', verbose_name='Comentario')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.supportticket', verbose_name='Ticket')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Adjunto de ticket',
                'verbose_name_plural': 'Adjuntos de tickets',
            },
        ),
        migrations.CreateModel(
            name='TicketActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('field_name', models.CharField(max_length=100, verbose_name='Campo modificado')),
                ('old_value', models.CharField(blank=True, max_length=500, null=True, verbose_name='Valor anterior')),
                ('new_value', models.CharField(blank=True, max_length=500, null=True, verbose_name='Valor nuevo')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='core.supportticket', verbose_name='Ticket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de actividad',
                'verbose_name_plural': 'Logs de actividad',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['point_catchment', 'status', 'is_active'], name='core_suppor_point_c_6f251b_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['assigned_to', 'status', 'is_active'], name='core_suppor_assigne_71b991_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['origin', 'status', 'is_active'], name='core_suppor_origin_5e803c_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['category', 'status', 'is_active'], name='core_suppor_categor_db22f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='slaconfig',
            unique_together={('client', 'project', 'category', 'priority')},
        ),
    ]
