# Generated by Django 4.2.28 on 2026-05-23 21:16
# Customizado: preserva la columna interaction_detail_id en BD eliminando solo la constraint FK.
# Esto desbloquea el particionamiento declarativo de InteractionDetail (PostgreSQL 15
# no permite FKs desde tablas no-particionadas hacia tablas particionadas).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_add_ticket_subsystem'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # PostgreSQL: eliminar solo la constraint FK, mantener la columna y sus datos
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE core_alerttrigger
                        DROP CONSTRAINT IF EXISTS core_alerttrigger_interaction_detail_id_fkey;
                    """,
                    reverse_sql="""
                        ALTER TABLE core_alerttrigger
                        ADD CONSTRAINT core_alerttrigger_interaction_detail_id_fkey
                        FOREIGN KEY (interaction_detail_id) REFERENCES core_interactiondetail(id)
                        ON DELETE SET NULL;
                    """,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='alerttrigger',
                    name='interaction_detail',
                ),
                migrations.AddField(
                    model_name='alerttrigger',
                    name='interaction_detail_id',
                    field=models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text='Referencia blanda a InteractionDetail (IntegerField para compatibilidad con particionamiento).',
                        null=True,
                        verbose_name='ID de registro de telemetría relacionado',
                    ),
                ),
            ],
        ),
    ]
