# Generated by Django 4.2.23 on 2026-05-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_remove_alerttrigger_interaction_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactiondetail',
            name='dga_last_retry_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp del último ciclo de reintento persistente.', null=True, verbose_name='Último reintento DGA'),
        ),
        migrations.AddField(
            model_name='interactiondetail',
            name='dga_retry_count',
            field=models.IntegerField(default=0, help_text='Contador de ciclos de reintento persistente (fuera del loop de 3 intentos inmediatos).', verbose_name='Reintentos DGA persistentes'),
        ),
    ]
