# Generated by Django 4.2.23 on 2026-05-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_add_dga_retry_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactiondetail',
            name='flow',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Caudal(lt)'),
        ),
        migrations.AlterField(
            model_name='interactiondetail',
            name='nivel',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Nivel(mt)'),
        ),
        migrations.AlterField(
            model_name='interactiondetail',
            name='water_table',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Nivel freático(mt)'),
        ),
        migrations.AddIndex(
            model_name='interactiondetail',
            index=models.Index(fields=['send_dga', 'is_error', 'date_time_medition'], name='core_interact_dga_err_dt'),
        ),
    ]
