# Generated by Django 4.2.23 on 2026-06-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_add_dga_error_index_and_widen_decimals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterresetlog',
            name='reset_type',
            field=models.CharField(choices=[('ZERO', 'Reset a 0'), ('ZERO_KEPT', 'Reset a 0 - total preservado'), ('PARTIAL', 'Reset parcial (0 < actual < anterior)'), ('PARTIAL_REJECTED', 'Reset parcial rechazado (sin evidencia de desconexión)'), ('MASSIVE_JUMP', 'Salto masivo bloqueado'), ('NEGATIVE_PULSES', 'Pulsos negativos (error de ingesta)')], max_length=20, verbose_name='Tipo de reset'),
        ),
        migrations.AddIndex(
            model_name='catchmentpoint',
            index=models.Index(fields=['project', 'title'], name='ik_cp_proj_title_idx'),
        ),
        migrations.AddIndex(
            model_name='catchmentpoint',
            index=models.Index(fields=['owner_user', 'title'], name='ik_cp_owner_title_idx'),
        ),
        migrations.AddIndex(
            model_name='dgadataconfigcatchment',
            index=models.Index(fields=['point_catchment', 'send_dga'], name='ik_dga_cfg_pt_send_idx'),
        ),
        migrations.AddIndex(
            model_name='dgadataconfigcatchment',
            index=models.Index(fields=['send_dga', 'code_dga'], name='ik_dga_cfg_code_idx'),
        ),
        migrations.AddIndex(
            model_name='dgadataconfigcatchment',
            index=models.Index(fields=['send_sma', 'sma_device_id'], name='ik_dga_cfg_sma_idx'),
        ),
        migrations.AddIndex(
            model_name='interactiondetail',
            index=models.Index(fields=['catchment_point', 'date_time_medition', 'total_diff'], name='ik_cc_id_total_idx'),
        ),
        migrations.AddIndex(
            model_name='interactiondetail',
            index=models.Index(fields=['catchment_point', 'date_time_medition', 'flow'], name='ik_cc_id_flow_idx'),
        ),
        migrations.AddIndex(
            model_name='interactiondetail',
            index=models.Index(fields=['catchment_point', 'date_time_medition', 'n_voucher'], name='ik_cc_id_voucher_idx'),
        ),
    ]
