# Generated by Django 4.2.23 on 2026-07-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_counterresetlog_reset_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Fecha de visita o ejecución planificada por operaciones.', null=True, verbose_name='Fecha planificada'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='visit_report',
            field=models.TextField(blank=True, help_text='Reporte técnico posterior a la visita/ejecución.', null=True, verbose_name='Informe de visita'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_ANALISIS', 'En análisis'), ('EN_ORDEN_TRABAJO', 'En orden de trabajo'), ('ESPERA_CLIENTE', 'Espera cliente'), ('ESPERA_PROVEEDOR', 'Espera proveedor'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], db_index=True, default='ABIERTO', max_length=30, verbose_name='Estado'),
        ),
    ]
