# Generated by Django 4.2.30 on 2026-07-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_supportticket_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='critical',
            field=models.BooleanField(default=False, help_text='Marca clientes críticos para priorizar monitoreo y alertas.', verbose_name='Crítico'),
        ),
    ]
