# Generated by Django 4.2.30 on 2026-07-02 20:53

from django.db import migrations, models
import django.db.models.deletion


def seed_categories_and_migrate_data(apps, schema_editor):
    """
    Crea las categorías base y migra los valores legacy de:
      - SupportTicket.category  (CharField) -> category_new (FK)
      - SLAConfig.category      (CharField) -> category_new (FK)
      - SupportTicket.point_catchment (FK)  -> points (M2M)
    """
    TicketCategory = apps.get_model("core", "TicketCategory")
    SupportTicket = apps.get_model("core", "SupportTicket")
    SLAConfig = apps.get_model("core", "SLAConfig")

    # Mapeo de categorías legacy a (tipo, nombre)
    legacy_map = {
        "SOFTWARE": ("SOFTWARE", "Software"),
        "HARDWARE": ("HARDWARE", "Hardware"),
        "CONECTIVIDAD": ("HARDWARE", "Conectividad"),
        "DGA": ("COMPLIANCE", "Cumplimiento DGA"),
        "TELEMETRIA": ("HARDWARE", "Telemetría"),
        "OT": ("WORK_ORDER", "Orden de Trabajo"),
    }

    category_ids = {}
    for legacy_value, (cat_type, name) in legacy_map.items():
        cat, _ = TicketCategory.objects.get_or_create(
            category_type=cat_type,
            name=name,
            parent=None,
            defaults={"is_active": True},
        )
        category_ids[legacy_value] = cat.id

    # Migrar SLAConfig
    for sla in SLAConfig.objects.all().iterator():
        new_id = category_ids.get(sla.category)
        if new_id:
            sla.category_new_id = new_id
            sla.save(update_fields=["category_new"])

    # Migrar SupportTicket
    for ticket in SupportTicket.objects.all().iterator():
        changed = False
        new_id = category_ids.get(ticket.category)
        if new_id:
            ticket.category_new_id = new_id
            changed = True
        if ticket.point_catchment_id:
            ticket.points.add(ticket.point_catchment_id)
        if changed:
            ticket.save(update_fields=["category_new"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_add_client_critical_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketCategory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, help_text="Fecha de creacion.", verbose_name="created at")),
                ("modified", models.DateTimeField(auto_now_add=True, help_text="Fecha de modificacion.", verbose_name="modified at")),
                ("category_type", models.CharField(choices=[("SOFTWARE", "Software"), ("HARDWARE", "Hardware"), ("COMPLIANCE", "Cumplimiento"), ("WORK_ORDER", "Orden de Trabajo")], max_length=20, verbose_name="Tipo")),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="subcategories", to="core.ticketcategory", verbose_name="Categoría padre")),
            ],
            options={
                "verbose_name": "Categoría de ticket",
                "verbose_name_plural": "Categorías de tickets",
                "ordering": ["category_type", "name"],
                "unique_together": {("category_type", "name", "parent")},
            },
        ),
        # Campos temporales FK para migrar sin perder datos
        migrations.AddField(
            model_name="slaconfig",
            name="category_new",
            field=models.ForeignKey(
                blank=True,
                help_text="Si se deja vacío, aplica a todas las categorías.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sla_configs_new",
                to="core.ticketcategory",
                verbose_name="Categoría",
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="category_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets_new",
                to="core.ticketcategory",
                verbose_name="Categoría",
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="points",
            field=models.ManyToManyField(related_name="support_tickets", to="core.catchmentpoint", verbose_name="Puntos de captación"),
        ),
        # Migrar datos
        migrations.RunPython(seed_categories_and_migrate_data, migrations.RunPython.noop),
        # Eliminar campos legacy
        migrations.RemoveField(
            model_name="slaconfig",
            name="category",
        ),
        migrations.RemoveField(
            model_name="supportticket",
            name="category",
        ),
        migrations.RemoveField(
            model_name="supportticket",
            name="point_catchment",
        ),
        # Renombrar los nuevos campos a los nombres definitivos
        migrations.RenameField(
            model_name="slaconfig",
            old_name="category_new",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="supportticket",
            old_name="category_new",
            new_name="category",
        ),
    ]
