# Generated by Django 4.2.23 on 2026-07-03 05:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_seed_subcategories_and_default_sla'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcategory',
            name='notify_operators_on_create',
            field=models.BooleanField(default=True, help_text='Si está activo, se enviará un correo a los operadores cuando se cree un ticket de esta categoría.', verbose_name='Notificar operadores al crear ticket'),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='operators',
            field=models.ManyToManyField(blank=True, help_text='Usuarios que recibirán notificación cuando se cree un ticket en esta categoría.', related_name='operated_ticket_categories', to=settings.AUTH_USER_MODEL, verbose_name='Operadores'),
        ),
    ]
