# Generated by Django 4.2.23 on 2026-07-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_ticketcategory_notify_operators_on_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='sla_last_overdue_notification',
            field=models.DateTimeField(blank=True, help_text='Se usa para evitar enviar spam de recordatorios.', null=True, verbose_name='Última notificación de SLA vencido'),
        ),
    ]
