# Generated by Django 4.2.30 on 2026-07-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_supportticket_sla_last_overdue_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='origin',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('INTERNO', 'Interno'), ('OPERACIONES', 'Operaciones')], db_index=True, default='CLIENTE', max_length=20, verbose_name='Origen (cliente/interno)'),
        ),
    ]
