# Generated by Django 4.2.23 on 2026-07-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_alter_supportticket_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertchannel',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='alerttrigger',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='catchmentpoint',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='client',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='complianceprovider',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='counterresetlog',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='dgadataconfigcatchment',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='filecatchment',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='interactiondetail',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='notificationscatchment',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='profiledataconfigcatchment',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='profileikolucatchment',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='projectcatchments',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='registerpersons',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='responsenotificationscatchment',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='schemescatchment',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='slaconfig',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='systemevent',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='telemetryprovider',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='ticketactivitylog',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='typefilecatchment',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at'),
        ),
    ]
