# Generated by Django 4.2.30 on 2026-07-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_alter_alertchannel_modified_alter_alertrule_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledataconfigcatchment',
            name='disable_thethings_polling',
            field=models.BooleanField(default=False, help_text='Si es True, el cron unificado no consulta TheThings.io REST para este punto porque los datos llegan vía MQTT/webhook.', verbose_name='Desactivar polling de TheThings.io'),
        ),
    ]
