# Generated by Django 4.2.30 on 2026-07-31 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_add_disable_thethings_polling'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='scheduled_date_confirmed',
            field=models.BooleanField(default=False, help_text='Indica si la fecha planificada fue confirmada por el involucrado.', verbose_name='Fecha planificada confirmada'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='scheduled_date_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se confirmó la fecha planificada.', null=True, verbose_name='Fecha confirmada en'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='scheduled_date_confirmed_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que confirmó la fecha planificada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_ticket_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Fecha confirmada por'),
        ),
    ]
