# Generated by Django 4.2.30 on 2026-07-31 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_supportticket_scheduled_date_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='scheduled_date_cancelled',
            field=models.BooleanField(default=False, help_text='Indica si la fecha planificada fue cancelada y queda a la espera de re-agendar.', verbose_name='Fecha planificada cancelada'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='scheduled_date_cancelled_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se canceló la fecha planificada.', null=True, verbose_name='Fecha cancelada en'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='scheduled_date_cancelled_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que canceló la fecha planificada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_ticket_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Fecha cancelada por'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='scheduled_date_cancelled_reason',
            field=models.TextField(blank=True, help_text='Motivo por el que se canceló la fecha planificada.', null=True, verbose_name='Motivo de cancelación'),
        ),
    ]
