# Generated by Django 4.2.30 on 2026-08-04 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_supportticket_scheduled_date_cancelled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='work_order_category',
            field=models.ForeignKey(blank=True, help_text='Subcategoría de tipo WORK_ORDER que describe la orden de trabajo. Solo aplica mientras el ticket está en estado EN_ORDEN_TRABAJO; la categoría original del ticket se mantiene intacta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_tickets', to='core.ticketcategory', verbose_name='Categoría de orden de trabajo'),
        ),
    ]
