# Generated by Django 4.2.30 on 2026-08-05 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_supportticket_work_order_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicketTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDIENTE', max_length=30, verbose_name='Estado')),
                ('priority', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], db_index=True, default='MEDIA', max_length=20, verbose_name='Prioridad')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha límite')),
                ('created_stage', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_ANALISIS', 'En análisis'), ('EN_ORDEN_TRABAJO', 'En orden de trabajo'), ('ESPERA_CLIENTE', 'Espera cliente'), ('ESPERA_PROVEEDOR', 'Espera proveedor'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], help_text='Estado del ticket cuando se creó la tarea (snapshot automático).', max_length=30, verbose_name='Etapa de creación')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ticket_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ticket_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.supportticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Tarea de ticket',
                'verbose_name_plural': 'Tareas de tickets',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.supporttickettask', verbose_name='Tarea'),
        ),
        migrations.AddIndex(
            model_name='supporttickettask',
            index=models.Index(fields=['ticket', 'status'], name='core_suppor_ticket__6d7aa6_idx'),
        ),
        migrations.AddIndex(
            model_name='supporttickettask',
            index=models.Index(fields=['assigned_to', 'status'], name='core_suppor_assigne_ed99ae_idx'),
        ),
    ]
