# Generated by Django 4.2.30 on 2026-08-07 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_supporttickettask_ticketattachment_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaconfig',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='URL que recibe un POST JSON cuando el SLA de un ticket con esta configuración vence. Si está vacío, se usa settings.SLA_OVERDUE_WEBHOOK_URL si existe.', null=True, verbose_name='Webhook SLA'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_email',
            field=models.BooleanField(default=True, help_text='Si está activo, el usuario recibe correos del subsistema de tickets (menciones, SLA, etc.).'),
        ),
        migrations.CreateModel(
            name='TicketNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('notification_type', models.CharField(choices=[('MENTION', 'Mención en comentario')], default='MENTION', max_length=30, verbose_name='Tipo')),
                ('message', models.CharField(max_length=500, verbose_name='Mensaje')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.ticketcomment', verbose_name='Comentario')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.supportticket', verbose_name='Ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación de ticket',
                'verbose_name_plural': 'Notificaciones de tickets',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='ik_tktnotif_user_read_idx')],
            },
        ),
    ]
