# Generated by Django 4.2.30 on 2026-08-07 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_slaconfig_webhook_url_user_notify_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Si es una respuesta a otro comentario, referencia al comentario original (hilos).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='core.ticketcomment', verbose_name='Comentario padre'),
        ),
    ]
