# Generated by Django 4.2.30 on 2026-08-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_ticketcomment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketnotification',
            name='notification_type',
            field=models.CharField(choices=[('MENTION', 'Mención en comentario'), ('REFERENCE', 'Referencia a otro ticket')], default='MENTION', max_length=30, verbose_name='Tipo'),
        ),
    ]
