# Generated by Django 4.2.30 on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_ticketcommentlike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Imagen de perfil del usuario.', null=True, upload_to='profile_images/', verbose_name='Foto de perfil'),
        ),
    ]
