# Generated by Django 4.2.30 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='sla_paused_at',
            field=models.DateTimeField(blank=True, help_text='Marca cuándo se pausó el SLA (estados de espera). Mientras está seteado el reloj del SLA no corre; al salir del estado de espera los plazos se desplazan por el tiempo pausado y este campo se limpia.', null=True, verbose_name='SLA pausado en'),
        ),
    ]
