# Generated by Django 5.2.10 on 2026-01-23 01:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telemetry', '0004_remove_corevariable_provider_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(help_text="Unique identifier for the provider (e.g., 'nettra', 'twin', 'novus')", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text="Human-readable name (e.g., 'Nettra IoT Platform')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the provider')),
                ('provider_type', models.CharField(choices=[('api', 'REST API'), ('mqtt_server', 'MQTT Server (broker local - equipos publican hacia SmartHydro)'), ('mqtt_client', 'MQTT Client (broker externo - SmartHydro consume de terceros)'), ('modbus', 'ModBus TCP'), ('http', 'HTTP Endpoint'), ('websocket', 'WebSocket')], default='api', help_text='\n        Protocolo de comunicación:\n        - api: REST API de terceros\n        - mqtt_server: Broker local, equipos publican hacia SmartHydro\n        - mqtt_client: Broker externo, SmartHydro se conecta como cliente\n        - modbus: ModBus TCP/IP\n        ', max_length=20)),
                ('base_url', models.URLField(help_text='Base URL for API endpoints (e.g., https://api.nettra.cl)', validators=[django.core.validators.URLValidator()])),
                ('timeout_seconds', models.IntegerField(default=30, help_text='Request timeout in seconds')),
                ('auth_method', models.CharField(choices=[('none', 'No Authentication'), ('bearer', 'Bearer Token'), ('basic', 'Basic Authentication'), ('api_key', 'API Key'), ('oauth2', 'OAuth2'), ('custom', 'Custom Authentication')], default='bearer', help_text='Authentication method to use', max_length=20)),
                ('auth_config', models.JSONField(blank=True, default=dict, help_text='\n        Authentication configuration as JSON. Examples:\n        - Bearer: {"token": "your_token"}\n        - Basic: {"username": "user", "password": "pass"}\n        - API Key: {"key": "api_key", "header": "X-API-Key"}\n        - OAuth2: {"client_id": "id", "client_secret": "secret", "token_url": "url"}\n        ')),
                ('endpoint_template', models.CharField(help_text='\n        Template for building endpoint URLs. Use {variables}.\n        Examples:\n        - "/api/v1/devices/{device_id}/data"\n        - "/data?point={point_code}&variable={variable}"\n        ', max_length=500)),
                ('request_template', models.JSONField(blank=True, default=dict, help_text='\n        Template for request payload as JSON.\n        Use {variables} for dynamic content.\n        Example: {"device_id": "{device_code}", "variable": "{variable_type}"}\n        ')),
                ('response_mapping', models.JSONField(blank=True, default=dict, help_text='\n        Mapping for parsing API responses to standardized format.\n        Example: {\n            "timestamp": "data.time",\n            "value": "data.value",\n            "unit": "data.unit"\n        }\n        ')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this provider is available for use')),
                ('max_retries', models.IntegerField(default=3, help_text='Maximum number of retry attempts for failed requests')),
                ('retry_delay_seconds', models.IntegerField(default=1, help_text='Delay between retry attempts in seconds')),
                ('version', models.CharField(default='1.0', help_text='Provider API version', max_length=20)),
                ('documentation_url', models.URLField(blank=True, help_text='URL to provider documentation')),
            ],
            options={
                'verbose_name': 'Proveedor de Telemetría',
                'verbose_name_plural': 'Proveedores de Telemetría',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MQTTProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_identifier', models.SlugField(default='generic', help_text="Identificador único del servicio/protocolo (ej: 'netra', 'novus')")),
                ('service_description', models.TextField(blank=True, help_text='Descripción del propósito de este servicio MQTT')),
                ('mqtt_mode', models.CharField(choices=[('server', 'Servidor MQTT (escuchar broker local)'), ('client', 'Cliente MQTT (conectar a broker externo)')], default='server', help_text='\n        Rol MQTT:\n        - server: SmartHydro ESCUCHA topics en broker local (equipos publican hacia SmartHydro)\n        - client: SmartHydro se CONECTA a broker externo (SmartHydro consume de terceros)\n        ', max_length=10)),
                ('broker_host', models.CharField(help_text='Host/IP del broker MQTT (ej: broker.hivemq.com)', max_length=255)),
                ('broker_port', models.IntegerField(default=1883, help_text='Puerto del broker MQTT (1883 para MQTT, 8883 para MQTTS)')),
                ('use_tls', models.BooleanField(default=False, help_text='¿Usar TLS/SSL para la conexión?')),
                ('client_id_prefix', models.CharField(default='smarthydro', help_text='Prefijo para generar client_id únicos (ej: smarthydro)', max_length=50)),
                ('subscribe_topic_template', models.CharField(help_text='\n        Template para topics de suscripción. Usa {variables}:\n        - {provider}: Nombre del proveedor\n        - {device_id}: ID del dispositivo\n        - {point_code}: Código del punto\n        Ejemplo: "{provider}/{device_id}/telemetry"\n        ', max_length=500, validators=[django.core.validators.RegexValidator(message='Debe contener al menos una variable entre llaves {variable}', regex='\\{[^}]+\\}')])),
                ('publish_topic_template', models.CharField(blank=True, help_text='\n        Template para topics de publicación (opcional).\n        Usa las mismas variables que subscribe_topic_template.\n        ', max_length=500)),
                ('default_qos', models.IntegerField(choices=[(0, '0 - Al menos una vez'), (1, '1 - Al menos una vez'), (2, '2 - Exactamente una vez')], default=1, help_text='QoS por defecto para mensajes')),
                ('retain_messages', models.BooleanField(default=False, help_text='¿Retener mensajes en el broker?')),
                ('username', models.CharField(blank=True, help_text='Usuario para autenticación MQTT (opcional)', max_length=100)),
                ('password', models.CharField(blank=True, help_text='Contraseña para autenticación MQTT (opcional)', max_length=255)),
                ('keep_alive', models.IntegerField(default=60, help_text='Intervalo keep-alive en segundos')),
                ('reconnect_delay', models.IntegerField(default=5, help_text='Delay entre reintentos de conexión en segundos')),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mqtt_config', to='telemetry_providers.telemetryprovider', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Configuración MQTT del Proveedor',
                'verbose_name_plural': 'Configuraciones MQTT de Proveedores',
            },
        ),
        migrations.CreateModel(
            name='ProviderDataSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('sync_type', models.CharField(choices=[('FULL_HISTORICAL', 'Histórico Completo'), ('INCREMENTAL', 'Incremental'), ('REALTIME', 'Tiempo Real (Polling)')], default='INCREMENTAL', max_length=20)),
                ('current_status', models.CharField(choices=[('IDLE', 'Inactivo'), ('RUNNING', 'Ejecutando'), ('SUCCESS', 'Exitoso'), ('PARTIAL_SUCCESS', 'Parcialmente Exitoso'), ('FAILED', 'Fallido'), ('CANCELLED', 'Cancelado')], default='IDLE', max_length=20)),
                ('last_sync_attempt', models.DateTimeField(blank=True, null=True)),
                ('last_successful_sync', models.DateTimeField(blank=True, null=True)),
                ('total_records_synced', models.BigIntegerField(default=0)),
                ('last_sync_records', models.IntegerField(default=0)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('last_error_message', models.TextField(blank=True)),
                ('sync_config', models.JSONField(blank=True, default=dict, help_text='Configuración específica del trabajo (buffer, threads, etc)')),
                ('is_active', models.BooleanField(default=True)),
                ('sync_interval_minutes', models.IntegerField(default=60)),
                ('messages_received_today', models.IntegerField(default=0)),
                ('messages_sent_today', models.IntegerField(default=0)),
                ('bytes_received_today', models.BigIntegerField(default=0)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='telemetry_providers.telemetryprovider', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Sincronización de Proveedor',
                'verbose_name_plural': 'Sincronizaciones de Proveedores',
                'unique_together': {('provider', 'sync_type')},
            },
        ),
        migrations.CreateModel(
            name='PayloadParsingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo de la regla', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descripción detallada de cuándo y cómo usar esta regla')),
                ('rule_type', models.CharField(choices=[('topic_match', 'Coincidencia de Topic (Regex)'), ('payload_field', 'Campo específico en Payload'), ('device_type', 'Tipo de Dispositivo'), ('always', 'Siempre Aplicar (Default)')], default='always', help_text='Tipo de condición para aplicar esta regla', max_length=20)),
                ('rule_condition', models.JSONField(blank=True, default=dict, help_text='\n        Condición para aplicar la regla según rule_type:\n\n        topic_match: {"pattern": "novus/+/data"}\n        payload_field: {"field": "device_type", "value": "nxperience"}\n        device_type: {"type": "plc_siemens"}\n        always: {} (vacío)\n        ')),
                ('parsing_method', models.CharField(choices=[('template', 'Template con Variables'), ('jsonpath', 'JSONPath/JMESPath'), ('python', 'Script Python'), ('regex', 'Expresiones Regulares')], default='jsonpath', help_text='Método para extraer datos del payload', max_length=20)),
                ('field_mappings', models.JSONField(default=dict, help_text='\n        Mapeo de campos a extraer. Formato depende del parsing_method:\n\n        template: {"field_name": "payload.{json_field}"}\n        jsonpath: {"field_name": {"source": "$.data.value", "type": "jsonpath"}}\n        python: {"field_name": "extract_custom_field(payload)"}\n        regex: {"field_name": {"pattern": "value:(\\d+)", "group": 1}}\n        ')),
                ('transformations', models.JSONField(blank=True, default=list, help_text='\n        Lista de transformaciones a aplicar a los campos extraídos.\n        Ejemplo: [\n            {"field": "timestamp", "type": "unix_to_datetime"},\n            {"field": "flow", "type": "unit_conversion", "from": "m3/h", "to": "L/s"}\n        ]\n        ')),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='\n        Reglas de validación para campos extraídos.\n        Ejemplo: {\n            "flow": {"min": 0, "max": 1000},\n            "timestamp": {"not_null": true}\n        }\n        ')),
                ('priority', models.IntegerField(default=0, help_text='Prioridad de aplicación (mayor = primero)')),
                ('is_active', models.BooleanField(default=True, help_text='¿Esta regla está activa?')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsing_rules', to='telemetry_providers.telemetryprovider', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Regla de Parsing de Payload',
                'verbose_name_plural': 'Reglas de Parsing de Payload',
                'ordering': ['-priority', 'name'],
                'unique_together': {('provider', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CatchmentPointProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('provider_variable_key', models.CharField(blank=True, help_text="Identificador de la variable en este sistema externo específico (ej: '4001', 'v_caudal').", max_length=100, verbose_name='Key/ID de Variable en Proveedor')),
                ('config_override', models.JSONField(blank=True, default=dict, help_text='\n        Override provider configuration for this specific point.\n        Same format as TelemetryProvider.auth_config.\n        ')),
                ('provider_device_id', models.CharField(blank=True, help_text='\n        Identificador del dispositivo en el sistema del proveedor externo.\n        Ejemplos:\n        - Nettra: "station_123"\n        - TTN: "eui-70b3d57ed0012345"\n        - MQTT: "device_001" o serial del equipo\n        ', max_length=100, verbose_name='ID del Dispositivo en el Proveedor')),
                ('device_config', models.JSONField(blank=True, default=dict, help_text='Device-specific configuration (e.g., sensor mappings, calibration data)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this provider configuration is active for the point')),
                ('priority', models.IntegerField(default=0, help_text='Priority for load balancing/failover (higher = preferred)')),
                ('last_success', models.DateTimeField(blank=True, help_text='Last successful data retrieval', null=True)),
                ('last_error', models.DateTimeField(blank=True, help_text='Last failed attempt', null=True)),
                ('error_count', models.IntegerField(default=0, help_text='Consecutive error count')),
                ('consecutive_successes', models.IntegerField(default=0, help_text='Consecutive successful requests')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_configs', to='telemetry.catchmentpoint', verbose_name='Punto de Captación')),
                ('variable', models.ForeignKey(help_text='Variable del punto que recibe datos de este proveedor', on_delete=django.db.models.deletion.CASCADE, related_name='provider_configs', to='telemetry.corevariable', verbose_name='Variable')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetry_providers.telemetryprovider', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Configuración de Proveedor por Punto',
                'verbose_name_plural': 'Configuraciones de Proveedor por Punto',
                'ordering': ['-priority', 'provider__name'],
                'unique_together': {('point', 'provider', 'variable')},
            },
        ),
        migrations.CreateModel(
            name='CatchmentPointMQTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_device_id', models.CharField(blank=True, help_text='ID personalizado del dispositivo (override del point_code)', max_length=100)),
                ('custom_topics', models.JSONField(blank=True, default=dict, help_text='\n        Topics personalizados para este punto.\n        Ejemplo: {"subscribe": "custom/{device_id}/data"}\n        ')),
                ('device_config', models.JSONField(blank=True, default=dict, help_text='\n        Configuración específica del dispositivo.\n        Ejemplo: {"calibration_factor": 1.23, "sensor_offset": 0.5}\n        ')),
                ('is_active', models.BooleanField(default=True, help_text='¿Esta configuración está activa?')),
                ('last_seen', models.DateTimeField(blank=True, help_text='Última vez que se recibió mensaje de este dispositivo', null=True)),
                ('point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mqtt_config', to='telemetry.catchmentpoint', verbose_name='Punto de Captación')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetry_providers.telemetryprovider', verbose_name='Proveedor MQTT')),
            ],
            options={
                'verbose_name': 'Configuración MQTT del Punto',
                'verbose_name_plural': 'Configuraciones MQTT de Puntos',
                'unique_together': {('point', 'provider')},
            },
        ),
    ]
