# Generated by Django 5.2.10 on 2026-01-19 15:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(help_text="Unique identifier for the provider (e.g., 'nettra', 'twin', 'novus')", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text="Human-readable name (e.g., 'Nettra IoT Platform')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the provider')),
                ('provider_type', models.CharField(choices=[('api', 'REST API'), ('mqtt', 'MQTT'), ('modbus', 'ModBus TCP'), ('http', 'HTTP Endpoint'), ('websocket', 'WebSocket')], default='api', help_text='Communication protocol used by the provider', max_length=20)),
                ('base_url', models.URLField(help_text='Base URL for API endpoints (e.g., https://api.nettra.cl)', validators=[django.core.validators.URLValidator()])),
                ('timeout_seconds', models.IntegerField(default=30, help_text='Request timeout in seconds')),
                ('auth_method', models.CharField(choices=[('none', 'No Authentication'), ('bearer', 'Bearer Token'), ('basic', 'Basic Authentication'), ('api_key', 'API Key'), ('oauth2', 'OAuth2'), ('custom', 'Custom Authentication')], default='bearer', help_text='Authentication method to use', max_length=20)),
                ('auth_config', models.JSONField(blank=True, default=dict, help_text='\n        Authentication configuration as JSON. Examples:\n        - Bearer: {"token": "your_token"}\n        - Basic: {"username": "user", "password": "pass"}\n        - API Key: {"key": "api_key", "header": "X-API-Key"}\n        - OAuth2: {"client_id": "id", "client_secret": "secret", "token_url": "url"}\n        ')),
                ('endpoint_template', models.CharField(help_text='\n        Template for building endpoint URLs. Use {variables}.\n        Examples:\n        - "/api/v1/devices/{device_id}/data"\n        - "/data?point={point_code}&variable={variable}"\n        ', max_length=500)),
                ('request_template', models.JSONField(blank=True, default=dict, help_text='\n        Template for request payload as JSON.\n        Use {variables} for dynamic content.\n        Example: {"device_id": "{device_code}", "variable": "{variable_type}"}\n        ')),
                ('response_mapping', models.JSONField(blank=True, default=dict, help_text='\n        Mapping for parsing API responses to standardized format.\n        Example: {\n            "timestamp": "data.time",\n            "value": "data.value",\n            "unit": "data.unit"\n        }\n        ')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this provider is available for use')),
                ('max_retries', models.IntegerField(default=3, help_text='Maximum number of retry attempts for failed requests')),
                ('retry_delay_seconds', models.IntegerField(default=1, help_text='Delay between retry attempts in seconds')),
                ('version', models.CharField(default='1.0', help_text='Provider API version', max_length=20)),
                ('documentation_url', models.URLField(blank=True, help_text='URL to provider documentation')),
            ],
            options={
                'verbose_name': 'Proveedor de Telemetría',
                'verbose_name_plural': 'Proveedores de Telemetría',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CatchmentPointProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('config_override', models.JSONField(blank=True, default=dict, help_text='\n        Override provider configuration for this specific point.\n        Same format as TelemetryProvider.auth_config.\n        ')),
                ('point_code', models.CharField(blank=True, help_text='Provider-specific identifier for this point (e.g., device ID, sensor code)', max_length=100)),
                ('device_config', models.JSONField(blank=True, default=dict, help_text='Device-specific configuration (e.g., sensor mappings, calibration data)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this provider configuration is active for the point')),
                ('priority', models.IntegerField(default=0, help_text='Priority for load balancing/failover (higher = preferred)')),
                ('last_success', models.DateTimeField(blank=True, help_text='Last successful data retrieval', null=True)),
                ('last_error', models.DateTimeField(blank=True, help_text='Last failed attempt', null=True)),
                ('error_count', models.IntegerField(default=0, help_text='Consecutive error count')),
                ('consecutive_successes', models.IntegerField(default=0, help_text='Consecutive successful requests')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_configs', to='telemetry.catchmentpoint', verbose_name='Punto de Captación')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.telemetryprovider', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Configuración de Proveedor por Punto',
                'verbose_name_plural': 'Configuraciones de Proveedor por Punto',
                'ordering': ['-priority', 'provider__name'],
                'unique_together': {('point', 'provider')},
            },
        ),
    ]
