# Generated by Django 5.2.10 on 2026-01-19 16:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_providers', '0001_initial'),
        ('telemetry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('name', models.CharField(help_text="Unique identifier (e.g., 'dga', 'sma', 'indh')", max_length=50, unique=True)),
                ('display_name', models.CharField(help_text="Human-readable name (e.g., 'DGA - Dirección General de Aguas')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the compliance provider')),
                ('service_type', models.CharField(choices=[('water_rights', 'Derechos de Agua'), ('environmental', 'Ambiental'), ('energy', 'Energía'), ('custom', 'Personalizado')], default='water_rights', help_text='Type of regulatory service', max_length=20)),
                ('base_url', models.URLField(help_text='Base URL for API endpoints (e.g., https://dga.cl/api)', validators=[django.core.validators.URLValidator()])),
                ('auth_endpoint', models.CharField(blank=True, help_text='Authentication endpoint (e.g., /v1/auth)', max_length=200)),
                ('data_endpoint_template', models.CharField(help_text='Template for data submission endpoint. Use {variables}. Example: /ufs/{uf_id}/procesos/{process_id}/registros', max_length=500)),
                ('timeout_seconds', models.IntegerField(default=30, help_text='Request timeout in seconds')),
                ('auth_method', models.CharField(choices=[('none', 'Sin Autenticación'), ('bearer', 'Bearer Token'), ('basic', 'Basic Auth'), ('oauth2', 'OAuth2 (user/pass → token)'), ('api_key', 'API Key'), ('custom', 'Personalizada')], default='bearer', help_text='Authentication method to use', max_length=20)),
                ('auth_config', models.JSONField(blank=True, default=dict, help_text='\n        Default authentication configuration as JSON. Examples:\n        - Bearer: {"token": "your_token"}\n        - Basic: {"username": "user", "password": "pass"}\n        - OAuth2: {"username": "user", "password": "pass", "token_field": "token"}\n        - API Key: {"key": "api_key", "header": "X-API-Key"}\n        ')),
                ('payload_template', models.JSONField(default=dict, help_text='\n        Template for building request payload. Use {config.*} for point config,\n        {record.*} for telemetry data. Example:\n        {\n            "codigo_obra": "{config.codigo_obra}",\n            "caudal": "{record.data.flow}",\n            "fecha": "{record.timestamp}"\n        }\n        ')),
                ('response_mapping', models.JSONField(blank=True, default=dict, help_text='\n        Mapping for parsing API responses. Example:\n        {\n            "success_field": "status",\n            "success_value": "ok",\n            "voucher_field": "comprobante",\n            "message_field": "mensaje"\n        }\n        ')),
                ('required_fields', models.JSONField(default=list, help_text='\n        Fields required for point configuration. Example:\n        [\n            {"name": "codigo_obra", "type": "string", "label": "Código de Obra"},\n            {"name": "rut_informante", "type": "string", "label": "RUT Informante"},\n            {"name": "caudal_otorgado", "type": "decimal", "label": "Caudal Otorgado (lt/s)"}\n        ]\n        ')),
                ('data_variables', models.JSONField(default=list, help_text='\n        Variables to capture from telemetry or manual input. Example:\n        [\n            {"name": "caudal", "type": "decimal", "label": "Caudal (lt/s)", "unit": "l/s"},\n            {"name": "nivel", "type": "decimal", "label": "Nivel (m)", "unit": "m"},\n            {"name": "total", "type": "decimal", "label": "Totalizado (m³)", "unit": "m3"}\n        ]\n        ')),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='Validation rules for data before submission')),
                ('submission_frequency', models.CharField(choices=[('on_record', 'Cada registro'), ('hourly', 'Cada hora'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], default='hourly', help_text='How often to submit data', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this provider is available for use')),
                ('max_retries', models.IntegerField(default=3, help_text='Maximum number of retry attempts for failed requests')),
                ('retry_delay_seconds', models.IntegerField(default=60, help_text='Delay between retry attempts in seconds')),
                ('documentation_url', models.URLField(blank=True, help_text='URL to provider documentation')),
            ],
            options={
                'verbose_name': 'Proveedor de Cumplimiento',
                'verbose_name_plural': 'Proveedores de Cumplimiento',
                'db_table': 'compliance_provider',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PointComplianceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('config_data', models.JSONField(default=dict, help_text='\n        Point-specific configuration values. Example:\n        {\n            "codigo_obra": "ND-0401-1234",\n            "rut_informante": "12345678-9",\n            "nombre_informante": "Juan Pérez",\n            "caudal_otorgado": 10.5,\n            "dispositivo_id": "12180"\n        }\n        ')),
                ('credentials_override', models.JSONField(blank=True, default=dict, help_text='\n        Override provider credentials for this point.\n        If empty, uses provider\'s default auth_config.\n        Example: {"username": "otro_rut", "password": "otra_clave"}\n        ')),
                ('data_source', models.CharField(choices=[('telemetry', 'Telemetría Automática'), ('manual', 'Ingreso Manual'), ('both', 'Ambos')], default='telemetry', help_text='Source of data for compliance submissions', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active')),
                ('send_compliance', models.BooleanField(default=False, help_text='Enable automatic submission to this provider')),
                ('last_submission', models.DateTimeField(blank=True, help_text='Last submission attempt', null=True)),
                ('last_success', models.DateTimeField(blank=True, help_text='Last successful submission', null=True)),
                ('last_error', models.TextField(blank=True, help_text='Last error message')),
                ('error_count', models.IntegerField(default=0, help_text='Consecutive error count')),
                ('total_submissions', models.IntegerField(default=0, help_text='Total submissions sent')),
                ('successful_submissions', models.IntegerField(default=0, help_text='Total successful submissions')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_configs', to='telemetry.catchmentpoint', verbose_name='Punto de Captación')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetry_providers.complianceprovider', verbose_name='Proveedor de Cumplimiento')),
            ],
            options={
                'verbose_name': 'Configuración de Cumplimiento por Punto',
                'verbose_name_plural': 'Configuraciones de Cumplimiento por Punto',
                'db_table': 'point_compliance_config',
                'ordering': ['point__title', 'provider__name'],
                'unique_together': {('point', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='ManualComplianceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('measurement_timestamp', models.DateTimeField(help_text='When the measurement was taken', verbose_name='Fecha/Hora de Medición')),
                ('data', models.JSONField(default=dict, help_text='\n        Measurement data. Example:\n        {"caudal": 10.5, "nivel": 15.2, "total": 1234}\n        ')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('queued', 'En Cola'), ('sent', 'Enviado'), ('error', 'Error'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('response_data', models.JSONField(blank=True, default=dict, help_text='Response received from the provider')),
                ('voucher', models.CharField(blank=True, help_text='Submission voucher/receipt from provider', max_length=200, verbose_name='Comprobante')),
                ('error_message', models.TextField(blank=True, help_text='Error message if submission failed')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the record was submitted to the provider', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_compliance_records', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_records', to='telemetry_providers.pointcomplianceconfig', verbose_name='Configuración de Cumplimiento')),
            ],
            options={
                'verbose_name': 'Registro Manual de Cumplimiento',
                'verbose_name_plural': 'Registros Manuales de Cumplimiento',
                'db_table': 'manual_compliance_record',
                'ordering': ['-measurement_timestamp'],
                'indexes': [models.Index(fields=['config', 'status'], name='manual_comp_config__2100bc_idx'), models.Index(fields=['measurement_timestamp'], name='manual_comp_measure_da71eb_idx'), models.Index(fields=['status'], name='manual_comp_status_d1f8f2_idx')],
            },
        ),
    ]
