# Generated by Django 5.2.10 on 2026-01-18 23:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
        ('telemetry', '__first__'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catchmentpointprovider',
            options={'ordering': ['-priority', 'provider__name'], 'verbose_name': 'Configuración de Proveedor por Punto', 'verbose_name_plural': 'Configuraciones de Proveedor por Punto'},
        ),
        migrations.RemoveField(
            model_name='catchmentpointprovider',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='telemetryprovider',
            name='auth_type',
        ),
        migrations.RemoveField(
            model_name='telemetryprovider',
            name='config_schema',
        ),
        migrations.RemoveField(
            model_name='telemetryprovider',
            name='headers',
        ),
        migrations.RemoveField(
            model_name='telemetryprovider',
            name='health_check_url',
        ),
        migrations.RemoveField(
            model_name='telemetryprovider',
            name='rate_limit',
        ),
        migrations.RemoveField(
            model_name='telemetryprovider',
            name='retry_count',
        ),
        migrations.RemoveField(
            model_name='telemetryprovider',
            name='retry_delay',
        ),
        migrations.RemoveField(
            model_name='telemetryprovider',
            name='supported_protocols',
        ),
        migrations.RemoveField(
            model_name='telemetryprovider',
            name='timeout',
        ),
        migrations.AddField(
            model_name='telemetryprovider',
            name='auth_method',
            field=models.CharField(choices=[('none', 'No Authentication'), ('bearer', 'Bearer Token'), ('basic', 'Basic Authentication'), ('api_key', 'API Key'), ('oauth2', 'OAuth2'), ('custom', 'Custom Authentication')], default='bearer', help_text='Authentication method to use', max_length=20),
        ),
        migrations.AddField(
            model_name='telemetryprovider',
            name='documentation_url',
            field=models.URLField(blank=True, help_text='URL to provider documentation'),
        ),
        migrations.AddField(
            model_name='telemetryprovider',
            name='max_retries',
            field=models.IntegerField(default=3, help_text='Maximum number of retry attempts for failed requests'),
        ),
        migrations.AddField(
            model_name='telemetryprovider',
            name='provider_type',
            field=models.CharField(choices=[('api', 'REST API'), ('mqtt', 'MQTT'), ('modbus', 'ModBus TCP'), ('http', 'HTTP Endpoint'), ('websocket', 'WebSocket')], default='api', help_text='Communication protocol used by the provider', max_length=20),
        ),
        migrations.AddField(
            model_name='telemetryprovider',
            name='request_template',
            field=models.JSONField(blank=True, default=dict, help_text='\n        Template for request payload as JSON.\n        Use {variables} for dynamic content.\n        Example: {"device_id": "{device_code}", "variable": "{variable_type}"}\n        '),
        ),
        migrations.AddField(
            model_name='telemetryprovider',
            name='response_mapping',
            field=models.JSONField(blank=True, default=dict, help_text='\n        Mapping for parsing API responses to standardized format.\n        Example: {\n            "timestamp": "data.time",\n            "value": "data.value",\n            "unit": "data.unit"\n        }\n        '),
        ),
        migrations.AddField(
            model_name='telemetryprovider',
            name='retry_delay_seconds',
            field=models.IntegerField(default=1, help_text='Delay between retry attempts in seconds'),
        ),
        migrations.AddField(
            model_name='telemetryprovider',
            name='timeout_seconds',
            field=models.IntegerField(default=30, help_text='Request timeout in seconds'),
        ),
        migrations.AddField(
            model_name='telemetryprovider',
            name='version',
            field=models.CharField(default='1.0', help_text='Provider API version', max_length=20),
        ),
        migrations.AlterField(
            model_name='catchmentpointprovider',
            name='config_override',
            field=models.JSONField(blank=True, default=dict, help_text='\n        Override provider configuration for this specific point.\n        Same format as TelemetryProvider.auth_config.\n        '),
        ),
        migrations.AlterField(
            model_name='catchmentpointprovider',
            name='consecutive_successes',
            field=models.IntegerField(default=0, help_text='Consecutive successful requests'),
        ),
        migrations.AlterField(
            model_name='catchmentpointprovider',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='catchmentpointprovider',
            name='device_config',
            field=models.JSONField(blank=True, default=dict, help_text='Device-specific configuration (e.g., sensor mappings, calibration data)'),
        ),
        migrations.AlterField(
            model_name='catchmentpointprovider',
            name='error_count',
            field=models.IntegerField(default=0, help_text='Consecutive error count'),
        ),
        migrations.AlterField(
            model_name='catchmentpointprovider',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this provider configuration is active for the point'),
        ),
        migrations.AlterField(
            model_name='catchmentpointprovider',
            name='last_error',
            field=models.DateTimeField(blank=True, help_text='Last failed attempt', null=True),
        ),
        migrations.AlterField(
            model_name='catchmentpointprovider',
            name='last_success',
            field=models.DateTimeField(blank=True, help_text='Last successful data retrieval', null=True),
        ),
        migrations.AlterField(
            model_name='catchmentpointprovider',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='catchmentpointprovider',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_configs', to='telemetry.catchmentpoint', verbose_name='Punto de Captación'),
        ),
        migrations.AlterField(
            model_name='catchmentpointprovider',
            name='point_code',
            field=models.CharField(blank=True, help_text='Provider-specific identifier for this point (e.g., device ID, sensor code)', max_length=100),
        ),
        migrations.AlterField(
            model_name='catchmentpointprovider',
            name='priority',
            field=models.IntegerField(default=0, help_text='Priority for load balancing/failover (higher = preferred)'),
        ),
        migrations.AlterField(
            model_name='catchmentpointprovider',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.telemetryprovider', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='telemetryprovider',
            name='auth_config',
            field=models.JSONField(blank=True, default=dict, help_text='\n        Authentication configuration as JSON. Examples:\n        - Bearer: {"token": "your_token"}\n        - Basic: {"username": "user", "password": "pass"}\n        - API Key: {"key": "api_key", "header": "X-API-Key"}\n        - OAuth2: {"client_id": "id", "client_secret": "secret", "token_url": "url"}\n        '),
        ),
        migrations.AlterField(
            model_name='telemetryprovider',
            name='base_url',
            field=models.URLField(help_text='Base URL for API endpoints (e.g., https://api.nettra.cl)', validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='telemetryprovider',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='telemetryprovider',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the provider'),
        ),
        migrations.AlterField(
            model_name='telemetryprovider',
            name='display_name',
            field=models.CharField(help_text="Human-readable name (e.g., 'Nettra IoT Platform')", max_length=200),
        ),
        migrations.AlterField(
            model_name='telemetryprovider',
            name='endpoint_template',
            field=models.CharField(help_text='\n        Template for building endpoint URLs. Use {variables}.\n        Examples:\n        - "/api/v1/devices/{device_id}/data"\n        - "/data?point={point_code}&variable={variable}"\n        ', max_length=500),
        ),
        migrations.AlterField(
            model_name='telemetryprovider',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this provider is available for use'),
        ),
        migrations.AlterField(
            model_name='telemetryprovider',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='telemetryprovider',
            name='name',
            field=models.CharField(help_text="Unique identifier for the provider (e.g., 'nettra', 'twin', 'novus')", max_length=100, unique=True),
        ),
    ]
