# Generated by Django 4.2.23 on 2026-01-20 17:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0004_configurationscheme_configurationschemefield_and_more"),
        ("providers", "0002_complianceprovider_pointcomplianceconfig_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MQTTProviderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "broker_host",
                    models.CharField(
                        help_text="Host/IP del broker MQTT (ej: broker.hivemq.com)",
                        max_length=255,
                    ),
                ),
                (
                    "broker_port",
                    models.IntegerField(
                        default=1883,
                        help_text="Puerto del broker MQTT (1883 para MQTT, 8883 para MQTTS)",
                    ),
                ),
                (
                    "use_tls",
                    models.BooleanField(
                        default=False, help_text="¿Usar TLS/SSL para la conexión?"
                    ),
                ),
                (
                    "client_id_prefix",
                    models.CharField(
                        default="smarthydro",
                        help_text="Prefijo para generar client_id únicos (ej: smarthydro)",
                        max_length=50,
                    ),
                ),
                (
                    "subscribe_topic_template",
                    models.CharField(
                        help_text='\n        Template para topics de suscripción. Usa {variables}:\n        - {provider}: Nombre del proveedor\n        - {device_id}: ID del dispositivo\n        - {point_code}: Código del punto\n        Ejemplo: "{provider}/{device_id}/telemetry"\n        ',
                        max_length=500,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Debe contener al menos una variable entre llaves {variable}",
                                regex="\\{[^}]+\\}",
                            )
                        ],
                    ),
                ),
                (
                    "publish_topic_template",
                    models.CharField(
                        blank=True,
                        help_text="\n        Template para topics de publicación (opcional).\n        Usa las mismas variables que subscribe_topic_template.\n        ",
                        max_length=500,
                    ),
                ),
                (
                    "default_qos",
                    models.IntegerField(
                        choices=[
                            (0, "0 - Al menos una vez"),
                            (1, "1 - Al menos una vez"),
                            (2, "2 - Exactamente una vez"),
                        ],
                        default=1,
                        help_text="QoS por defecto para mensajes",
                    ),
                ),
                (
                    "retain_messages",
                    models.BooleanField(
                        default=False, help_text="¿Retener mensajes en el broker?"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Usuario para autenticación MQTT (opcional)",
                        max_length=100,
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        help_text="Contraseña para autenticación MQTT (opcional)",
                        max_length=255,
                    ),
                ),
                (
                    "keep_alive",
                    models.IntegerField(
                        default=60, help_text="Intervalo keep-alive en segundos"
                    ),
                ),
                (
                    "reconnect_delay",
                    models.IntegerField(
                        default=5,
                        help_text="Delay entre reintentos de conexión en segundos",
                    ),
                ),
                (
                    "provider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mqtt_config",
                        to="providers.telemetryprovider",
                        verbose_name="Proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración MQTT del Proveedor",
                "verbose_name_plural": "Configuraciones MQTT de Proveedores",
            },
        ),
        migrations.CreateModel(
            name="PayloadParsingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre descriptivo de la regla", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada de cuándo y cómo usar esta regla",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("topic_match", "Coincidencia de Topic (Regex)"),
                            ("payload_field", "Campo específico en Payload"),
                            ("device_type", "Tipo de Dispositivo"),
                            ("always", "Siempre Aplicar (Default)"),
                        ],
                        default="always",
                        help_text="Tipo de condición para aplicar esta regla",
                        max_length=20,
                    ),
                ),
                (
                    "rule_condition",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='\n        Condición para aplicar la regla según rule_type:\n\n        topic_match: {"pattern": "novus/+/data"}\n        payload_field: {"field": "device_type", "value": "nxperience"}\n        device_type: {"type": "plc_siemens"}\n        always: {} (vacío)\n        ',
                    ),
                ),
                (
                    "parsing_method",
                    models.CharField(
                        choices=[
                            ("template", "Template con Variables"),
                            ("jsonpath", "JSONPath/JMESPath"),
                            ("python", "Script Python"),
                            ("regex", "Expresiones Regulares"),
                        ],
                        default="jsonpath",
                        help_text="Método para extraer datos del payload",
                        max_length=20,
                    ),
                ),
                (
                    "field_mappings",
                    models.JSONField(
                        default=dict,
                        help_text='\n        Mapeo de campos a extraer. Formato depende del parsing_method:\n\n        template: {"field_name": "payload.{json_field}"}\n        jsonpath: {"field_name": {"source": "$.data.value", "type": "jsonpath"}}\n        python: {"field_name": "extract_custom_field(payload)"}\n        regex: {"field_name": {"pattern": "value:(\\d+)", "group": 1}}\n        ',
                    ),
                ),
                (
                    "transformations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='\n        Lista de transformaciones a aplicar a los campos extraídos.\n        Ejemplo: [\n            {"field": "timestamp", "type": "unix_to_datetime"},\n            {"field": "flow", "type": "unit_conversion", "from": "m3/h", "to": "L/s"}\n        ]\n        ',
                    ),
                ),
                (
                    "validation_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='\n        Reglas de validación para campos extraídos.\n        Ejemplo: {\n            "flow": {"min": 0, "max": 1000},\n            "timestamp": {"not_null": true}\n        }\n        ',
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Prioridad de aplicación (mayor = primero)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="¿Esta regla está activa?"
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parsing_rules",
                        to="providers.telemetryprovider",
                        verbose_name="Proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla de Parsing de Payload",
                "verbose_name_plural": "Reglas de Parsing de Payload",
                "ordering": ["-priority", "name"],
                "unique_together": {("provider", "name")},
            },
        ),
        migrations.CreateModel(
            name="CatchmentPointMQTT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_device_id",
                    models.CharField(
                        blank=True,
                        help_text="ID personalizado del dispositivo (override del point_code)",
                        max_length=100,
                    ),
                ),
                (
                    "custom_topics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='\n        Topics personalizados para este punto.\n        Ejemplo: {"subscribe": "custom/{device_id}/data"}\n        ',
                    ),
                ),
                (
                    "device_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='\n        Configuración específica del dispositivo.\n        Ejemplo: {"calibration_factor": 1.23, "sensor_offset": 0.5}\n        ',
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="¿Esta configuración está activa?"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True,
                        help_text="Última vez que se recibió mensaje de este dispositivo",
                        null=True,
                    ),
                ),
                (
                    "point",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mqtt_config",
                        to="telemetry.catchmentpoint",
                        verbose_name="Punto de Captación",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="providers.telemetryprovider",
                        verbose_name="Proveedor MQTT",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración MQTT del Punto",
                "verbose_name_plural": "Configuraciones MQTT de Puntos",
                "unique_together": {("point", "provider")},
            },
        ),
    ]
