# Generated by Django
from django.db import migrations

def seed_providers(apps, schema_editor):
    TelemetryProvider = apps.get_model('providers', 'TelemetryProvider')

    # 1. NOVUS (Tago.io)
    # Auth: Authorization header (API Key)
    # URL: /data/?variable={variable}&query=last_item
    # Response: {"result": [{"time": "...", "value": ...}]}
    TelemetryProvider.objects.create(
        name='novus',
        display_name='Novus (Tago.io)',
        provider_type='http',
        base_url='https://api.tago.io',
        auth_method='api_key',
        auth_config={
            'header': 'authorization',
            'place': 'header'
        },
        endpoint_template='/data/?variable={variable}&query=last_item',
        response_mapping={
            'value': 'result.0.value',
            'timestamp': 'result.0.time',
            'unit': 'result.0.unit'
        },
        is_active=True
    )

    # 2. NETTRA (TheThings.io)
    # Auth: None (Token in URL path)
    # URL: /v2/things/{token}/resources/{variable}
    # Response: [{"datetime": "...", "value": ...}]
    TelemetryProvider.objects.create(
        name='nettra',
        display_name='Nettra (TheThings.io)',
        provider_type='http',
        base_url='https://api.thethings.io',
        auth_method='none',  # Token is part of URL
        auth_config={},
        endpoint_template='/v2/things/{token}/resources/{variable}',
        response_mapping={
            'value': '0.value',
            'timestamp': '0.datetime'
        },
        is_active=True
    )

    # 3. TWIN (Twin Dimension)
    # Auth: Login -> Bearer Token
    # URL: /tdata/v1/telemetry/DEVICE/{token}/values/timeseries?keys={variable}
    # Response: {"{variable}": [{"ts": 1234567890000, "value": 123.45}]}
    TelemetryProvider.objects.create(
        name='twin',
        display_name='Twin Dimension',
        provider_type='http',
        base_url='https://api.twindimension.com',
        auth_method='bearer',
        auth_config={
            'login_url': '/tdata/v1/login',
            'username': 'PLEASE_UPDATE_USERNAME',  # To be updated by admin/env
            'password': 'PLEASE_UPDATE_PASSWORD',  # To be updated by admin/env
            'token_key': 'token', # Key in login response
            'expiration_key': 'expires_in'
        },
        endpoint_template='/tdata/v1/telemetry/DEVICE/{token}/values/timeseries?keys={variable}',
        # Response mapping is tricky because the key is dynamic (the variable name).
        # DynamicAPIHandler generic parser handles "unknown key -> list -> value/ts" structure
        # if mapping is empty. Or we can implement specific logic later.
        # For now, we rely on _parse_generic_response logic or improved JsonPath if we supported wildcards.
        response_mapping={}, 
        is_active=True
    )

def reverse_seed(apps, schema_editor):
    TelemetryProvider = apps.get_model('providers', 'TelemetryProvider')
    TelemetryProvider.objects.filter(name__in=['novus', 'nettra', 'twin']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_catchmentpointprovider_options_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_providers, reverse_seed),
    ]
