# Generated by Django 5.2.10 on 2026-01-20 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_providers', '0003_add_mqtt_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('code', models.CharField(help_text='Código corto (ej: MAYOR, MEDIO, MENOR, CMP)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Nombre descriptivo (ej: Estándar Mayor)', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('frequency_type', models.CharField(choices=[('hourly', 'Por hora'), ('daily', 'Diario'), ('monthly', 'Mensual'), ('semestral', 'Semestral'), ('custom', 'Personalizado')], default='daily', max_length=20)),
                ('hour', models.IntegerField(default=0, help_text='Hora del envío (0-23)')),
                ('minute', models.IntegerField(default=0, help_text='Minuto del envío (0-59)')),
                ('day_of_month', models.IntegerField(blank=True, help_text='Día del mes para el envío (1-31)', null=True)),
                ('months', models.JSONField(blank=True, default=list, help_text='Lista de meses para envío (ej: [1, 7] para semestral)')),
                ('cron_expression', models.CharField(blank=True, help_text='Expresión cron equivalente (informativo)', max_length=100)),
                ('records_per_period', models.IntegerField(default=1, help_text='Cantidad de datos esperados por período')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estándar de Cumplimiento',
                'verbose_name_plural': 'Estándares de Cumplimiento',
                'db_table': 'compliance_standard',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='pointcomplianceconfig',
            name='compliance_standard',
            field=models.ForeignKey(blank=True, help_text='Define la frecuencia de envío (Mayor, Medio, Menor, CMP)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_configs', to='telemetry_providers.compliancestandard', verbose_name='Estándar de Cumplimiento'),
        ),
    ]
