# Generated by Django 5.2.10 on 2026-01-21 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_providers', '0004_compliancestandard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catchmentpointmqtt',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetry_providers.telemetryprovider', verbose_name='Proveedor MQTT'),
        ),
        migrations.AlterField(
            model_name='catchmentpointprovider',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetry_providers.telemetryprovider', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='manualcompliancerecord',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_records', to='telemetry_providers.pointcomplianceconfig', verbose_name='Configuración de Cumplimiento'),
        ),
        migrations.AlterField(
            model_name='mqttproviderconfig',
            name='provider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mqtt_config', to='telemetry_providers.telemetryprovider', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='payloadparsingrule',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsing_rules', to='telemetry_providers.telemetryprovider', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='pointcomplianceconfig',
            name='compliance_standard',
            field=models.ForeignKey(blank=True, help_text='Define la frecuencia de envío (Mayor, Medio, Menor, CMP)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_configs', to='telemetry_providers.compliancestandard', verbose_name='Estándar de Cumplimiento'),
        ),
        migrations.AlterField(
            model_name='pointcomplianceconfig',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetry_providers.complianceprovider', verbose_name='Proveedor de Cumplimiento'),
        ),
    ]
